### ISSUE TITLE
Dash in Patient by Identifier request is encoded twice

### ISSUE THREAD

**Issue by gansoper** [onc-healthit/inferno-program#127]
Thank you for reporting a possible bug in Inferno! Please fill in as much of the template below as you can.

**Subject of the issue**
Request is encoded twice

**Your environment**
* Edition of inferno (Community or Program): https://inferno.healthit.gov/inferno/ 
* Version of inferno: latest available
* Which browser and version(s) is the bug present on?: Chrome Version 83.0.4103.116 (Official Build) (64-bit)

**Steps to reproduce**
Patient needed with identifier:

{
      "use": "usual",
      "type": {
        "coding": [
          {
            "system": "http://terminology.hl7.org/CodeSystem/v2-0203",
            "code": "MR",
            "display": "Medical Record Number"
          }
        ],
        "text": "Medical Record Number"
      },
      "system": "http://hospital.davinciproject.org",
      "value": "123456"
    }

Include:

* The selected test suite:  Patient Tests
* The URL of the FHIR server being tested :  https://davinci.collablynk.com/emr/fhir/R4
* The Test ID, if it's a problem with a specific test. : USCP-02
* Any required configuration options (client ID, client secret, etc.) 

inferno_confidential
cf57bebe-b85f-47d4-a2b3-48b8312466a6

* Anything else needed to make the issue occur.

**Expected behavior**
Dash in  identifier=system|value must not be encoded twice

Real request must be the following
https://davinci.collablynk.com/emr/fhir/R4/Patient?identifier=http%3A%2F%2Fhospital.davinciproject.org%7C123456

**Actual behavior**
Second request with identifier=system|value is encoded twice 
First - dash is encoded.
https://davinci.collablynk.com/emr/fhir/R4/Patient?identifier=http://hospital.davinciproject.org%7C123456 

and actual invocation URL is 

https://davinci.collablynk.com/emr/fhir/R4/Patient?identifier=http%3A%2F%2Fhospital.davinciproject.org%257C123456

**Comment by yunwwang** [comment]
Hello gansoper: Thank you for reaching out to Inferno. We are investigating this issue. It would be really helpful if you can send us your saved test session so we can look into the REST communications. To save a test session, click the "Save" button on the top right corner after testing complete. Thank you.

**Comment by yunwwang** [comment]
I run some tests on hapi.fhir.org, api.logicahealth.org, and vonk.fire.ly. I queried `Condition?clinical-status=http://terminology.hl7.org/CodeSystem/condition-clinical%7Cresolved` or `Condition?clinical-status=http://terminology.hl7.org/CodeSystem/condition-clinical|resolved` All servers resolve the query parameters correctly.

**Comment by gansoper** [comment]
I successfully ran tests now.
