### ISSUE TITLE
Incorrectly requires `401` instead of `403` when scopes are insufficient in limited access tests.

### ISSUE THREAD

**Issue by arscan** [onc-healthit/inferno-program#129]
Tests that deny access due to insufficient scope needs to expect `403` instead of `401`.  This is an issue in AVR/AVU tests.

![image](https://user-images.githubusercontent.com/412901/85790119-b3569b00-b6fd-11ea-927b-0f38d7a5a45b.png)

This is also explicit in the FHIR spec itself:  https://www.hl7.org/fhir/security.html#AccessDenied

**Comment by yunwwang** [comment]
Fixed by PR130
