### ISSUE TITLE
Proprietary code/systems

### ISSUE THREAD

**Issue by kathypickering** [onc-healthit/inferno-program#136]
Unknown proprietary codes and systems are issuing a warning.  We recommend changing this to an "informational" message.

**Comment by yunwwang** [comment]
Hello kathypickering: Warning means the test passed while the tester may need to take a closer look, and manually inspect the results.
As for your use case, Inferno tests if the code is actually in the code system. When the code system is proprietary and not known to Inferno, Inferno could not run the test. As a result, Inferno warns the tester to manually check the code's validity.
