### ISSUE TITLE
Capability statement validation indicates group export does not resolve

### ISSUE THREAD

**Issue by darena-mhaque** [onc-healthit/inferno-program#147]
**Subject of the issue**
In the USCCAP-02 test, the result indicates that the group-export url does not resolve. Here is an image:
![image](https://user-images.githubusercontent.com/45796503/88231531-66091300-cc42-11ea-94b1-4ed61fbb6304.png)

However, the URL this _is_ resolvable. Here is the URL: http://hl7.org/fhir/uv/bulkdata/OperationDefinition/group-export. You can copy paste this to your browser window or postman and verify that the URL resolves.

**Your environment**
* Edition of inferno (Community or Program): Program
* Version of inferno: 1.0.2

**Steps to reproduce**
Run USCCAP-02 with any fhir server that defines the "$export" operation. You can view our server's metadata by going to: https://fhir-staging.bluebuttonpro.com/inferno-certification/metadata

**Comment by arscan** [comment]
We resolved this in [v1.1](https://github.com/onc-healthit/inferno-program/releases/tag/v1.1.0P), which was released and deployed yesterday.  I confirmed it no longer errors on the capability statement at https://fhir-staging.bluebuttonpro.com/inferno-certification/ (and I confirmed that it still has the group-export url referenced there).

Thanks for the report.  I'm going to close this, please comment here or open a new ticket if you are still seeing issues.
