### ISSUE TITLE
Capability statement validation indicates 'introspect' and 'revoke' security extensions are not defined

### ISSUE THREAD

**Issue by darena-mhaque** [onc-healthit/inferno-program#148]
**Subject of the issue**
In the USCCAP-02 test, the capability statement validation indicates that the values 'introspect' and 'revoke' are not defined by the extension http://fhir-registry.smarthealthit.org/StructureDefinition/oauth-uris. However, if we go to the URL where this extension is defined, http://www.hl7.org/fhir/smart-app-launch/StructureDefinition-oauth-uris.html, we can see that the 'introspect' and 'revoke' values are indeed defined.

**Your environment**
* Edition of inferno (Community or Program): Program
* Version of inferno: 1.0.2

**Steps to reproduce**
Run USCCAP-02 with any fhir server that supports the "http://fhir-registry.smarthealthit.org/StructureDefinition/oauth-uris" extension and has 'introspect' and 'revoke' as url values. You can view our server's metadata by going to: https://fhir-staging.bluebuttonpro.com/inferno-certification/metadata

**Comment by darena-mhaque** [comment]
Here's an image for clarity:
![image](https://user-images.githubusercontent.com/45796503/88232724-5d194100-cc44-11ea-87bd-b1448d0e3770.png)

**Comment by yunwwang** [comment]
Hello darena-mhaque:

We have realized this problem. There is a discussion on zulip https://chat.fhir.org/#narrow/stream/179170-smart/topic/OAuth-URIs.20Extension. We are working with Josh and Grahame to address that.

**Comment by arscan** [comment]
We resolved this in [v1.1](https://github.com/onc-healthit/inferno-program/releases/tag/v1.1.0P), which was released and deployed yesterday.  I confirmed it no longer errors on the capability statement at https://fhir-staging.bluebuttonpro.com/inferno-certification/ (and I confirmed that CapabilityStatement still has the oauth-uri extension in use).

Thanks for the report.  I'm going to close this, please comment here or open a new ticket if you are still seeing issues.
