### ISSUE TITLE
Docker installation issue:  Windows Server 2016, unable to install ruby

### ISSUE THREAD

**Issue by jgdxc** [onc-healthit/inferno-program#161]
Greetings,

My regrets if this is not the correct forum.  I am new to Inferno and am just attempting to install the container on Windows 2016 for the first time.  When attempting to build in docker the following error appears:

Step 1/16 : FROM ruby:2.5.6
2.5.6: Pulling from library/ruby
ERROR: Service 'ruby_server' failed to build: no matching manifest for windows/amd64 10.0.14393 in the manifest list entries

Thank you in advance for any leads on how to resolve this issue.

Jim

**Comment by okeefm** [comment]
Hello Jim,

Based on the error message, I believe that what is occurring here is that your Docker for Windows application is currently configured to use Windows containers, rather than Linux containers. If you right-click on the Docker icon in the System Tray, you should see an option that says "Switch to Linux Containers". If you click on that, and re-run the build, that should solve your issue. If it doesn't, let me know and we can investigate further.

Thank you,
Michael

**Comment by jgdxc** [comment]
Hi Michael,

Thank you for the guidance!  I’m attempting the install on a Windows 2016 VM, so we had to install the Docker Microsoft Provider (example):

Install-Module -Name DockerMsftProvider `
               -Repository PSGallery `
               -Force

I did find the guidance last night about how this might be resolved in Docker for Windows on a workstation, but it was one of many possible leads.  I’m following up on how to achieve the same aim on a server.  I did try to run ubuntu but hit a similar “wall”:

PS H:\inferno\Inferno Program Edition v1.1.0\inferno-program-1.1.0P> docker run -it ubuntu
Unable to find image 'ubuntu:latest' locally
latest: Pulling from library/ubuntu
C:\Program Files\Docker\docker.exe: no matching manifest for windows/amd64 10.0.14393 in the manifest list entries.

Jim

**Comment by arscan** [comment]
Hi Jim --

Have you been able to resolve this issue?  We use docker-compose, which starts a number of docker containers, so running `docker run` isn't quite right.  Have you tried the steps described in the [README](https://github.com/onc-healthit/inferno-program#docker-installation) (specifically, you should be running `docker-compose up --build`).

**Comment by jgdxc** [comment]
Hi Rob,

Thank you for reaching out!  Based on the lead provided, I realized quickly last week that the server implementation of docker was not properly configured.  At that point the effort went on hold temporarily as we focused on obtaining the NIH license.

I will try to verify the actual install soon and will follow up.

Jim

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by yunwwang** [comment]
@jgdxc 
Hi Jim: Are you still experiencing the same installation issue? If not, I will close this one.

**Comment by yunwwang** [comment]
Closed as no response
