### ISSUE TITLE
Inquiry - CapabilityStatement - US Core Observations

### ISSUE THREAD

**Issue by SavannahDearing** [onc-healthit/inferno-program#167]
Example capabilitystatement: [https://www.medentmobiletest.com/fhir/R4/metadata/index.php?medent_practice_id=savcw235](https://www.medentmobiletest.com/fhir/R4/metadata/index.php?medent_practice_id=savcw235)

For test USCCAP-05: Capability Statement lists support for required US Core Profiles

There are multiple Observation profiles, but the R4 CapabilityStatement does not allow multiple "profile" elements: http://hl7.org/fhir/R4/capabilitystatement.html

Does Inferno recognize the "supportedProfile" elements for this test? Or is there another way to express this?

**Comment by yunwwang** [comment]
Hello Savannah: Yes Inferno looks both profile and supportedProfile.
