### ISSUE TITLE
USCP-12 Address Period

### ISSUE THREAD

**Issue by SavannahDearing** [onc-healthit/inferno-program#169]
**Subject of the issue**
Patient.address[0].period: Object must have some content

Reading the Period definition[[https://www.hl7.org/fhir/datatypes.html#Period](https://www.hl7.org/fhir/datatypes.html#Period)], I see this:
_If the start element is missing, the start of the period is not known. If the end element is missing, it means that the period is ongoing, or the start may be in the past, and the end date in the future, which means that period is expected/planned to end at the specified time_

It seems if the Start is unknown, and the End is Ongoing, Period would be an empty object: "period": {},  Or is there another way to express this that the Inferno test is looking for?

**Comment by yunwwang** [comment]
If the start is unknown and end is ongoing, Period shall be omitted.
For example, this is correct
```
      "address": {
        "use": "home",
        "type": "both",
        "line": [
          "534 Erewhon St"
        ],
        "city": "PleasantVille",
        "district": "Rainbow",
        "state": "Vic",
        "postalCode": "3999"
      }
```
but this is not
```
      "address": {
        "use": "home",
        "type": "both",
        "line": [
          "534 Erewhon St"
        ],
        "city": "PleasantVille",
        "district": "Rainbow",
        "state": "Vic",
        "postalCode": "3999",
        "period": {}
      }
```

**Comment by SavannahDearing** [comment]
Ok, the Inferno test gives this when Period is not included, which sounds like an error "Could not find address.period in the 1 provided Patient resource(s)"  
I suppose it's not marked with a red X icon, so its not supposed to be considered an actual "error"?

**Comment by yunwwang** [comment]
Period is an Element. Element has constraint that "All FHIR elements must have a @value or children"

**Comment by SavannahDearing** [comment]
Yes, I meant that when the Period element is completely removed, Inferno seems to give an error, even though it is technically to spec to not include it in this specific case.

![uscp-13](https://user-images.githubusercontent.com/58518170/91726132-bfcbf980-eb6d-11ea-9b0b-3bf707b10ba1.png)

**Comment by yunwwang** [comment]
US Core IG defines that Patient.address.period is MUST SUPPORT. Inferno tests this US Core requirement by checking if the system has at least one Patient having this must supported element. Inferno marked this test as skipped because the patient provided for the testing did not have must supported Patient.address.period. Inferno provides an option to re-run all skipped test using different patient(s).
