### ISSUE TITLE
invalid DocumentReference.identifier values in uscore-testing-data-03-05-2020.zip test data

### ISSUE THREAD

**Issue by jschneid-nmdp** [onc-healthit/inferno-program#179]
Thank you for reporting a possible bug in Inferno! Please fill in as much of the template below as you can.

**Subject of the issue**

When running test data from uscore-testing-data-03-05-2020.zip through a FHIR validator, I'm seeing validation errors on DocumentReference.identifier that say, "if identifier.system is ''urn:ietf:rfc:3986'', then the identifier.value must be a full URI (e.g. start with a scheme)".  This error appears to be present in every DocumentReference.identifier.

Here's a brief example using Abigail677_Zieme486_621338a9-01f4-49d4-b852-14507a8bf8c7.json as input.

{
  "severity": "error",
  "code": "processing",
  "diagnostics": "if identifier.system is ''urn:ietf:rfc:3986'', then the identifier.value must be a full URI (e.g. start with a scheme)",
  "location": [
    "Parameters.parameter[0].resource.ofType(Bundle).entry[9].resource.ofType(DocumentReference).identifier[0]",
    "Line 1, Col 24010"
  ]
}

The Bundle.entry[9] DocumentReference.identifier looks like this:

{
  "system": "urn:ietf:rfc:3986",
  "value": "445d4eab-7da3-45cf-aa65-272344c8da08"
}

The identifier.value looks like a UUID, so presumably "urn:uuid:" should be prepended to it.

**Your environment**
* Edition of inferno (Community or Program):
* Version of inferno:
* Which browser and version(s) is the bug present on?:

I'm using only the uscore-testing-data (not a full Inferno edition).
https://github.com/inferno-community/uscore-data-sets

**Steps to reproduce**
Extract one of the JSON bundles from the zip file and send it to the Bundle/$validate endpoint of a FHIR server which supports validation.

E.g. ...

1) Construct file containing Parameters resource based on Abigail677_Zieme486_621338a9-01f4-49d4-b852-14507a8bf8c7.json

{
  "resourceType": "Parameters",
  "parameter": [ {
    "name": "resource",
    "resource":
<<< content of Abigail677_Zieme486_621338a9-01f4-49d4-b852-14507a8bf8c7.json >>>
  } ]
}

2) Submit the constructed _parameters.json file to FHIR server's Bundle/$validate endpoint.

cat Abigail677_Zieme486_621338a9-01f4-49d4-b852-14507a8bf8c7_parameters.json | curl --data @- --silent --verbose --request POST --url 'http://localhost:8080/r4/Bundle/$validate' --header 'content-type: application/fhir+json' --header 'accept: application/fhir+json' > Abigail677_Zieme486_621338a9-01f4-49d4-b852-14507a8bf8c7_validation-result-1.json

**Expected behavior**
The DocumentReference.identifier values should not trigger validation errors.

**Actual behavior**
DocumentReference.identifier values are invalid.

**Comment by okeefm** [comment]
Hello @jschneid-nmdp,

Thanks for bringing this to our attention! I'll look into this and get back to you. We have a series of updates coming out to the `uscore-data-sets` repository in the next few days, so hopefully we can address this issue during those updates.

**Comment by jschneid-nmdp** [comment]
In the meantime, here's a quick & dirty Python script to adjust the errant DocumentReference.identifier values.  (The script doesn't precisely preserve the bundle's decimal values, but at least doesn't change them to float values.)  Usage example:

```
cat Abigail677_Zieme486_621338a9-01f4-49d4-b852-14507a8bf8c7.json | ./fix179.py > Abigail677_Zieme486_621338a9-01f4-49d4-b852-14507a8bf8c7_fix179.json
```

fix179.py script:
```
#!/usr/local/bin/python3

import decimal
import json
import sys

class decfloat(float):
    def __init__(self,o):
        self.decval = o

    def __str__(self):
        return str(self.decval)

def decimal_default(obj):
    if isinstance(obj, decimal.Decimal):
        return decfloat(obj)
    raise TypeError

bundle = json.load(sys.stdin, parse_float=decimal.Decimal)

for entry in bundle['entry']:
    resource = entry['resource']
    if resource['resourceType'] == 'DocumentReference':
        for identifier in resource['identifier']:
            if identifier['system'] == 'urn:ietf:rfc:3986' and identifier['value'].find(':') < 0:
                identifier['value'] = "urn:uuid:{}".format(identifier['value'])

print(json.dumps(bundle, indent=2, default=decimal_default))
```

**Comment by yunwwang** [comment]
Fix released
