### ISSUE TITLE
Error Running NoMethodError: undefined method `fhir_version'

### ISSUE THREAD

**Issue by MJ422** [onc-healthit/inferno-program#192]
**Subject of the issue**
Describe your issue here.

In trying to run individual rake commands on the Inferno program source code's directory, we are met with some errors that seem to be internal to the source code itself (inferno-program-130P) 

Whenever we build out our command to execute_batch (as dictated in https://github.com/onc-healthit/inferno-program#running-automated-command-line-interface-scripts ) we are consistently hit with this error: 
**rake aborted!
NoMethodError: undefined method `fhir_version' for nil:NilClass
/var/www/inferno/lib/app/models/testing_instance.rb:171:in `fhir_version'**
![image](https://user-images.githubusercontent.com/44490162/95917755-bcd14500-0d78-11eb-976d-d85ec699e424.png)

Here is a screenshot of where it is failing in the source code: 
![image](https://user-images.githubusercontent.com/44490162/95917617-8abfe300-0d78-11eb-9cd3-28fab7039c57.png)

It seems that the "module" class is "nil" as of now - how can I work around this bug? 

**Your environment**
* Edition of inferno (Community or Program): inferno-program-130P
* Version of inferno: 3
* Which browser and version(s) is the bug present on?: N/A, within Windows 10 cmd

**Expected behavior**
Tell us what should happen.
- Execute the Inferno standalone tests based on data in the inferno.json file (which it is able to read)

**Actual behavior**
Tell us what happens instead. Include screenshots if possible.
![image](https://user-images.githubusercontent.com/44490162/95917726-b4790a00-0d78-11eb-913e-98efd7400851.png)

**Comment by Jammjammjamm** [comment]
What is the module name in the json file? It looks like Inferno can't find that module.

**Comment by arscan** [comment]
I'm going to close this because it is so old and might not be relevant any more.  If you try again and still have problems, please let us know and we'll work to debug that with you on the current version.
