### ISSUE TITLE
MetamorphoSys run failed

### ISSUE THREAD

**Issue by nwams** [onc-healthit/inferno-program#195]
**Subject of the issue**
When I try to Spot Check the Terminology Files I run the command **`bundle exec rake "terminology:check_code[91935009,http://snomed.info/sct, http://hl7.org/fhir/us/core/ValueSet/us-core-allergy-substance]"`** the rake is aborted. 

The same happens when I run the command: **`bundle exec rake "terminology:check_code[91935009,http://snomed.info/sct]"`**

**Your environment**
* Version of inferno: **inferno-program-1.3.0P**
* Which browser and version(s) is the bug present on?: **macOS Catalina v 10.15.5**

**Steps to reproduce**
I simply followed your instructions here https://github.com/onc-healthit/inferno-program step-by-step, locally. From Docker, to creating a UMLS account. 

I ran the terminology creation task with **`docker-compose -f terminology_compose.yml up`**. Which gave the following: **MetamorphoSys run failed**. See screenshot below: 

![image](https://user-images.githubusercontent.com/8648584/96901325-bae24280-1458-11eb-8a6b-0258168a18dc.png)

I did **NOT** do the cleanup step.

I then tried to proceed with Spot Checking the Terminology Files and encountered the errors below.

**Actual behavior**

For the command **`bundle exec rake "terminology:check_code[91935009,http://snomed.info/sct]" `**
```
chruby: unknown Ruby: 2.5.6
INFO | Inferno | Environment: development
/.gem/ruby/2.7.2/gems/json_pure-1.8.6/lib/json/common.rb:155: warning: Using the last argument as keyword parameters is deprecated
**rake aborted!**
Inferno::Terminology::UnknownValueSetException: Unknown ValueSet: http://hl7.org/fhir/us/core/ValueSet/us-core-allergy-substance
/Repos/inferno-program-1.3.0P/lib/app/utils/terminology.rb:241:in `validate_code'
lib/tasks/tasks.rake:1127:in `block (2 levels) in <top (required)>'
/.rubies/ruby-2.7.2/bin/bundle:23:in `load'
/.rubies/ruby-2.7.2/bin/bundle:23:in `<main>'
Tasks: TOP => terminology:check_code
(See full trace by running task with --trace)
```

For the command **`bundle exec rake "terminology:check_code[91935009,http://snomed.info/sct]"`**
```
chruby: unknown Ruby: 2.5.6
INFO | Inferno | Environment: development
/.gem/ruby/2.7.2/gems/json_pure-1.8.6/lib/json/common.rb:155: warning: Using the last argument as keyword parameters is deprecated
**rake aborted!**
Inferno::Terminology::ValueSet::UnknownCodeSystemException: Unknown Code System: http://snomed.info/sct
/Repos/inferno-program-1.3.0P/lib/app/utils/terminology.rb:244:in `validate_code'
lib/tasks/tasks.rake:1127:in `block (2 levels) in <top (required)>'
/.rubies/ruby-2.7.2/bin/bundle:23:in `load'
/.rubies/ruby-2.7.2/bin/bundle:23:in `<main>'
Tasks: TOP => terminology:check_code
(See full trace by running task with --trace)
```

Any thoughts on this? Thanks.

**Comment by okeefm** [comment]
Hello @nwams 

Taking a look at the error in the screenshots above, it looks like the terminology download step didn't complete properly. This can be caused by a couple of things. Can you confirm that you put your UMLS credentials into a `.env` file, in the inferno-program root directory, like so:

```
UMLS_USERNAME=a_username
UMLS_PASSWORD=a_password
```

Where `a_username` is replaced by your UMLS username, and `a_password` is replaced by your password?

Once that is accomplished, I would retry the whole terminology build process, by running the following two commands, in order.

`bundle exec rake terminology:cleanup`
followed by
`docker-compose -f terminology-compose.yml up`

Let me know if you have any questions, or if you run into any further issues.

Thank you,
Michael

**Comment by nwams** [comment]
@okeefm thanks. I had already previously included my username/password in both the .env file and the terminology-compose file, as strings in both files (within quotation marks). For example:

```
UMLS_USERNAME="xyz_username"
UMLS_PASSWORD="xyz_password"
```

I should also note that I added my username and password to the terminology_compose.yml file as well (same format). See screenshot. I blurred out my username/password. 
![image](https://user-images.githubusercontent.com/8648584/96928104-b3816000-147d-11eb-8ca8-f0fa5e816a97.png)

I hope that's correct? 

I'll try your suggestion of cleaning up then rerunning in a bit, will let you know.

**Comment by nwams** [comment]
@okeefm the cleanup and rebuilding worked. Thanks! Before I close this out, can you confirm whether the login credentials should be in a .env file or within the terminology_compose.yml file? Because I put it in both so I'm not sure which one is meant to be the source of truth.

**Comment by okeefm** [comment]
Hello @nwams,

Glad to hear it worked for you!

Either location should be fine. Specifying them in `terminology_compose.yml` will override anything specified in `.env`. 

Also, I think the reason they weren't working when only specified in `.env` is that Docker Compose interprets _everything_ after the equals sign as part of the variable, including quotation marks (according to [this link](https://docs.docker.com/compose/env-file/)). This is different than how they are handled in the `terminology_compose.yml` file.
