### ISSUE TITLE
Downloads from NLM no longer working (FI-1258)

### ISSUE THREAD

**Issue by dougpratt** [onc-healthit/inferno-program#203]
The NLM has changed the method for logging in, and now the content is not automatically loaded for INFERNO. Can this be fixed to work with the new login method?

-----Original Message-----
From: UMLS Notification <UMLS-NOTIFY@LIST.NIH.GOV> On Behalf Of NLM Customer Service
Sent: Monday, November 16, 2020 7:20 AM
To: UMLS-NOTIFY@LIST.NIH.GOV
Subject: UTS Login Changes and UMLS 2020 Annual Report

Dear UMLS Licensee,

**UTS Login Changes**

The UMLS Terminology Services (UTS) is moving from a username/password login to a service that allows you to sign in to the UTS using Google, Microsoft, Login.gov, or another identity provider of your choice.

**Comment by radamson** [comment]
Hey @dougpratt.

Thanks for reporting this issue. The team is aware of the updated NLM authorization method and we are actively working to update.  I anticipate this will be merged in the next week or so (Thanksgiving holiday throws a bit of a wrench in terms of timing).  We'll post an update once its ready.

**Comment by Jammjammjamm** [comment]
As a temporary workaround, if you download https://download.nlm.nih.gov/umls/kss/2019AB/umls-2019AB-full.zip, rename it `umls.zip` and place it in `tmp/terminology`, that should allow the terminology processing to skip the download step and continue normally.

**Comment by yunwwang** [comment]
PR: #337
