### ISSUE TITLE
Observation validation fails when using effectivePeriod

### ISSUE THREAD

**Issue by mbaltus** [onc-healthit/inferno-program#206]
When running the Single Patient API tests, the tests for Observations fail when I have one with the effectivePeriod field. This is the error message:
`Invalid Observation: Observation.effective.ofType(Period): vs-1: if Observation.effective[x] is dateTime and has a value then that value shall be precise to the day [($this as dateTime).toString().length() >= 8]`

Imho, this error is incorrect, since the vs-1 constraint should only fire when the field is of type dateTime.
If I do not supply an Observation with an effectivePeriod, I cannot get all the tests to pass either, since it is one of the mustSupport elements.

* Edition of inferno (Community or Program): Program
* Version of inferno: 1.3.0

**Steps to reproduce**
Add an Observation with an effectivePeriod field to your server and run the Single Patient API tests on that server.
See some of the Observation tests fail with the error listed above.

**Expected behavior**
The Observation with effectivePeriod should pass validation of the constraint without any problem.

**Comment by radamson** [comment]
@mbaltus see this related [chat.fhir.org discussion on the topic](https://chat.fhir.org/#narrow/stream/179309-inferno/topic/Single.20Patient.20API.20Observation.20Tests).

The consensus is that the error is correct and that the FHIRPath is wrong. We may resort to filtering this specific error out in the meantime because it may take a long time for this to get fixed in US Core.

**Comment by yunwwang** [comment]
Both FHIR OO and CGP work groups acknowledge the FHIRPath errors in FHIR Vital Sign profiles and US Core Lab Result profile. 
Here is the Zulip discussion: https://chat.fhir.org/#narrow/stream/179309-inferno/topic/Single.20Patient.20API.20Observation.20Tests
Here are the two FHIR trackers: https://jira.hl7.org/browse/FHIR-29654, https://jira.hl7.org/browse/FHIR-29658
We expect those fix to be released in next release of USCore and FHIR.

**Comment by arscan** [comment]
Since this is an acknowledged issue in the spec itself, we updated our test to ignore this very specific validation error. 
This was introduced in [v1.4.0](https://github.com/onc-healthit/inferno-program/releases/tag/v1.4.0P) that we released last month.

Thanks for the report!
