### ISSUE TITLE
Certificate Expired

### ISSUE THREAD

**Issue by dougpratt** [onc-healthit/inferno-program#209]
Thank you for reporting a possible bug in Inferno! Please fill in as much of the template below as you can.

**Subject of the issue**
The sites certificate has expired
https://packages.fhir.org/

If I hit that site and bypass the expired certificate it looks like they have moved the content to https://simplifier.net/packages.  So my guess is they have not update the Inferno code to point to the new site.

![Inferno1](https://user-images.githubusercontent.com/27502666/100761159-961aac80-33c0-11eb-8bfc-3f9d32a98217.jpg)
![Inferno2](https://user-images.githubusercontent.com/27502666/100761193-a03cab00-33c0-11eb-9e8b-45196ec59c39.jpg)

**Your environment**
* Edition of inferno (Community or Program):
* Version of inferno:
* Which browser and version(s) is the bug present on?:

**Steps to reproduce**
Tell us how to reproduce this issue.

Include:

* The selected test suite
* The URL of the FHIR server being tested
* The Test ID, if it's a problem with a specific test.
* Any required configuration options (client ID, client secret, etc.)
* Anything else needed to make the issue occur.

**Expected behavior**
Tell us what should happen.

**Actual behavior**
Tell us what happens instead. Include screenshots if possible.

**Comment by okeefm** [comment]
Hello @dougpratt,

Thanks for posting this issue. We're currently in the middle of updating the terminology infrastructure in Inferno Program to support US Core 3.1.1, so we'll look into this as we make those upgrades.

**Comment by nathanloyer** [comment]
I'm seeing this exact issue. I was attempting to update the terminology definitions because I was updating our deployment to use your recently released 1.4.0 version. When I start it up without updating the definitions I get this warning "Inferno is missing validator files for the following ValueSets: http://hl7.org/fhir/ValueSet/clinical-findings". And now when trying to update the definitions I get the certificate error.

**Comment by okeefm** [comment]
To anyone who's affected by this, there is a workaround that you can use until we're able to fix the underlying issue. If you're using Inferno from the GitHub repository, you can edit the `config.yml` file that's at the root of the Inferno installation to set `disable_verify_peer` to `true` (by default it should be `false`). This will let you download the required terminology files. We highly recommend resetting that variable to false before running any tests with Inferno.

**Comment by nathanloyer** [comment]
That workaround worked for me, although after making the config change I had to rebuild the docker image and clear out the temp directories and start over.

**Comment by arscan** [comment]
This looks to have resolved itself, because the packages.fhir.org cert has been renewed. @okeefm tested it and it works fine, even with SSL inspection turned on in config.yml.
