### ISSUE TITLE
Goal resource failing invariant rule which is not applicable

### ISSUE THREAD

**Issue by emily-alt** [onc-healthit/inferno-program#211]
Thank you for reporting a possible bug in Inferno! Please fill in as much of the template below as you can.

**Subject of the issue**
"FluentPath expression evaluates to false for USCoreGoalProfile invariant rule gol-1: Goal.target.measure is required if Goal.target.detail is populated."  However, Goal.target.detail is not populated. Sample JSON below.

Also, " Goal.lifecycleStatus: unable to evaluate FluentPath expression against JSON for USCoreGoalProfile invariant rule ele-1: All FHIR elements must have a @value or children". Though lifecycleStatus appears to be in order. 

{
  "resourceType": "Goal",
  "id": "2CF8017665E94ED49499D848BD6BFDC4.NRS.30274",
  "meta": {
    "lastUpdated": "2020-11-24T18:01:27-05:00"
  },
  "lifecycleStatus": "active",
  "subject": {
    "reference": "Patient/2CF8017665E94ED49499D848BD6BFDC4",
    "display": "Mcallister,Sathees Ron"
  },
  "target": [
    {
      "dueDate": "2021-11-04"
    }
  ]
}

**Your environment**
* Edition of inferno (Community or Program): Program
* Version of inferno: 1.3.0
* Which browser and version(s) is the bug present on?:

**Steps to reproduce**
Single Patient API Test suite > Test for Goal resource
Include resource which does not have Goal.target.detail populated
Consider if Goal.target.dueDate is causing the rule to be invoked??
Include resource which does have Goal.lifecycleStatus populated

Include:

* The selected test suite
* The URL of the FHIR server being tested
* The Test ID, if it's a problem with a specific test.
* Any required configuration options (client ID, client secret, etc.)
* Anything else needed to make the issue occur.

**Expected behavior**
Invariant rule should not be checked; should not fail test. 

**Actual behavior**
Invariant rule fails test; see issue description

**Comment by yunwwang** [comment]
Hello emily-alt: 
Thank you for reporting this issue.
Did you test this on inferno.healthit.gov or your own setup? 
If it is your own setup, what is your resource_validator setting? "internal" or "external"
Thank you

**Comment by emily-alt** [comment]
@yunwwang We are testing with our own setup and the resource_validator setting is "external"

**Comment by yunwwang** [comment]
Which external validator do you use?

**Comment by emily-alt** [comment]
@yunwwang I apologize, we are using the internal validator. 

A note on our process: 
We are deploying inferno on a instance in the cloud.  We then publish the content to that instance manually.   We then set it so Inferno uses the internal validator.  
The model settings file is set to external, hence the original incorrectly answered question, however that is overridden to internal.

**Comment by yunwwang** [comment]
OK. Internal validator uses the ruby FHIR model. There is a bug in the FHIR model which causing the FHIRPath validation failure. An alternative solution is to change to "external" validator. Inferno provides a validator web service wrapped around HL7 FHIR validator app. https://github.com/inferno-community/fhir-validator-wrapper.

**Comment by emily-alt** [comment]
Thank you @yunwwang I've passed this on to our admins. Any sense of when this will be fixed / working without requiring the workaround?

**Comment by arscan** [comment]
This has the same root cause as #220.  For ONC certification testing we recommend using the configuration provided through `docker-compose` as described in the README.  We hope to improve our ruby-based FHIRPath evaluator, which would reduce the complexity of our setup by not relying on a Java-based service, but I cannot say when we will have time to do that.
