### ISSUE TITLE
 USCPO-10: Observation.code.coding failed cardinality test (1..1) – found 2 

### ISSUE THREAD

**Issue by emily-alt** [onc-healthit/inferno-program#220]
Thank you for reporting a possible bug in Inferno! Please fill in as much of the template below as you can.

**Subject of the issue**
" USCPO-10: Observation resources returned from previous search conform to the US Core Pulse Oximetry Profile. Observation.code.coding failed cardinality test (1..1) – found 2"

While Observation.**code** has a cardinality of 1..1, Observation.code.**coding** has a cardinality of 1..* per definition of CodeableConcept data type http://hl7.org/fhir/R4/datatypes.html#CodeableConcept

![ProfileScreenGrab](https://user-images.githubusercontent.com/75340305/102553461-e10b1400-4090-11eb-96e3-e2875dac6f0f.jpg)

The example resource with US Core Pulse Oximetry profile in 3.1.1 demonstrates 2 codings (59480-5 and 2708-6). Link and snippet from US Core follow: 
https://www.hl7.org/fhir/us/core/Observation-satO2-fiO2.json.html
  "code" : {
    "coding" : [
      {
        "system" : "http://loinc.org",
        "code" : "2708-6",
        "display" : "Oxygen saturation in Arterial blood"
      },
      {
        "system" : "http://loinc.org",
        "code" : "59408-5",
        "display" : "Oxygen saturation in Arterial blood by Pulse oximetry"
      },
      {
        "system" : "urn:iso:std:iso:11073:10101",
        "code" : "150456",
        "display" : "MDC_PULS_OXIM_SAT_O2"
      }
    ]
  },

Unsure if this happens with other *code.coding elements, Observation or otherwise.

**Your environment**
* Edition of inferno (Community or Program): P
* Version of inferno: 1.4
* Which browser and version(s) is the bug present on?: Chrome 87.0.4280.88

**Steps to reproduce**
Tell us how to reproduce this issue.
Provide two or more code.coding values with Observation Pulse Ox resource

Include:

* The selected test suite
* The URL of the FHIR server being tested
* The Test ID, if it's a problem with a specific test.
* Any required configuration options (client ID, client secret, etc.)
* Anything else needed to make the issue occur.

**Expected behavior**
Tell us what should happen.

Cardinality of code.coding is 1..* per definition of CodeableConcept data type 
http://hl7.org/fhir/R4/datatypes.html#CodeableConcept

**Actual behavior**
Tell us what happens instead. Include screenshots if possible.

**Comment by radamson** [comment]
The example that you are referencing shouldn't have any issues. Are you using that exact resource in your tests or does it have a different `Observation.code`? If you are testing on the inferno.healthit.gov and can share a link that would be helpful too.

Also, can you confirm that the `resource_validator` configuration in `config.yml` is set to `external`?

**Comment by emily-alt** [comment]
We run Inferno in-house with internal validator. 

And no, that is not the exact resource, that's just the example from US Core. Attaching the exact. 
[ObsPulseOxCardFail.txt](https://github.com/onc-healthit/inferno-program/files/5717206/ObsPulseOxCardFail.txt)

**Comment by emily-alt** [comment]
@radamson To add to the previous comment, we are experiencing a similar failure with BP Profile test though it is also failing on cardinality of component in addition to failing on some singular appearing code checks. 

Resource body attached, Thanks for looking into it. 
[ObsBPCardFail.txt](https://github.com/onc-healthit/inferno-program/files/5717431/ObsBPCardFail.txt)


"USCOBP-10: Observation resources returned from previous search conform to the Observation Blood Pressure Profile.

Observation/9F2DD58252054F1F89F70FEEFADB202F.NRS.VS.48261: Observation.component failed cardinality test (1..1) – found 2
Observation/9F2DD58252054F1F89F70FEEFADB202F.NRS.VS.48261: Observation.component.code.coding.code value of '8462-4' did not match fixed value: 8480-6
Observation/9F2DD58252054F1F89F70FEEFADB202F.NRS.VS.48261: Observation.component failed cardinality test (1..1) – found 2
Observation/9F2DD58252054F1F89F70FEEFADB202F.NRS.VS.48261: Observation.component.code.coding.code value of '8480-6' did not match fixed value: 8462-4

**Comment by arscan** [comment]
This appears to be a deficiency in the Ruby-based FHIR-validator (the 'internal' validator as we call it), just like #211.  For ONC (g)(10) certification testing, we currently only fully support the configuration provided in the `docker-compose.yml`, which uses a specific version of the HL7 FHIR validator exposed as a service.  We decided to do this because upgrading our ruby solution to have fully compliant fhirpath and validation capabilities is a significant effort, and would be duplicative of what was already readily available in the hl7 validator.  We would like to take the time to do that eventually, but it is not high on our priority list (as of now).

Is it possible for you to use the default configuration, which uses that external hl7 validator service?  That would either involve deploying using the docker-compose setup, or standing up the hl7 validator service separately and pointing the config.yml to it.  We can help if you have any questions in doing that.

**Comment by emily-alt** [comment]
@arscan Roger. Thank you. I'll pass this on to the sys admin. I think the previous reply on #211 didn't quite spur action but this explainer seems like it has a much better chance. 

Happy Holidays.
