### ISSUE TITLE
MedicationRequest omitted test for referencing Medication

### ISSUE THREAD

**Issue by bh021790** [onc-healthit/inferno-program#225]
**Subject of the issue**
Currently there is a test specific to referencing Medication within MedicationRequest. According to the clarification in the v3.2 US Core profile: The server systems are not required to support both a code and a reference, but SHALL support at least one of these methods. The test is ‘omitted’ but I wanted to confirm its relevancy and ensure we will not be dinged for only supporting medicationCodeableConcept. The test name references US Core v3.1.1 but I wanted to see if the test would be removed with the Must Support clarification. 

**Your environment**
Edition of inferno (Community or Program): ONC Program Edition
Version of inferno: 1.4.1	
Which browser and version(s) is the bug present on?: Chrome Version 87.0.4280.141

**Steps to reproduce**
Select Program Edition>Enter endpointSelect>Select Single Patient API tab>Run Tests>Add a patient id

**Include:**
The selected test suite: Single Patient API tab	
The URL of the FHIR server being tested: https://fhir-open.cerner.com/r4/ec2458f2-1e24-41c8-b71b-0e701af7583d	
The Test ID, if it's a problem with a specific test: USCMR-11: Medication resources returned conform to US Core v3.1.1 profiles

**Expected behavior**
We would not expect to be tested for a reference to Medication

**Actual behavior**
There is an omitted test for not having a reference to Medication

**Comment by arscan** [comment]
If a test is 'omitted', it means that it does not apply to your system and does not need to be run  You can think of it as a 'pass', or 'removed for this server'.  An 'omit' will roll up as a pass (so if one test was omitted, but the rest passed, then your system will be marked as passed).  So you will not be dinged for this.

**Comment by bh021790** [comment]
Thanks for the confirmation! <sigh of relief!> Just wanting to see a million green checks but I'll take it!
