### ISSUE TITLE
Consistently receiving a 504

### ISSUE THREAD

**Issue by bh021790** [onc-healthit/inferno-program#226]
I have had consistent issues running Inferno. I continue to get a 504 response. I'm using an open endpoint and specifically only running the tests on the Single Patient API tab with one patient ID. I'm using Chrome. Any guidance is greatly appreciated.

**Comment by arscan** [comment]
Thanks for the report -- we are seeing this issue as well now after running the single patient tests against our reference fhir server.  It appears that the results are taking too long to render and our reverse proxy decides to cut off the request before the response is sent.  I'll let you know when we fix the issue.

**Comment by arscan** [comment]
We cleared out data and the single patient api test results are much more responsive.  Could you try again?

We are in the process of rewriting components of Inferno so it can better support heavy testing on inferno.healthit.gov.  So while my solution today was a temporary fix, we'll be rolling in more robust components over the coming months.  And we still encourage downloading and running inferno locally so you can avoid load issues on the shared inferno.healthit.gov server.
