### ISSUE TITLE
must-support checks are improperly applied to OperationOutcomes in the searchset Bundle

### ISSUE THREAD

**Issue by cooperthompson** [onc-healthit/inferno-program#229]
Thank you for reporting a possible bug in Inferno! Please fill in as much of the template below as you can.

**Subject of the issue**
For FHIR search interactions return a Bundle that has both the relevant resource (e.g. Immunization) _and_ an OperationOutcome, Inferno tries to validate must-support properties for AllergyIntolerance on the OperationOutcome.  In our case, we return informational OperationOutcomes, which should be allowed.

**Your environment**
* Edition of inferno (Community or Program):  Program
* Version of inferno: 1.4.1
* Which browser and version(s) is the bug present on?:  Chrome 88

**Steps to reproduce**
Run the Single Patient API tests against a server that returns OperationOutcomes in the searchset Bundle alongside the actual search results.  Unfortunately I don't have a public server for you to use for testing :(.  I did include some example Bundle responses so maybe you can load those into a reference server and use for testing?

Include:

* The selected test suite: All of the Single Patient API tests appear to have the same issue.
* The URL of the FHIR server being tested: an internal/non-public server (sorry, I know this will make testing/reproduction hard)
* The Test ID, if it's a problem with a specific test. USCI-01, USCI-08, USCI-09
* Any required configuration options (client ID, client secret, etc.)
* Anything else needed to make the issue occur.

**Expected behavior**
must-support validation logic should only run on a resource in a bundle if that resource is of the type that has the must support requirements.  If a search interaction returns a mix of the requested resource (e.g. Immunization) and OperationOutcome, the must-support requirements for Immunization should only be checked on the Immunization resources.

**Actual behavior**
The test fails, due looking for must-support elements on the OperationOutcome.  
Example Bundle responses are attached.  

[example_immunization_bundle.xml.txt](https://github.com/onc-healthit/inferno-program/files/5952389/example_immunization_bundle.xml.txt)
[example_immunization_bundle.json.txt](https://github.com/onc-healthit/inferno-program/files/5952390/example_immunization_bundle.json.txt)

Example errors:

**USCI-01**: Server returns valid results for Immunization search by patient. results...
Fatal Error: undefined method `patient' for #<FHIR::OperationOutcome:0x00007fe403771ca0 @id=nil, @meta=nil, @implicitRules=nil, @language=nil, @text=nil, @contained=[], @extension=[], @modifierExtension=[], @issue=[#<FHIR::OperationOutcome::Issue:0x00007fe4037716b0 @id=nil, @extension=[], @modifierExtension=[], @severity="warning", @code="processing", @details=#<FHIR::CodeableConcept:0x00007fe403770f58 @id=nil, @extension=[], @coding=[#<FHIR::Coding:0x00007fe403770c10 @id=nil, @extension=[], @system="urn:oid:1.2.840.114350.1.13.5325.1.7.2.657369", @version=nil, @code="4119", @display="This response includes information available to the authorized user at the time of the request. It may not contain the entire record available in the system.", @userSelected=nil, @source_hash={"system"=>"urn:oid:1.2.840.114350.1.13.5325.1.7.2.657369", "code"=>"4119", "display"=>"This response includes information available to the authorized user at the time of the request. It may not contain the entire record available in the system."}>], @text="This response includes information available to the authorized user at the time of the request. It may not contain the entire record available in the system.", @source_hash={"coding"=>[{"system"=>"urn:oid:1.2.840.114350.1.13.5325.1.7.2.657369", "code"=>"4119", "display"=>"This response includes information available to the authorized user at the time of the request. It may not contain the entire record available in the system."}], "text"=>"This response includes information available to the authorized user at the time of the request. It may not contain the entire record available in the system."}>, @diagnostics=nil, @location=[], @expression=[], @source_hash={"severity"=>"warning", "code"=>"processing", "details"=>{"coding"=>[{"system"=>"urn:oid:1.2.840.114350.1.13.5325.1.7.2.657369", "code"=>"4119", "display"=>"This response includes information available to the authorized user at the time of the request. It may not contain the entire record available in the system."}], "text"=>"This response includes information available to the authorized user at the time of the request. It may not contain the entire record available in the system."}}>], @source_hash={"resourceType"=>"OperationOutcome", "issue"=>[{"severity"=>"warning", "code"=>"processing", "details"=>{"coding"=>[{"system"=>"urn:oid:1.2.840.114350.1.13.5325.1.7.2.657369", "code"=>"4119", "display"=>"This response includes information available to the authorized user at the time of the request. It may not contain the entire record available in the system."}], "text"=>"This response includes information available to the authorized user at the time of the request. It may not contain the entire record available in the system."}}]}>

**USCI-08**: Immunization resources returned from previous search conform to the US Core Immunization Profile. results...
Fatal Error: undefined method `status' for #<FHIR::OperationOutcome:0x00007fe403771ca0 @id=nil, @meta=nil, @implicitRules=nil, @language=nil, @text=nil, @contained=[], @extension=[], @modifierExtension=[], @issue=[#<FHIR::OperationOutcome::Issue:0x00007fe4037716b0 @id=nil, @extension=[], @modifierExtension=[], @severity="warning", @code="processing", @details=#<FHIR::CodeableConcept:0x00007fe403770f58 @id=nil, @extension=[], @coding=[#<FHIR::Coding:0x00007fe403770c10 @id=nil, @extension=[], @system="urn:oid:1.2.840.114350.1.13.5325.1.7.2.657369", @version=nil, @code="4119", @display="This response includes information available to the authorized user at the time of the request. It may not contain the entire record available in the system.", @userSelected=nil, @source_hash={"system"=>"urn:oid:1.2.840.114350.1.13.5325.1.7.2.657369", "code"=>"4119", "display"=>"This response includes information available to the authorized user at the time of the request. It may not contain the entire record available in the system."}>], @text="This response includes information available to the authorized user at the time of the request. It may not contain the entire record available in the system.", @source_hash={"coding"=>[{"system"=>"urn:oid:1.2.840.114350.1.13.5325.1.7.2.657369", "code"=>"4119", "display"=>"This response includes information available to the authorized user at the time of the request. It may not contain the entire record available in the system."}], "text"=>"This response includes information available to the authorized user at the time of the request. It may not contain the entire record available in the system."}>, @diagnostics=nil, @location=[], @expression=[], @source_hash={"severity"=>"warning", "code"=>"processing", "details"=>{"coding"=>[{"system"=>"urn:oid:1.2.840.114350.1.13.5325.1.7.2.657369", "code"=>"4119", "display"=>"This response includes information available to the authorized user at the time of the request. It may not contain the entire record available in the system."}], "text"=>"This response includes information available to the authorized user at the time of the request. It may not contain the entire record available in the system."}}>], @source_hash={"resourceType"=>"OperationOutcome", "issue"=>[{"severity"=>"warning", "code"=>"processing", "details"=>{"coding"=>[{"system"=>"urn:oid:1.2.840.114350.1.13.5325.1.7.2.657369", "code"=>"4119", "display"=>"This response includes information available to the authorized user at the time of the request. It may not contain the entire record available in the system."}], "text"=>"This response includes information available to the authorized user at the time of the request. It may not contain the entire record available in the system."}}]}>

**USCI-09**: All must support elements are provided in the Immunization resources returned. results...
Fatal Error: undefined method `statusReason' for #<FHIR::OperationOutcome:0x00007fe403771ca0 @id=nil, @meta=nil, @implicitRules=nil, @language=nil, @text=nil, @contained=[], @extension=[], @modifierExtension=[], @issue=[#<FHIR::OperationOutcome::Issue:0x00007fe4037716b0 @id=nil, @extension=[], @modifierExtension=[], @severity="warning", @code="processing", @details=#<FHIR::CodeableConcept:0x00007fe403770f58 @id=nil, @extension=[], @coding=[#<FHIR::Coding:0x00007fe403770c10 @id=nil, @extension=[], @system="urn:oid:1.2.840.114350.1.13.5325.1.7.2.657369", @version=nil, @code="4119", @display="This response includes information available to the authorized user at the time of the request. It may not contain the entire record available in the system.", @userSelected=nil, @source_hash={"system"=>"urn:oid:1.2.840.114350.1.13.5325.1.7.2.657369", "code"=>"4119", "display"=>"This response includes information available to the authorized user at the time of the request. It may not contain the entire record available in the system."}>], @text="This response includes information available to the authorized user at the time of the request. It may not contain the entire record available in the system.", @source_hash={"coding"=>[{"system"=>"urn:oid:1.2.840.114350.1.13.5325.1.7.2.657369", "code"=>"4119", "display"=>"This response includes information available to the authorized user at the time of the request. It may not contain the entire record available in the system."}], "text"=>"This response includes information available to the authorized user at the time of the request. It may not contain the entire record available in the system."}>, @diagnostics=nil, @location=[], @expression=[], @source_hash={"severity"=>"warning", "code"=>"processing", "details"=>{"coding"=>[{"system"=>"urn:oid:1.2.840.114350.1.13.5325.1.7.2.657369", "code"=>"4119", "display"=>"This response includes information available to the authorized user at the time of the request. It may not contain the entire record available in the system."}], "text"=>"This response includes information available to the authorized user at the time of the request. It may not contain the entire record available in the system."}}>], @source_hash={"resourceType"=>"OperationOutcome", "issue"=>[{"severity"=>"warning", "code"=>"processing", "details"=>{"coding"=>[{"system"=>"urn:oid:1.2.840.114350.1.13.5325.1.7.2.657369", "code"=>"4119", "display"=>"This response includes information available to the authorized user at the time of the request. It may not contain the entire record available in the system."}], "text"=>"This response includes information available to the authorized user at the time of the request. It may not contain the entire record available in the system."}}]}>

**Comment by arscan** [comment]
Thanks for pointing out this oversight.  We'll address this ASAP.

Are you aware of any valid reason to send a resource other than the target resource or an OperationOutcome for US Core searches (besides the _include/_revinclude searches)?  I'd like to make an exception to just allow OperationOutcomes in addition to the target resource type, but want to verify there aren't other situations that are valid.

**Comment by cooperthompson** [comment]
I think just excluding OperationOutcome should be fine.  Since you control _include and _revinclude, I suppose you can handle those how you like.

Not to get to into the solution, but couldn't you just check that the resource is the type you expect before running the validations.  I know the US Core and base FHIR specs fairly well, and I can't think of any other resource types, but doing a resource type check seems like the most defensive solution.

**Comment by arscan** [comment]
Yes, we'll add a type check in there before we run the validation -- we try to be defensive but this one slipped through the cracks.  What I wasn't quite sure about is if we can fail for anything other than the expected resource type + OperationOutcome, or if we should simply ignore those other resource types (perhaps there are valid reasons for them to be sent).  I think the former is the better approach for now, and in case we missed some exception that allows for other resource types we'll address that when it comes up.

**Comment by yunwwang** [comment]
Fixed in #234

**Comment by arscan** [comment]
This was released last night in v1.5.0. Thanks for the report @cooperthompson.

**Comment by yunwwang** [comment]
Closed as fix has been released
