### ISSUE TITLE
CapabilityStatement validations don't check system-wide search params

### ISSUE THREAD

**Issue by cooperthompson** [onc-healthit/inferno-program#230]
**Subject of the issue**
CapabilityStatement allows you to specify search parameters in two places:
* At the system level (CapabilityStatement.rest.searchParam) - these apply to all resources
* At the resource level (CapabilityStatement.rest.resource.searchParam) - these only apply to the specific resource

Our server puts common parameters (_id, _count_, _revInclude, _include) at the system level since we support them for all resources.  It does not appear that Inferno is checking that, and is failing us because we do not specify them in the resource-level searchParam.

**Your environment**
* Edition of inferno (Community or Program): Program
* Version of inferno: 1.4.1
* Which browser and version(s) is the bug present on?: Chrome 88

**Steps to reproduce**
Tell us how to reproduce this issue.
Run the program validation on server that uses the server-level option for universally supported search params.

Include:

* The selected test suite
* The URL of the FHIR server being tested
* The Test ID, if it's a problem with a specific test.
* Any required configuration options (client ID, client secret, etc.)
* Anything else needed to make the issue occur.

**Expected behavior**
Tell us what should happen.
For validating that the common search parameters (_id, _count, etc.) are supported on a resource, check for both the system-level params (CapabilityStatement.rest.searchParams) *and* the resource-level params (CapabilityStatement.rest.resource.searchParam)

**Actual behavior**
Tell us what happens instead. Include screenshots if possible.
Validation will fail for any parameters that are only listed at the system level (i.e. it only checks the resource level search params)

Example cap statements:
[capstatement.json.txt](https://github.com/onc-healthit/inferno-program/files/5954139/capstatement.json.txt)
[capstatement.xml.txt](https://github.com/onc-healthit/inferno-program/files/5954140/capstatement.xml.txt)

**Comment by arscan** [comment]
Thanks, we are taking a look.  I was under the impression this is where you would document [cross-resource search parameters](https://www.hl7.org/fhir/http.html#vsearch) for things like:
```
 GET [base]?[parameters]{&_format=[mime-type]}
```

Which would be consistent with how system-level operations are defined. But apparently this is the space where you define parameters that apply to all resource-level searches?  Is there a way to define new system-level searches or are those just inferred based on the aggregate of all resource-level searches?

**Comment by cooperthompson** [comment]
Hmm.. I suppose that is an interpretation question for CapabilityStatement.  I'll post a question on chat.fhir to get clarification.

**Comment by cooperthompson** [comment]
https://chat.fhir.org/#narrow/stream/179166-implementers/topic/CapabilityStatement.2Erest.2EsearchParams.20.20for.20common.20params

**Comment by cooperthompson** [comment]
I'll very likely be closing this based on discussion in chat.fhir.  I'm going to leave it open for a bit longer to see if any other discussion ensues that would change the outcome.

**Comment by arscan** [comment]
Sounds good, thanks!  I appreciate your willingness to update your implementation based on the intent of the spec, even if the words written in the current version are not very clear.

**Comment by cooperthompson** [comment]
Closing, as the consensus is that the FHIR spec didn't intend for rest.searchParam be used for params that apply to all resources.  Those involved agreed that the wording in the spec was unclear.  I submitted [FHIR#31051](https://jira.hl7.org/browse/FHIR-31051) against the FHIR spec to clarify the meaning to avoid future ambiguity.
