### ISSUE TITLE
Patient.name search validation appears to have escaping issues

### ISSUE THREAD

**Issue by cooperthompson** [onc-healthit/inferno-program#231]
**Subject of the issue**
When testing "name" searching for Patient, it appears that Inferno grabs the first name listed in Patient.name, pulls the text property, then issues a search Patient?name=<text name>.  It looks like the search is escaped in the actual query.  For example:

https://vs-icx.epic.com/Interconnect-CDE/api/FHIR/R4/Patient?name=Fhir%5C,%20Auto

However, when validating the search result against the expected name value, it seems to be comparing a partial escaped value.  

**Your environment**
* Edition of inferno (Community or Program):  Program
* Version of inferno: 1.4.1
* Which browser and version(s) is the bug present on?: Chrome 88

**Steps to reproduce**
Tell us how to reproduce this issue.
Validate a patient "name" search where the first listed name has a comma.

Include:

* The selected test suite: Single Patient API
* The URL of the FHIR server being tested: https://vs-icx.epic.com/Interconnect-CDE/api/FHIR/R4 (it's not public, sorry!)
* The Test ID, if it's a problem with a specific test.  USCP-03
* Any required configuration options (client ID, client secret, etc.)
* Anything else needed to make the issue occur.

**Expected behavior**
Tell us what should happen.
I'm not 100% sure.  Validating name searching is tricky.  A sufficient solution for us is just resolving what I think is an escaping issue.

Also, it looks like USCP-03 is just picking the first name, regardless of whether it is an "old", "usual", or "official" name.  This seems fine, and would work for us if we just fix the escaping, but do you want to validate usual names instead?  old name are part of USCDI, but it seems like the more common real-world use case is usual names, so making sure those work seems more useful.  Or maybe check that searching both old and usual names?

**Actual behavior**
Tell us what happens instead. Include screenshots if possible.
Here is the FHIR searchset Bundle with the full patient resource that was causing the issue:
[fhirpatientsearch.json.txt](https://github.com/onc-healthit/inferno-program/files/5954337/fhirpatientsearch.json.txt)

![image](https://user-images.githubusercontent.com/5863379/107430186-70a9cd80-6aea-11eb-978d-07e2f05f502b.png)

`name in Patient/e5ZHnklVuYuT85PnDVOepOg3 ([#<FHIR::HumanName:0x00007f09943bb100 @id=nil, @extension=[], @use="old", @text="Fhir, Auto", @family=nil, @given=[], @prefix=[], @suffix=[], @period=nil, @source_hash={"use"=>"old", "text"=>"Fhir, Auto"}>, #<FHIR::HumanName:0x00007f09943ba9a8 @id=nil, @extension=[], @use="old", @text="FHIR,AUTOMATION", @family=nil, @given=[], @prefix=[], @suffix=[], @period=nil, @source_hash={"use"=>"old", "text"=>"FHIR,AUTOMATION"}>, #<FHIR::HumanName:0x00007f09943ba2a0 @id=nil, @extension=[], @use="old", @text="FHIR,AUTOMATION SR.", @family=nil, @given=[], @prefix=[], @suffix=[], @period=nil, @source_hash={"use"=>"old", "text"=>"FHIR,AUTOMATION SR."}>, #<FHIR::HumanName:0x00007f09943b9b48 @id=nil, @extension=[], @use="official", @text="Automation FHIR Sr.", @family="FHIR", @given=["Automation"], @prefix=[], @suffix=["SR."], @period=nil, @source_hash={"use"=>"official", "text"=>"Automation FHIR Sr.", "family"=>"FHIR", "given"=>["Automation"], "suffix"=>["SR."]}>, #<FHIR::HumanName:0x00007f09943b8ef0 @id=nil, @extension=[], @use="usual", @text="Automation FHIR Sr.", @family="FHIR", @given=["Automation"], @prefix=[], @suffix=["SR."], @period=nil, @source_hash={"use"=>"usual", "text"=>"Automation FHIR Sr.", "family"=>"FHIR", "given"=>["Automation"], "suffix"=>["SR."]}>]) does not match name requested (Fhir\, Auto)`

**Comment by yunwwang** [comment]
Issue is fixed at #242
