### ISSUE TITLE
Related Person is a contained resource within the Care Team. When the such contained resource is included in the response, the Inferno Care Team test USCCT-01 is failing.

### ISSUE THREAD

**Issue by IgLysk00** [onc-healthit/inferno-program#232]
Thank you for reporting a possible bug in Inferno! Please fill in as much of the template below as you can.

**Subject of the issue**
Inferno Single Patient API Care Team test USCCT-01 is issued an error message: Fatal Error undefined method ‘name’ for nil:NilClass  due to Inferno is not supporting Related Person profile. According to HL7 FHIR Release 4, https://www.hl7.org/fhir/careteam-definitions.html#CareTeam.participant.member,  CareTeam profile supports Related Person.

**Your environment**
* Edition of inferno (Community or Program): Program
* Version of inferno: 1.4.1
* Which browser and version(s) is the bug present on?: Chrome

**Steps to reproduce**
Tell us how to reproduce this issue.
Patient needs to have a Related Person in the Care Team according to https://www.hl7.org/fhir/relatedperson.html
Run Single Patient API Care Team tests.

Include:

* The selected test suite: Single Patient API 
* The URL of the FHIR server being tested: https://fhir-myrecord-sc.stagingcerner.com/r4/3f2aca24-87f3-4eac-a6d7-1f75247e6b43 (not a public URL)
* The Test ID, if it's a problem with a specific test.: USCCT-01
* Any required configuration options (client ID, client secret, etc.)
* Anything else needed to make the issue occur.: Application workflow should allow to add a Related Person to the patient’s record. 

**Expected behavior**
Tell us what should happen.
The Care Team test USCCT-01 should not fail when the response contains Related Person

**Actual behavior**
Tell us what happens instead. Include screenshots if possible.
![image](https://user-images.githubusercontent.com/73243391/107539825-5a0b8100-6b93-11eb-9344-6c24827e868e.png)
[Care Team error.docx](https://github.com/onc-healthit/inferno-program/files/5959749/Care.Team.error.docx)

**Comment by yunwwang** [comment]
Hello @IgLysk00: Is this RelatedPerson embedded in Patient resource? Would you mind to include an example of Patient instance with contained RelatedPerson? Thank you.

**Comment by IgLysk00** [comment]
GET   200   https://fhir-myrecord-sc.stagingcerner.com/r4/3f2aca24-87f3-4eac-a6d7-1f75247e6b43/CareTeam?patient=A879904FD2FE4B2D90C89FDA84E1285F&status=active
Request
Headers
User-Agent: Ruby FHIR Client
Accept-Charset: utf-8
Accept: application/fhir+json
Authorization: Bearer eyJraWQiOiIyMDIxLTAyLTA5VDExOjI0OjQ0Ljc2OC5lYyIsInR5cCI6IkpXVCIsImFsZyI6IkVTMjU2In0.eyJpc3MiOiJodHRwczpcL1wvYXV0aG9yaXphdGlvbi5zYW5kYm94Y2VybmVyLmNvbVwvIiwiZXhwIjoxNjEyOTkwMTgwLCJpYXQiOjE2MTI5ODk1ODAsImp0aSI6ImFmNTQzMzQ0LWViOTItNDZiMy04MGZkLThkNzQzY2IyMTdjYiIsInVybjpjZXJuZXI6YXV0aG9yaXphdGlvbjpjbGFpbXM6dmVyc2lvbjoxIjp7InZlciI6IjEuMCIsInByb2ZpbGVzIjp7InNtYXJ0LXYxIjp7InBhdGllbnRzIjpbIkE4Nzk5MDRGRDJGRTRCMkQ5MEM4OUZEQTg0RTEyODVGIl0sImF6cyI6ImZoaXJVc2VyIGxhdW5jaFwvcGF0aWVudCBvZmZsaW5lX2FjY2VzcyBvcGVuaWQgcGF0aWVudFwvQWxsZXJneUludG9sZXJhbmNlLnJlYWQgcGF0aWVudFwvQ2FyZVBsYW4ucmVhZCBwYXRpZW50XC9DYXJlVGVhbS5yZWFkIHBhdGllbnRcL0NvbmRpdGlvbi5yZWFkIHBhdGllbnRcL0RldmljZS5yZWFkIHBhdGllbnRcL0RpYWdub3N0aWNSZXBvcnQucmVhZCBwYXRpZW50XC9Eb2N1bWVudFJlZmVyZW5jZS5yZWFkIHBhdGllbnRcL0VuY291bnRlci5yZWFkIHBhdGllbnRcL0dvYWwucmVhZCBwYXRpZW50XC9JbW11bml6YXRpb24ucmVhZCBwYXRpZW50XC9NZWRpY2F0aW9uUmVxdWVzdC5yZWFkIHBhdGllbnRcL09ic2VydmF0aW9uLnJlYWQgcGF0aWVudFwvUGF0aWVudC5yZWFkIHBhdGllbnRcL1Byb2NlZHVyZS5yZWFkIHVzZXJcL09yZ2FuaXphdGlvbi5yZWFkIHVzZXJcL1ByYWN0aXRpb25lci5yZWFkIn19LCJjbGllbnQiOnsibmFtZSI6IlNDIEluZmVybm8gQ29uZmlkZW50aWFsIENsaWVudCBBcHAgLSBQYXRpZW50IiwiaWQiOiJjYjhkZjliNy1lNWVjLTQ5MWYtODYzMi05OTE1ODFiNGU1MTUifSwidXNlciI6eyJwcmluY2lwYWwiOiJURU1QX0FQSV9VU0VSIiwicGVyc29uYSI6InBhdGllbnQiLCJpZHNwIjoiY2UyMGI5ZDgtZDAzNi00MWQwLWEzNDctZjNiNDQwZjE5NWUzIiwic2Vzc2lvbklkIjoiYjBhMGY5OWMtMjUyOS00ZTFlLWFjYzItODhhZTNmNzM0NmMwIiwicHJpbmNpcGFsVHlwZSI6InVzZXJuYW1lIiwicHJpbmNpcGFsVXJpIjoidXJuOmNlcm5lcjppZGVudGl0eS1mZWRlcmF0aW9uOnJlYWxtOmNlMjBiOWQ4LWQwMzYtNDFkMC1hMzQ3LWYzYjQ0MGYxOTVlMzpwcmluY2lwYWw6VEVNUF9BUElfVVNFUiIsImlkc3BVcmkiOiJodHRwczpcL1wvaWRmZWQtZGVtby5zYW5kYm94ZXhhbXBsZWhlYWx0aC5jb21cL3BvcnRhbCJ9LCJ0ZW5hbnQiOiIzZjJhY2EyNC04N2YzLTRlYWMtYTZkNy0xZjc1MjQ3ZTZiNDMifX0.XYhzqkfadEnp8zqjRhGhcUKmT6-JDnYwW2QyHo37m8m-GulaKgt8z_l5wl6NgyzFKRykHvG61K9lpmPrMqGvzQ
Response
Headers
content-type: application/json
content-length: 5548
connection: keep-alive
date: Wed, 10 Feb 2021 20:40:32 GMT
cache-control: private
expires: Thu, 01 Jan 1970 00:00:00 GMT
access-control-allow-origin: *
access-control-allow-methods: POST, GET, OPTIONS, DELETE
access-control-max-age: 3600
access-control-allow-headers: x-requested-with, X-Auth-Token, Content-Type, Authorization
x-correlation-id: 2a2b0134-c208-409f-a4f5-f6aecbc75de8
vary: Accept-Encoding
x-cache: Miss from cloudfront
via: 1.1 e88b34dd0e6a8e6f16f12ba472ae0c12.cloudfront.net (CloudFront)
x-amz-cf-pop: IAD50-C2
x-amz-cf-id: BF1K2PpMnQD-m1_jseJuTwDbh0QxzChDsfzwoqAMedIG1Bqf1k2VQw==
Body
{
  "resourceType": "Bundle",
  "id": "cf41b587-26f0-4748-8409-985346929ec7",
  "type": "searchset",
  "timestamp": "2021-02-10T15:40:32-05:00",
  "entry": [
    {
      "fullUrl": "https://fhir-myrecord-sc.stagingcerner.com/r4/3f2aca24-87f3-4eac-a6d7-1f75247e6b43/CareTeam/A879904FD2FE4B2D90C89FDA84E1285F.LCC",
      "resource": {
        "resourceType": "CareTeam",
        "id": "A879904FD2FE4B2D90C89FDA84E1285F.LCC",
        "meta": {
          "lastUpdated": "2020-12-16T20:03:37-05:00"
        },
        "status": "active",
        "subject": {
          "reference": "Patient/A879904FD2FE4B2D90C89FDA84E1285F",
          "display": "Mcgovern,Astrid Santiago"
        },
        "category": [
          {
            "coding": [
              {
                "system": "http://loinc.org",
                "code": "LA28865-6",
                "display": "Longitudinal care-coordination focused care team"
              }
            ]
          }
        ],
        "participant": [
          {
            "role": [
              {
                "coding": [
                  {
                    "system": "http://nucc.org/provider-taxonomy",
                    "code": "207QA0000X",
                    "display": "Family Medicine"
                  }
                ],
                "text": "Additional Doctor"
              }
            ],
            "member": {
              "reference": "Practitioner/4F69EC72C5AA48988E5E73832887E634",
              "display": "Aguilar,Melva Delaine"
            }
          },
          {
            "role": [
              {
                "text": "ZRAut_AutPhysicianG12"
              }
            ],
            "member": {
              "reference": "#203049"
            }
          },
          {
            "role": [
              {
                "text": "HC Proxy - Primary"
              }
            ],
            "member": {
              "reference": "#202549"
            }
          },
          {
            "role": [
              {
                "text": "Patient Centered Medical Home"
              }
            ],
            "member": {
              "reference": "Organization/STF.196052"
            }
          },
          {
            "role": [
              {
                "text": "Primary Physician"
              }
            ],
            "member": {
              "reference": "Practitioner/A06BB34813644589BA7E50D8DDC8EFAA",
              "display": "McFadden,John"
            }
          }
        ],
        "contained": [
          {
            "resourceType": "RelatedPerson",
            "id": "203049",
            "patient": {
              "reference": "Patient/A879904FD2FE4B2D90C89FDA84E1285F",
              "display": "Mcgovern,Astrid Santiago"
            },
            "relationship": [
              {
                "text": "ZRAut_AutPhysicianG12"
              }
            ],
            "name": [
              {
                "use": "official",
                "text": "John,McGovern",
                "family": "John",
                "given": [
                  "McGovern"
                ]
              }
            ]
          },
          {
            "resourceType": "RelatedPerson",
            "id": "202549",
            "patient": {
              "reference": "Patient/A879904FD2FE4B2D90C89FDA84E1285F",
              "display": "Mcgovern,Astrid Santiago"
            },
            "relationship": [
              {
                "text": "HC Proxy - Primary"
              }
            ],
            "name": [
              {
                "use": "official",
                "text": "Mcallister,Sathees ",
                "family": "Mcallister",
                "given": [
                  "Sathees "
                ]
              }
            ]
          }
        ],
        "text": {
          "status": "generated",
          "div": "<div xmlns=\"http://www.w3.org/1999/xhtml\"><b>CareTeam</b><br /><b>Patient</b>:Mcgovern,Astrid Santiago<br /><b>Status</b>:active<br /><b>Category</b>:<b>System</b>:http://loinc.org <b>Code</b>:LA28865-6 <b>Display</b>:Longitudinal care-coordination focused care team<br /><b>Role</b>:<b>System</b>:http://nucc.org/provider-taxonomy <b>Code</b>:207QA0000X <b>Display</b>:Family Medicine <b>Text</b>:Additional Doctor<br /><b>CareTeam Member</b>:Aguilar,Melva Delaine<br /><b>Role</b>:<b>Text</b>:ZRAut_AutPhysicianG12<br /><b>CareTeam Member</b>:John,McGovern<br /><b>Role</b>:<b>Text</b>:HC Proxy - Primary<br /><b>CareTeam Member</b>:Mcallister,Sathees <br /><b>Role</b>:<b>Text</b>:Patient Centered Medical Home<br /><b>Role</b>:<b>Text</b>:Primary Physician<br /><b>CareTeam Member</b>:McFadden,John<br /><br /></div>"
        }
      }
    },
    {
      "fullUrl": "https://fhir-myrecord-sc.stagingcerner.com/r4/3f2aca24-87f3-4eac-a6d7-1f75247e6b43/CareTeam/A879904FD2FE4B2D90C89FDA84E1285F.ENC.29019",
      "resource": {
        "resourceType": "CareTeam",
        "id": "A879904FD2FE4B2D90C89FDA84E1285F.ENC.29019",
        "meta": {
          "lastUpdated": "2020-11-11T20:53:17-05:00"
        },
        "status": "active",
        "subject": {
          "reference": "Patient/A879904FD2FE4B2D90C89FDA84E1285F",
          "display": "Mcgovern,Astrid Santiago"
        },
        "encounter": {
          "reference": "Encounter/A879904FD2FE4B2D90C89FDA84E1285F.29019",
          "display": "Inferno,Initial"
        },
        "category": [
          {
            "coding": [
              {
                "system": "http://loinc.org",
                "code": "LA27976-2",
                "display": "Encounter-focused care team"
              }
            ]
          }
        ],
        "participant": [
          {
            "role": [
              {
                "coding": [
                  {
                    "system": "http://nucc.org/provider-taxonomy",
                    "code": "207QA0000X",
                    "display": "Family Medicine"
                  }
                ],
                "text": "Consulting Doctor"
              }
            ],
            "member": {
              "reference": "Practitioner/4F69EC72C5AA48988E5E73832887E634",
              "display": "Aguilar,Melva Delaine"
            }
          },
          {
            "role": [
              {
                "text": "Consulting Doctor"
              }
            ],
            "member": {
              "reference": "Practitioner/D8A9F3EADBE041688ADD843BBD98CAB0",
              "display": "O'Reilly,Rose"
            }
          },
          {
            "role": [
              {
                "coding": [
                  {
                    "system": "http://nucc.org/provider-taxonomy",
                    "code": "208D00000X",
                    "display": "General Practice"
                  }
                ],
                "text": "Admitting Doctor"
              }
            ],
            "member": {
              "reference": "Practitioner/DF2821C049CC47E6A37C6B796DF4CF1D",
              "display": "Godziszewski,Janet Kris"
            }
          },
          {
            "role": [
              {
                "coding": [
                  {
                    "system": "http://nucc.org/provider-taxonomy",
                    "code": "208D00000X",
                    "display": "General Practice"
                  }
                ],
                "text": "Attending Doctor"
              }
            ],
            "member": {
              "reference": "Practitioner/DF2821C049CC47E6A37C6B796DF4CF1D",
              "display": "Godziszewski,Janet Kris"
            }
          }
        ],
        "text": {
          "status": "generated",
          "div": "<div xmlns=\"http://www.w3.org/1999/xhtml\"><b>CareTeam</b><br /><b>Patient</b>:Mcgovern,Astrid Santiago<br /><b>Status</b>:active<br /><b>Encounter</b>:Inferno,Initial<br /><b>Category</b>:<b>System</b>:http://loinc.org <b>Code</b>:LA27976-2 <b>Display</b>:Encounter-focused care team<br /><b>Role</b>:<b>System</b>:http://nucc.org/provider-taxonomy <b>Code</b>:207QA0000X <b>Display</b>:Family Medicine <b>Text</b>:Consulting Doctor<br /><b>CareTeam Member</b>:Aguilar,Melva Delaine<br /><b>Role</b>:<b>Text</b>:Consulting Doctor<br /><b>CareTeam Member</b>:O'Reilly,Rose<br /><b>Role</b>:<b>System</b>:http://nucc.org/provider-taxonomy <b>Code</b>:208D00000X <b>Display</b>:General Practice <b>Text</b>:Admitting Doctor<br /><b>CareTeam Member</b>:Godziszewski,Janet Kris<br /><b>Role</b>:<b>System</b>:http://nucc.org/provider-taxonomy <b>Code</b>:208D00000X <b>Display</b>:General Practice <b>Text</b>:Attending Doctor<br /><b>CareTeam Member</b>:Godziszewski,Janet Kris<br /><br /></div>"
        }
      }
    }
  ],
  "link": [
    {
      "relation": "self",
      "url": "https://fhir-myrecord-sc.stagingcerner.com/r4/3f2aca24-87f3-4eac-a6d7-1f75247e6b43/CareTeam?patient=A879904FD2FE4B2D90C89FDA84E1285F&status=active"
    }
  ]
}

**Comment by PBKarthik** [comment]
Hi @yunwwang 
What @IgLysk00  meant was Related person is contained in Careteam resource. **"Patient needs to have a Related Person in the Care Team"?** means  Patient for whom we are pulling the careteam response should have Related person data so that it is part it becomes part of  careteam response.
Below  is the example of a patient Elson,Carmine-CareTeam Theresia for whom Rick stalone is the related person

**Comment by PBKarthik** [comment]
"resourceType": "Bundle",
    "id": "bfe0f2d9-75f9-4a0e-bcdf-20d33b402fb2",
    "type": "searchset",
    "timestamp": "2021-02-11T07:53:19-05:00",
    "entry": [
        {
            "fullUrl": "/ASCAPPNV0009/CareTeam/75C0BB942A5F475D8F931C2B1A3A04A4.LCC",
            "resource": {
                "resourceType": "CareTeam",
                "id": "75C0BB942A5F475D8F931C2B1A3A04A4.LCC",
                "meta": {
                    "lastUpdated": "2020-11-13T12:43:11-05:00"
                },
                "status": "active",
                "subject": {
                    "reference": "Patient/75C0BB942A5F475D8F931C2B1A3A04A4",
                    "display": "Elson,Carmine-CareTeam Theresia"
                },
                "category": [
                    {
                        "coding": [
                            {
                                "system": "http://loinc.org",
                                "code": "LA28865-6",
                                "display": "Longitudinal care-coordination focused care team"
                            }
                        ]
                    }
                ],
                "participant": [
                    {
                        "role": [
                            {
                                "text": "Additional Doctor"
                            }
                        ],
                        "member": {
                            "reference": "Practitioner/23827345320F4636BE9D71C7D43E320D",
                            "display": "Lansford,Mukesh Dianne"
                        }
                    },
                    {
                        "role": [
                            {
                                "text": "Healthcare Proxy"
                            }
                        ],
                        "member": {
                            "reference": "#199951"
                        }
                    },
                    {
                        "role": [
                            {
                                "text": "Healthcare Proxy"
                            }
                        ],
                        "member": {
                            "reference": "#199952"
                        }
                    },
                    {
                        "role": [
                            {
                                "text": "Patient Centered Medical Home"
                            }
                        ],
                        "member": {
                            "reference": "Organization/LTC.13"
                        }
                    },
                    {
                        "role": [
                            {
                                "text": "Specialist"
                            }
                        ],
                        "member": {
                            "reference": "Practitioner/64FB91107E72432583430C3717ECF486",
                            "display": "Wullkotte,Joyce Anne-Marie"
                        }
                    },
                    {
                        "role": [
                            {
                                "text": "Patient Centered Medical Home"
                            }
                        ],
                        "member": {
                            "reference": "Organization/LTC.9"
                        }
                    },
                    {
                        "role": [
                            {
                                "text": "Patient Centered Medical Home"
                            }
                        ],
                        "member": {
                            "reference": "Organization/STF.147201"
                        }
                    },
                    {
                        "role": [
                            {
                                "text": "Primary Physician"
                            }
                        ],
                        "member": {
                            "reference": "Practitioner/7F29DBC899314F51A6C50389A206B441",
                            "display": "Pete,Anne"
                        }
                    },
                    {
                        "role": [
                            {
                                "text": "HC Proxy - Primary"
                            }
                        ],
                        "member": {
                            "reference": "Practitioner/8AD7EBE8678D4F5896FD148F1A421582",
                            "display": "Killilea,Lisa-Diane"
                        }
                    },
                    {
                        "role": [
                            {
                                "text": "HC Proxy - Alternate"
                            }
                        ],
                        "member": {
                            "reference": "Practitioner/E6478199F04B4055B23399E8DFD500CC",
                            "display": "Derry,Olson"
                        }
                    },
                    {
                        "role": [
                            {
                                "text": "Additional Doctor"
                            }
                        ],
                        "member": {
                            "reference": "Practitioner/D2E8E4EDA7E443F6B104B5DD452D15AD",
                            "display": "Parker,Peter"
                        }
                    }
                ],
                "contained": [
                    {
                        "resourceType": "RelatedPerson",
                        "id": "199951",
                        "patient": {
                            "reference": "Patient/75C0BB942A5F475D8F931C2B1A3A04A4",
                            "display": "Elson,Carmine-CareTeam Theresia"
                        },
                        "relationship": [
                            {
                                "text": "Oth"
                            }
                        ],
                        "name": [
                            {
                                "use": "official",
                                "text": "Stalone,Rick",
                                "family": "Stalone",
                                "given": [
                                    "Rick"
                                ]
                            }
                        ]
                    },
                    {
                        "resourceType": "RelatedPerson",
                        "id": "199952",
                        "patient": {
                            "reference": "Patient/75C0BB942A5F475D8F931C2B1A3A04A4",
                            "display": "Elson,Carmine-CareTeam Theresia"
                        },
                        "relationship": [
                            {
                                "text": "Oth"
                            }
                        ],
                        "name": [
                            {
                                "use": "official",
                                "text": "Stalone,Bobbie",
                                "family": "Stalone",
                                "given": [
                                    "Bobbie"
                                ]
                            }
                        ]
                    }
                ],
                "text": {
                    "status": "generated",
                    "div": "<div xmlns=\"http://www.w3.org/1999/xhtml\"><b>CareTeam</b><br /><b>Patient</b>:Elson,Carmine-CareTeam Theresia<br /><b>Status</b>:active<br /><b>Category</b>:<b>System</b>:http://loinc.org <b>Code</b>:LA28865-6 <b>Display</b>:Longitudinal care-coordination focused care team<br /><b>Role</b>:<b>Text</b>:Additional Doctor<br /><b>CareTeam Member</b>:Lansford,Mukesh Dianne<br /><b>Role</b>:<b>Text</b>:Healthcare Proxy<br /><b>CareTeam Member</b>:Stalone,Rick<br /><b>Role</b>:<b>Text</b>:Healthcare Proxy<br /><b>CareTeam Member</b>:Stalone,Bobbie<br /><b>Role</b>:<b>Text</b>:Patient Centered Medical Home<br /><b>Role</b>:<b>Text</b>:Specialist<br /><b>CareTeam Member</b>:Wullkotte,Joyce Anne-Marie<br /><b>Role</b>:<b>Text</b>:Patient Centered Medical Home<br /><b>Role</b>:<b>Text</b>:Patient Centered Medical Home<br /><b>Role</b>:<b>Text</b>:Primary Physician<br /><b>CareTeam Member</b>:Pete,Anne<br /><b>Role</b>:<b>Text</b>:HC Proxy - Primary<br /><b>CareTeam Member</b>:Killilea,Lisa-Diane<br /><b>Role</b>:<b>Text</b>:HC Proxy - Alternate<br /><b>CareTeam Member</b>:Derry,Olson<br /><b>Role</b>:<b>Text</b>:Additional Doctor<br /><b>CareTeam Member</b>:Parker,Peter<br /><br /></div>"
                }
            }
        },
        {
            "fullUrl": "/ASCAPPNV0009/CareTeam/75C0BB942A5F475D8F931C2B1A3A04A4.ENC.86261",
            "resource": {
                "resourceType": "CareTeam",
                "id": "75C0BB942A5F475D8F931C2B1A3A04A4.ENC.86261",
                "meta": {
                    "lastUpdated": "2020-10-18T14:03:01-04:00"
                },
                "status": "active",
                "subject": {
                    "reference": "Patient/75C0BB942A5F475D8F931C2B1A3A04A4",
                    "display": "Elson,Carmine-CareTeam Theresia"
                },
                "encounter": {
                    "reference": "Encounter/75C0BB942A5F475D8F931C2B1A3A04A4.86261",
                    "display": "City General,Initial"
                },
                "category": [
                    {
                        "coding": [
                            {
                                "system": "http://loinc.org",
                                "code": "LA27976-2",
                                "display": "Encounter-focused care team"
                            }
                        ]
                    }
                ],
                "participant": [
                    {
                        "role": [
                            {
                                "text": "Attending Doctor"
                            }
                        ],
                        "member": {
                            "reference": "Practitioner/25374FA9A0424F4E90F81998B78F2633",
                            "display": "Rekart,John"
                        }
                    },
                    {
                        "role": [
                            {
                                "text": "Admitting Doctor"
                            }
                        ],
                        "member": {
                            "reference": "Practitioner/26B05B67B59B4468A8FA6A86D5BD62DD",
                            "display": "Banks,Mike"
                        }
                    },
                    {
                        "role": [
                            {
                                "text": "Referring Doctor"
                            }
                        ],
                        "member": {
                            "reference": "Practitioner/294848B98770448D98464785C6C4915A",
                            "display": "Howler,Catherine"
                        }
                    },
                    {
                        "role": [
                            {
                                "text": "Other Care Giver"
                            }
                        ],
                        "member": {
                            "reference": "Practitioner/3936BDD379B944ACAC79E688186F43AC",
                            "display": "Lemus,Renie"
                        }
                    },
                    {
                        "role": [
                            {
                                "text": "Consulting Doctor"
                            }
                        ],
                        "member": {
                            "reference": "Practitioner/6B68FE0327C847A4AE6D539BC299D1FA",
                            "display": "Lilley,Cheryl"
                        }
                    },
                    {
                        "role": [
                            {
                                "text": "Other Care Giver"
                            }
                        ],
                        "member": {
                            "reference": "Practitioner/6BE0A52C7C2943E0B50C376EF3EF41DA",
                            "display": "Smith,Adam"
                        }
                    },
                    {
                        "role": [
                            {
                                "text": "Consulting Doctor"
                            }
                        ],
                        "member": {
                            "reference": "Practitioner/B7036AFC535F4170975DE6B25CB9DD83",
                            "display": "Tribble,Isaac Kelvin"
                        }
                    },
                    {
                        "role": [
                            {
                                "text": "Other Care Giver"
                            }
                        ],
                        "member": {
                            "reference": "Practitioner/E876F858F18A47E685E00D9798C2C9CA",
                            "display": "Jones,Gerald J"
                        }
                    }
                ],
                "text": {
                    "status": "generated",
                    "div": "<div xmlns=\"http://www.w3.org/1999/xhtml\"><b>CareTeam</b><br /><b>Patient</b>:Elson,Carmine-CareTeam Theresia<br /><b>Status</b>:active<br /><b>Encounter</b>:City General,Initial<br /><b>Category</b>:<b>System</b>:http://loinc.org <b>Code</b>:LA27976-2 <b>Display</b>:Encounter-focused care team<br /><b>Role</b>:<b>Text</b>:Attending Doctor<br /><b>CareTeam Member</b>:Rekart,John<br /><b>Role</b>:<b>Text</b>:Admitting Doctor<br /><b>CareTeam Member</b>:Banks,Mike<br /><b>Role</b>:<b>Text</b>:Referring Doctor<br /><b>CareTeam Member</b>:Howler,Catherine<br /><b>Role</b>:<b>Text</b>:Other Care Giver<br /><b>CareTeam Member</b>:Lemus,Renie<br /><b>Role</b>:<b>Text</b>:Consulting Doctor<br /><b>CareTeam Member</b>:Lilley,Cheryl<br /><b>Role</b>:<b>Text</b>:Other Care Giver<br /><b>CareTeam Member</b>:Smith,Adam<br /><b>Role</b>:<b>Text</b>:Consulting Doctor<br /><b>CareTeam Member</b>:Tribble,Isaac Kelvin<br /><b>Role</b>:<b>Text</b>:Other Care Giver<br /><b>CareTeam Member</b>:Jones,Gerald J<br /><br /></div>"
                }
            }
        },
        {
            "fullUrl": "/ASCAPPNV0009/CareTeam/75C0BB942A5F475D8F931C2B1A3A04A4.ENC.82260",
            "resource": {
                "resourceType": "CareTeam",
                "id": "75C0BB942A5F475D8F931C2B1A3A04A4.ENC.82260",
                "meta": {
                    "lastUpdated": "2020-11-13T12:54:54-05:00"
                },
                "status": "inactive",
                "subject": {
                    "reference": "Patient/75C0BB942A5F475D8F931C2B1A3A04A4",
                    "display": "Elson,Carmine-CareTeam Theresia"
                },
                "encounter": {
                    "reference": "Encounter/75C0BB942A5F475D8F931C2B1A3A04A4.82260",
                    "display": "City General,Initial"
                },
                "category": [
                    {
                        "coding": [
                            {
                                "system": "http://loinc.org",
                                "code": "LA27976-2",
                                "display": "Encounter-focused care team"
                            }
                        ]
                    }
                ],
                "participant": [
                    {
                        "role": [
                            {
                                "text": "Consulting Doctor"
                            }
                        ],
                        "member": {
                            "reference": "Practitioner/93FE7033EE474AB896666A97380EF926",
                            "display": "Manuel,Douglas"
                        }
                    },
                    {
                        "role": [
                            {
                                "text": "Referring Doctor"
                            }
                        ],
                        "member": {
                            "reference": "Practitioner/97126E2AA3EC4C8F811DBDD62F7143E0",
                            "display": "Blunt,James"
                        }
                    },
                    {
                        "role": [
                            {
                                "text": "Admitting Doctor"
                            }
                        ],
                        "member": {
                            "reference": "Practitioner/9901E1D193344695B366F25A495589D0",
                            "display": "Barclay,Joseph"
                        }
                    },
                    {
                        "role": [
                            {
                                "coding": [
                                    {
                                        "system": "http://nucc.org/provider-taxonomy",
                                        "code": "208D00000X",
                                        "display": "General Practice"
                                    }
                                ],
                                "text": "Attending Doctor"
                            }
                        ],
                        "member": {
                            "reference": "Practitioner/9AA4FD7148C54C1D9D9E0627F5BA54EC",
                            "display": "Wix,Cassandra"
                        }
                    },
                    {
                        "role": [
                            {
                                "text": "Other Care Giver"
                            }
                        ],
                        "member": {
                            "reference": "Practitioner/C6270C6D8DFD4C24807FE77388638558",
                            "display": "Ford,Harlen"
                        }
                    }
                ],
                "text": {
                    "status": "generated",
                    "div": "<div xmlns=\"http://www.w3.org/1999/xhtml\"><b>CareTeam</b><br /><b>Patient</b>:Elson,Carmine-CareTeam Theresia<br /><b>Status</b>:inactive<br /><b>Encounter</b>:City General,Initial<br /><b>Category</b>:<b>System</b>:http://loinc.org <b>Code</b>:LA27976-2 <b>Display</b>:Encounter-focused care team<br /><b>Role</b>:<b>Text</b>:Consulting Doctor<br /><b>CareTeam Member</b>:Manuel,Douglas<br /><b>Role</b>:<b>Text</b>:Referring Doctor<br /><b>CareTeam Member</b>:Blunt,James<br /><b>Role</b>:<b>Text</b>:Admitting Doctor<br /><b>CareTeam Member</b>:Barclay,Joseph<br /><b>Role</b>:<b>System</b>:http://nucc.org/provider-taxonomy <b>Code</b>:208D00000X <b>Display</b>:General Practice <b>Text</b>:Attending Doctor<br /><b>CareTeam Member</b>:Wix,Cassandra<br /><b>Role</b>:<b>Text</b>:Other Care Giver<br /><b>CareTeam Member</b>:Ford,Harlen<br /><br /></div>"
                }
            }
        }
    ],
    "link": [
        {
            "relation": "self",
            "url": "/ASCAPPNV0009/CareTeam?patient=75C0BB942A5F475D8F931C2B1A3A04A4&_format=json"
        }
    ]
}

**Comment by yunwwang** [comment]
Thanks @PBKarthik. This is fixed in #238
