### ISSUE TITLE
Support for IE 11 in EHR Launch Test (FI-1156)

### ISSUE THREAD

**Issue by dougpratt** [onc-healthit/inferno-program#235]
_**Is your feature request related to a problem? Please describe it.**
Describe the problem you are trying to solve._

Our EHR requires Internet Explorer 11. When we run the INFERNO test for EHR Launch, INFERNO fails with a message that it does not support Internet Explorer (see attachment 1). When we click on OK, and then click on the Run Tests button, nothing happens (see attachment 2). I asked about this during the monthly call (Feb 10 @1 PM EST), and Rob Scanlon asked me to log this request.

![Inferno-1](https://user-images.githubusercontent.com/27502666/107796136-848e4300-6d27-11eb-9393-62cd6610258c.jpg)
![Inferno-2](https://user-images.githubusercontent.com/27502666/107796148-88ba6080-6d27-11eb-88c8-9c6c923bff20.jpg)

_**Describe the solution you'd like to see implemented**_

Allow EHR Launch from IE 11. 

The retirement date announced by Microsoft is the same as Windows 10 retirement, which is 10/24/2025. See https://docs.microsoft.com/en-us/lifecycle/faq/internet-explorer-microsoft-edge and https://docs.microsoft.com/en-us/lifecycle/products/windows-10-home-and-pro.

_**Describe alternatives you've considered**
Describe any alternative solutions or features you have considered._
We have considered support for additional browsers, but will be certifying our EHR before supporting additional browsers.

**Comment by arscan** [comment]
Thanks for letting us know about this.  We have no grounds to disallow usage of IE11 for the app launch, so we need to make sure that you can execute the launch process parts of those tests within the browser of your choosing.  Is it possible for you to use another browser to get Inferno into the state where it is expecting the launch, then only use IE11 for the EHR launch part, then switch back to the non-IE11 browser?  The following steps describe that process:

1) In a browser other than IE 11 (preferably chrome or firefox), initiate the EHR launch test sequence.  This essentially will put Inferno in a state where it is waiting for the EHR to start the app launch process.  You'll be presented with this popup:
![Screen Shot 2021-02-15 at 4 35 22 PM](https://user-images.githubusercontent.com/412901/107995069-f70f5500-6fab-11eb-8638-8fc4d2bbaa08.png)
2) From within the EHR, launch Inferno at that launch URI.  Click through the 'Inferno does not support IE...' alert box, and you should see the following:
![Capture (1)](https://user-images.githubusercontent.com/412901/107996709-08a62c00-6faf-11eb-9052-40752eeb73d9.PNG)
3) Click on the 'Continue' button, which seems to work for me in IE 11.  That should then redirect you back to the URL presented above the Continue button within the EHR.  At some point, your system should redirect back to Inferno (you may have to click on the 'IE not supported' popup again).  And hopefully it will get far enough to get Inferno to continue running the tests.
4) At this point, switch back to the browser you originally started the test with (Chrome or Firefox), and refresh.  It should show the test results.  You may need to wait a few seconds.

Could you let me know if you are able to do the above? Or is does something block you from doing that?

**Comment by dougpratt** [comment]
Thanks for the suggestion. I will have our engineers try this out and let you know. - Doug

**Comment by dougpratt** [comment]
Hi Rob,
Our engineers gave this a try with some success, but there is one problem remaining that can hopefully be overcome rather easily: INFERNO cannot be launched in the iframe that we launch because the browser refuses to render the content. Internet Explorer displays the error “Content cannot be displayed in a frame.” We believe that this is due to INFERNO sending X-Frame-Options = SAMEORIGIN in the response headers, which prevents webpage to be loaded in an iframe. Can you remove SAMEORIGIN from the header? I think that will get us there. Thanks, Doug.
![SameOrigin](https://user-images.githubusercontent.com/27502666/109359464-8988e180-7853-11eb-8154-152cfbd09aef.jpg)

**Comment by dougpratt** [comment]
Thank you Rob. It looks like work is already in progress - do you anticipate that this will be available with the next release?

**Comment by arscan** [comment]
I can't say for certain, because the team needs to review the proposed update.  But I expect that it will be ok, and we will include it in our next release, which should be in the first half of next week.

**Comment by arscan** [comment]
@dougpratt -- The fix for the X-Frame-Options is in v.1.50, which we released yesterday.  Thanks for pointing this one out to us.

**Comment by dougpratt** [comment]
Thank you, Rob! We'll give it a try.

Doug

**Comment by dougpratt** [comment]
Hi Rob
We tested INFERNO 1.5.0 in IE 11, and it still did not work. Please see the attached picture. Were the changes included in this release? Thanks, Doug
![Annotation 2021-03-25 155214](https://user-images.githubusercontent.com/27502666/112536276-a09fee00-8d83-11eb-8b66-d5a7dc2a2478.jpg)

**Comment by arscan** [comment]
We didn't fix the rendering problems in IE11 yet, and haven't removed that alert box.  I hope we can look at that soon, but since you can work around that issue (albeit in a not very user-friendly way), we have prioritized other updates instead.

What we did fix in this release is the `X-Frame-Option` issue you described up here: https://github.com/onc-healthit/inferno-program/issues/235#issuecomment-786914929. That was something we put a high priority on because it prevented you from passing the EHR launch tests when using Inferno outside of a Docker environment.

Have you had a chance to try that out yet?  And if I misunderstood the effectiveness of the IE11 workaround, let me know, and I'll be sure we prioritize that near the top.

**Comment by dougpratt** [comment]
Thanks Rob. Our developer ran into an issue on our side that prevented him from completing the test. He's going to retest as soon as he gets that resolved. -Doug

**Comment by IgLysk00** [comment]
Retested again using Inferno 1.6.1. The workaround works, but definitely cannot be used during the certification - several pop up screens with information that IE is not supported. If possible, please provide ETA when this issue will be addressed. Thanks.

**Comment by arscan** [comment]
@IgLysk00 We have a PR open for this (#335), and I would expect it to be available on our next release.  If you are able, feel free to try out that branch on your side to confirm, in case there is something different about your useragent than the versions of IE11 I was able to test with.
