### ISSUE TITLE
Inferno Single Patient API MedicationRequest test USCMR-10 failed with contained Medication resource.

### ISSUE THREAD

**Issue by IgLysk00** [onc-healthit/inferno-program#237]
Inferno  Standalone Patient App, MedicationRequest Tests, USCMR-10 test failed with the error message :MedicationRequest.medication.ofType(Reference): Unable to find matching profile. 
The MedicationRequest resource includes a contained Medication Resource (see the output below).

**Your environment**
* Edition of inferno (Community or Program): Program
* Version of inferno: 1.4.1
* Which browser and version(s) is the bug present on?: Chrome

**Steps to reproduce**
Tell us how to reproduce this issue.
Use a test patient with medications and run Single Patient API MedicationRequest tests. Medicaction should be a contained resource within the MedicationRequest resource. According to HL7 FHIR® US Core Implementation Guide STU3 Release 3.1.1 guide, https://www.hl7.org/fhir/us/core/MedicationRequest-uscore-mo2.html MedicationRequest can include a reference to a contained Medication resource. 

Include:
* The selected test suite: Single Patient API
* The URL of the FHIR server being tested: https://fhir-myrecord-sc.stagingcerner.com/r4/3f2aca24-87f3-4eac-a6d7-1f75247e6b43 (not a public URL)
* The Test ID, if it's a problem with a specific test.: USCMR-10

**Actual behavior**
Tell us what happens instead. Include screenshots if possible.

{
  "resourceType": "MedicationRequest",
  "id": "4B01EB2C42D349209991AB814DC0DB5F.10001",
  "meta": {
    "lastUpdated": "2020-11-16T18:22:35-05:00"
  },
  "medicationReference": {
    "reference": "#10001"
  },
  "contained": [
    {
      "resourceType": "Medication",
      "id": "10001",
      "code": {
        "coding": [
          {
            "system": "http://www.nlm.nih.gov/research/umls/rxnorm",
            "code": "208416",
            "display": "Sulfamethoxazole 400 MG / Trimethoprim 80 MG Oral Tablet [Bactrim]"
          },
          {
            "system": "http://www.nlm.nih.gov/research/umls/rxnorm",
            "code": "198334",
            "display": "Sulfamethoxazole 400 MG / Trimethoprim 80 MG Oral Tablet"
          }
        ],
        "text": "sulfamethoxazole-trimethoprim"
      }
    }
  ],
  "status": "active",
  "intent": "order",
  "reportedBoolean": false,
  "subject": {
    "reference": "Patient/4B01EB2C42D349209991AB814DC0DB5F",
    "display": "Matchett,Greta-baby Blake"
  },
  "encounter": {
    "reference": "Encounter/4B01EB2C42D349209991AB814DC0DB5F.108260",
    "display": "Inferno,Initial"
  },
  "authoredOn": "2020-11-16T18:22:33-05:00",
  "requester": {
    "reference": "Practitioner/40134EF110CA4C07988F544E90057844",
    "display": "Admin,Admin"
  },
  "dosageInstruction": [
    {
      "text": "sulfamethoxazole-trimethoprim  (Bactrim)  400 mg-80 mg  Tablet  Directions: 1 tablet  oral  daily  Continued By: Admin  Admin "
    }
  ],
  "text": {
    "status": "generated",
    "div": "<div xmlns=\"http://www.w3.org/1999/xhtml\"><b>MedicationRequest</b><br /><b>Patient</b>:Matchett,Greta-baby Blake;<br /><b>Encounter</b>:Inferno,Initial;<br /><b>Status</b>:active;<br /><b>Intent</b>:order;<br /><b>Medication</b>:<br /><b>System</b>:http://www.nlm.nih.gov/research/umls/rxnorm <b>Code</b>:208416 <b>Display</b>:Sulfamethoxazole 400 MG / Trimethoprim 80 MG Oral Tablet [Bactrim] <b>Text</b>:sulfamethoxazole-trimethoprim;<br /><b>System</b>:http://www.nlm.nih.gov/research/umls/rxnorm <b>Code</b>:198334 <b>Display</b>:Sulfamethoxazole 400 MG / Trimethoprim 80 MG Oral Tablet <b>Text</b>:sulfamethoxazole-trimethoprim;<br /><b>Authored On</b>:2020-11-16T18:22:33-05:00;<br /><b>Dosage Instructions</b>:sulfamethoxazole-trimethoprim  (Bactrim)  400 mg-80 mg  Tablet  Directions: 1 tablet  oral  daily  Continued By: Admin  Admin ;<br /></div>"
  }
}

**Comment by IgLysk00** [comment]
MedicationRequest.medication.ofType(Reference): Unable to find matching profile

**Comment by yunwwang** [comment]
Thanks for raise the issue. This is fixed in Inferno fhir_validator https://github.com/inferno-community/fhir-validator-wrapper/pull/30

**Comment by yunwwang** [comment]
PR for updating fhir-validator-service in inferno-program to the latest #246

**Comment by arscan** [comment]
@IgLysk00 This should be fixed in v1.5.0 that we released yesterday.  Let us know if it still gives you problems!  Thanks again for the report.

**Comment by yunwwang** [comment]
Issue fixed in Inferno 1.5.0

**Comment by emily-alt** [comment]
@arscan @yunwwang This issue has re-emerged. Exact same data, same error re: "Unable to find matching profile for..."

Please advise on if we should open a new ticket or use this older one. 

Thanks
Emily Keller

**Comment by yunwwang** [comment]
@emily-alt I tested the MedicationRequest mentioned in the first note (from @IgLysk00). The resource passed validation without any error. Could you post the one you used? Thanks

**Comment by emily-alt** [comment]
@yunwwang Hmmm. We "officially" run Inferno bi-weekly. The last run was 1/26 and USCMR-10 failed for the sample shown above and for all the other MedReq resources for the test patient. My follow-up game is just slow this week. 

Sending another JSON sample below that failed on 1/26 but FWIW this passes today on INF. ¯\_(ツ)_/¯ 

{
  "resourceType": "MedicationRequest",
  "id": "A879904FD2FE4B2D90C89FDA84E1285F.17864",
  "meta": {
    "lastUpdated": "2021-05-19T12:43:34-04:00"
  },
  "medicationReference": {
    "reference": "#17864"
  },
  "contained": [
    {
      "resourceType": "Medication",
      "id": "17864",
      "code": {
        "coding": [
          {
            "system": "http://www.nlm.nih.gov/research/umls/rxnorm",
            "code": "213469",
            "display": "celecoxib 200 MG Oral Capsule [Celebrex]"
          },
          {
            "system": "http://www.nlm.nih.gov/research/umls/rxnorm",
            "code": "205323",
            "display": "celecoxib 200 MG Oral Capsule"
          }
        ],
        "text": "celecoxib"
      }
    }
  ],
  "status": "active",
  "intent": "plan",
  "reportedBoolean": false,
  "subject": {
    "reference": "Patient/A879904FD2FE4B2D90C89FDA84E1285F",
    "display": "Mcgovern,Astrid-Anna Santiago"
  },
  "encounter": {
    "reference": "Encounter/A879904FD2FE4B2D90C89FDA84E1285F.29019",
    "display": "Inferno,Initial"
  },
  "authoredOn": "2021-05-19T12:43:33-04:00",
  "requester": {
    "reference": "Practitioner/40134EF110CA4C07988F544E90057844"
  },
  "dosageInstruction": [
    {
      "text": "celecoxib  (CeleBREX)  200 mg  Capsule  Directions: 1 capsule  oral  daily  Continued By: Admin  Admin "
    }
  ],
  "text": {
    "status": "generated",
    "div": "<div xmlns=\"http://www.w3.org/1999/xhtml\"><b>MedicationRequest</b><br /><b>Patient</b>:Mcgovern,Astrid-Anna Santiago;<br /><b>Encounter</b>:Inferno,Initial;<br /><b>Status</b>:active;<br /><b>Intent</b>:plan;<br /><b>Medication</b>:<br /><b>System</b>:http://www.nlm.nih.gov/research/umls/rxnorm <b>Code</b>:213469 <b>Display</b>:celecoxib 200 MG Oral Capsule [Celebrex] <b>Text</b>:celecoxib;<br /><b>System</b>:http://www.nlm.nih.gov/research/umls/rxnorm <b>Code</b>:205323 <b>Display</b>:celecoxib 200 MG Oral Capsule <b>Text</b>:celecoxib;<br /><b>Authored On</b>:2021-05-19T12:43:33-04:00;<br /><b>Dosage Instructions</b>:celecoxib  (CeleBREX)  200 mg  Capsule  Directions: 1 capsule  oral  daily  Continued By: Admin  Admin ;<br /></div>"
  }
}
