### ISSUE TITLE
504 Gateway timeout

### ISSUE THREAD

**Issue by lakshmib08** [onc-healthit/inferno-program#240]
Thank you for reporting a possible bug in Inferno! Please fill in as much of the template below as you can.

**Subject of the issue**
Describe your issue here.

Hello,
When running Single Patient API test (whether I point to Inferno Reference Server or my FHIR server), after executing all the tests, the results are not displayed. I am getting a 504 Gateway Time-out
nginx/1.19.6
Thanks. (I am not sure if this is the right place to report the error).
**Your environment**
* Edition of inferno (Community or Program):
* Version of inferno:
* Which browser and version(s) is the bug present on?:

**Steps to reproduce**
Tell us how to reproduce this issue.

Include:

* The selected test suite
* The URL of the FHIR server being tested
* The Test ID, if it's a problem with a specific test.
* Any required configuration options (client ID, client secret, etc.)
* Anything else needed to make the issue occur.

**Expected behavior**
Tell us what should happen.

**Actual behavior**
Tell us what happens instead. Include screenshots if possible.

**Comment by arscan** [comment]
Thanks for the report!  Is this on a newer installation, or have you been using it for testing for some time?  We've noticed an issue where performance slows significantly when the local database size gets too big.  But if this is a new install, then that wouldn't be the case.

**Comment by lakshmib08** [comment]
I was running against the one in the cloud. This is not a local install.
Thanks.

**Comment by arscan** [comment]
Thanks @lakshmib08 -- we cleared out the old test data and the page renders quickly now after you have run the full tests.  We will be addressing this particular issue in a future version.
