### ISSUE TITLE
Not able to pass the test of "Capability Statement".

### ISSUE THREAD

**Issue by ParvindTrivial** [onc-healthit/inferno-program#254]
After getting the response from URL "/metadata", the tool is throwing the following error:

Invalid CapabilityStatement: CapabilityStatement.rest[0].operation[6].definition: Canonical URLs must be absolute URLs if they are not fragment references (OperationDefinition/-is-expunge).

Please help me with this.

**Comment by yunwwang** [comment]
This is an error reported from FHIR validator. Can you provide a sample of failed CapabilityStatement?

**Comment by arscan** [comment]
Are you running HAPI?  We noticed this issue on our own reference server running HAPI 5.0, and ended up removing the operations from the capability statement because we didn't actually want to advertise that we support these operations.  It seems like it is fixed in HAPI 5.3 (or at least, the most recent version of HAPI's public server doesn't report this issue).

There is a chance that the HL7 FHIR Validator is wrong, but on the surface this seems like a reasonable error to report.  We could dig in further if you send us your CapabilityStatement though.

**Comment by ParvindTrivial** [comment]
> This is an error reported from FHIR validator. Can you provide a sample of failed CapabilityStatement?

Thanks for the response. I can't provide the whole "CapabilityStatement" resource here but I can provide the portion at which I am getting the error.

"operation": [
    {
      "name": "mark-all-resources-for-reindexing",
      "definition": "OperationDefinition/-is-expunge"
    }
  ]

**Comment by ParvindTrivial** [comment]
> Are you running HAPI? We noticed this issue on our own reference server running HAPI 5.0, and ended up removing the operations from the capability statement because we didn't actually want to advertise that we support these operations. It seems like it is fixed in HAPI 5.3 (or at least, the most recent version of HAPI's public server doesn't report this issue).
> 
> There is a chance that the HL7 FHIR Validator is wrong, but on the surface this seems like a reasonable error to report. We could dig in further if you send us your CapabilityStatement though.

Thanks for your response. No I am not using HAPI. I've provided the portion of "CapabilityStatement" at which I am getting the error, in the comments. I am also planning to remove the "operation" section from my "CapabilityStatement" resource.

**Comment by yunwwang** [comment]
According to FHIR spec, CapabilityStatement.operation.definition has type of canonical. The canonical type has to be a full url unless the target is contained.
http://hl7.org/fhir/capabilitystatement.html

**Comment by arscan** [comment]
> The canonical type has to be a full url unless the target is contained.

@yunwwang -- Where exactly does it state that canonical urls must be absolute and not relative?  I wanted to paste the exact language in here for completeness and then close the ticket, but I am having trouble finding that specific requirement.

**Comment by yunwwang** [comment]
Here is a related FHIR JIRA ticket: https://jira.hl7.org/browse/FHIR-27789

**Comment by yunwwang** [comment]
Hello @ParvindTrivial I will close this ticket if you agree with our response.
