### ISSUE TITLE
Device: USCID-01: Search by patient expecting same results for patient=Patient/ID and patient=ID and they appear to be the same

### ISSUE THREAD

**Issue by bh021790** [onc-healthit/inferno-program#255]
**Subject:** First Device Test Failing but it appears to be correct
**Description:**

- USCID-01: Server returns valid results for Device search by patient. Message: Expected search by Patient/ID to have the same results as search by ID

From what I can tell, the two responses are identical. Is there an issue with this test?

**Your environment**
* Edition of inferno (Community or Program): ONC Program
* Version of inferno: 1.5.0
* Which browser and version(s) is the bug present on?: Chrome

**Steps to reproduce**
Enter open-endpoint, patient ID and device type code - Execute tests

Include:

* The selected test suite
* The URL of the FHIR server being tested: https://fhir-open.cerner.com/r4/ec2458f2-1e24-41c8-b71b-0e701af7583d
* The Test ID, if it's a problem with a specific test:
* Patient ID: 12644044
* Device Type Code: 269236419
* Any required configuration options (client ID, client secret, etc.): NA
* Anything else needed to make the issue occur.

**Expected behavior**
The test should pass because both requests result in identical responses:
GET   200   https://fhir-open.cerner.com/r4/ec2458f2-1e24-41c8-b71b-0e701af7583d/Device?patient=12644044

GET   200   https://fhir-open.cerner.com/r4/ec2458f2-1e24-41c8-b71b-0e701af7583d/Device?patient=Patient/12644044

**Actual behavior**
Very first tests fails and it notes that it expects the same response from both.

**Comment by yunwwang** [comment]
@bh021790 Thank you for raise this to our attention. Would you mind to either paste or email the results from both searches since we could not access that endpoint.

**Comment by bh021790** [comment]
First:
 GET   200   https://fhir-open.cerner.com/r4/ec2458f2-1e24-41c8-b71b-0e701af7583d/Device?patient=12644044
Request
Headers
User-Agent: Ruby FHIR Client
Accept-Charset: utf-8
Accept: application/fhir+json
Authorization: Bearer
Response
Headers
content-type: application/fhir+json; charset=utf-8
content-length: 1027
connection: keep-alive
date: Mon, 15 Mar 2021 15:43:15 GMT
cache-control: no-cache
etag: W/"f65bd17a4728c4a29d9be0e3271dace0"
server-response-time: 1010.3235260000001
vary: Origin
x-request-id: 31d54577-79d1-4626-aaa5-8980e49d82f1
x-runtime: 1.010240
x-cache: Miss from cloudfront
via: 1.1 62b5a67033f9ddeb513aca6c5afc317f.cloudfront.net (CloudFront)
x-amz-cf-pop: IAD66-C2
x-amz-cf-id: BYtpZ6Q3Fd8HcEvCOrjtoTPUC2tQLGaPXvizqgNvkiK3ZGc90ZHyPA==
Body
{
  "resourceType": "Bundle",
  "id": "34d3a535-7a27-4c26-b449-1fdf52a6ad1d",
  "type": "searchset",
  "total": 1,
  "link": [
    {
      "relation": "self",
      "url": "https://fhir-open.cerner.com/r4/ec2458f2-1e24-41c8-b71b-0e701af7583d/Device?patient=12644044"
    }
  ],
  "entry": [
    {
      "fullUrl": "https://fhir-open.cerner.com/r4/ec2458f2-1e24-41c8-b71b-0e701af7583d/Device/31445894",
      "resource": {
        "resourceType": "Device",
        "id": "31445894",
        "meta": {
          "versionId": "1",
          "lastUpdated": "2018-08-22T23:08:01Z"
        },
        "text": {
          "status": "generated",
          "div": "<div xmlns=\"http://www.w3.org/1999/xhtml\"><p><b>Device</b></p><p><b>Status</b>: Active</p><p><b>Type</b>: Pacemaker</p><p><b>Patient</b>: MXDTEST, RADIOLOGY B</p></div>"
        },
        "status": "active",
        "deviceName": [
          {
            "name": "Pacemaker",
            "type": "user-friendly-name"
          }
        ],
        "type": {
          "text": "Pacemaker"
        },
        "patient": {
          "reference": "Patient/12644044",
          "display": "MXDTEST, RADIOLOGY B"
        }
      }
    }
  ]
}

Second:
GET   200   https://fhir-open.cerner.com/r4/ec2458f2-1e24-41c8-b71b-0e701af7583d/Device?patient=Patient/12644044
Request
Headers
User-Agent: Ruby FHIR Client
Accept-Charset: utf-8
Accept: application/fhir+json
Authorization: Bearer
Response
Headers
content-type: application/fhir+json; charset=utf-8
content-length: 1037
connection: keep-alive
date: Mon, 15 Mar 2021 15:43:16 GMT
cache-control: no-cache
etag: W/"7a0ace6ce8f9db8958e956d4047afdeb"
server-response-time: 763.188807
vary: Origin
x-request-id: 9569f266-27ae-4525-b387-f05a71238ced
x-runtime: 0.763078
x-cache: Miss from cloudfront
via: 1.1 8a39851a9fdfa096ba6f1e618ed88f40.cloudfront.net (CloudFront)
x-amz-cf-pop: IAD66-C2
x-amz-cf-id: fatKxjjJ4pJLJrol2zhoNDl5E3KXFwoo3kbvnWwNA5K-WaXVu9MjnQ==
Body
{
  "resourceType": "Bundle",
  "id": "8b22c6b1-969f-4a13-b1ef-a4b8a5423832",
  "type": "searchset",
  "total": 1,
  "link": [
    {
      "relation": "self",
      "url": "https://fhir-open.cerner.com/r4/ec2458f2-1e24-41c8-b71b-0e701af7583d/Device?patient=Patient%2F12644044"
    }
  ],
  "entry": [
    {
      "fullUrl": "https://fhir-open.cerner.com/r4/ec2458f2-1e24-41c8-b71b-0e701af7583d/Device/31445894",
      "resource": {
        "resourceType": "Device",
        "id": "31445894",
        "meta": {
          "versionId": "1",
          "lastUpdated": "2018-08-22T23:08:01Z"
        },
        "text": {
          "status": "generated",
          "div": "<div xmlns=\"http://www.w3.org/1999/xhtml\"><p><b>Device</b></p><p><b>Status</b>: Active</p><p><b>Type</b>: Pacemaker</p><p><b>Patient</b>: MXDTEST, RADIOLOGY B</p></div>"
        },
        "status": "active",
        "deviceName": [
          {
            "name": "Pacemaker",
            "type": "user-friendly-name"
          }
        ],
        "type": {
          "text": "Pacemaker"
        },
        "patient": {
          "reference": "Patient/12644044",
          "display": "MXDTEST, RADIOLOGY B"
        }
      }
    }
  ]
}

**Comment by arscan** [comment]
We found a bug in how we are handling this check when you fill in the Device Type Code as an input.  One thing to keep in mind is that you only need to use that input if your patient has more than just implantable devices.  We have it in there so we don't inappropriately validate a non-implantable device against the implantable device profile.  I think in the case of this patient, you could juse leave that type blank, which will avoid this bug.

![Screen Shot 2021-03-16 at 5 29 34 PM](https://user-images.githubusercontent.com/412901/111382562-85dfc200-867d-11eb-9779-36cb0dddf7d1.png)

But regardless, we need to fix this.  I think we can get to it quickly, and are planning on another release soon.

Thanks for the report!

**Comment by yunwwang** [comment]
Working ticket: FI-1181

**Comment by yunwwang** [comment]
Hello @bh021790 , this issue has been fixed in Inferno Program release v1.6.0.

**Comment by bh021790** [comment]
thanks @yunwwang - I'll go ahead and close this out!
