### ISSUE TITLE
Patient tests erroring due to duplicate Patient.contact.name.id

### ISSUE THREAD

**Issue by bh021790** [onc-healthit/inferno-program#256]
Thank you for reporting a possible bug in Inferno! Please fill in as much of the template below as you can.

Many Patient tests are erroring because a Patient.contact is repeated.
I'm not sure why Inferno is testing for duplicate Patient.contacts. There are plenty of workflows where one given related person may be added to the patient's record using different relationships: guardian, authorized representative and mother could all be associated to a given contact. 

Error:
Patient.contact[3].name: Duplicate id value 'CI-12742541-0' * Patient.contact[2].name: Duplicate id value 'CI-12743963-0'

Tests Impacted:
USCP-01: Server returns valid results for Patient search by _id.
USCP-03: Server returns valid results for Patient search by name.
USCP-04: Server returns valid results for Patient search by birthdate+name.
USCP-12: Patient resources returned from previous search conform to the US Core Patient Profile.

**Your environment**
* Edition of inferno (Community or Program): ONC
* Version of inferno: 1.5.0
* Which browser and version(s) is the bug present on?: Chrome
* Saved Test Link: https://inferno.healthit.gov/inferno/jMo5mVouyrA/ 

**Steps to reproduce**
Tell us how to reproduce this issue.
**REQUEST:**
GET   200   https://fhir-open.cerner.com/r4/ec2458f2-1e24-41c8-b71b-0e701af7583d/Patient?_id=12744437

**RESPONSE:**
Request
Headers
User-Agent: Ruby FHIR Client
Accept-Charset: utf-8
Accept: application/fhir+json
Authorization: Bearer
Response
Headers
content-type: application/fhir+json; charset=utf-8
transfer-encoding: chunked
connection: keep-alive
date: Tue, 16 Mar 2021 18:40:04 GMT
cache-control: no-cache
etag: W/"8d9b943a3dfd7427e5a6394d3894b6f6"
server-response-time: 1056.192052
vary: Origin
x-request-id: e6c4157a-5d29-494e-8579-1ff0f4edfc1d
x-runtime: 1.056078
x-cache: Miss from cloudfront
via: 1.1 9724c58d66570574c4bf5a2b0c0f3038.cloudfront.net (CloudFront)
x-amz-cf-pop: IAD79-C3
x-amz-cf-id: 9z9_-LoMZ-Z8aDb4x6UoCPafvc8WjJ8wa9vZAL_AQM7JquVIHaANlw==
Body
{
  "resourceType": "Bundle",
  "id": "cda2d440-72ab-4b7a-b781-23503b494a22",
  "type": "searchset",
  "total": 1,
  "link": [
    {
      "relation": "self",
      "url": "https://fhir-open.cerner.com/r4/ec2458f2-1e24-41c8-b71b-0e701af7583d/Patient?_id=12744437"
    }
  ],
  "entry": [
    {
      "fullUrl": "https://fhir-open.cerner.com/r4/ec2458f2-1e24-41c8-b71b-0e701af7583d/Patient/12744437",
      "resource": {
        "resourceType": "Patient",
        "id": "12744437",
        "meta": {
          "versionId": "13",
          "lastUpdated": "2021-03-03T05:55:41.000Z"
        },
        "text": {
          "status": "extensions",
          "div": "<div xmlns=\"http://www.w3.org/1999/xhtml\"><p><b>Patient</b></p><p><b>Name</b>: KRAUS, DAVID</p><p><b>Status</b>: Active</p><p><b>DOB</b>: Jan  2, 1970</p><p><b>Birth Sex</b>: Male</p><p><b>Administrative Gender</b>: Male</p><p><b>Marital Status</b>: Single</p></div>"
        },
        "extension": [
          {
            "valueCode": "M",
            "url": "http://hl7.org/fhir/us/core/StructureDefinition/us-core-birthsex"
          },
          {
            "extension": [
              {
                "valueCoding": {
                  "system": "urn:oid:2.16.840.1.113883.6.238",
                  "code": "2054-5",
                  "display": "Black or African American",
                  "userSelected": false
                },
                "url": "ombCategory"
              },
              {
                "valueString": "Black or African American",
                "url": "text"
              }
            ],
            "url": "http://hl7.org/fhir/us/core/StructureDefinition/us-core-race"
          },
          {
            "extension": [
              {
                "valueCoding": {
                  "system": "urn:oid:2.16.840.1.113883.6.238",
                  "code": "2186-5",
                  "display": "Not Hispanic or Latino",
                  "userSelected": false
                },
                "url": "ombCategory"
              },
              {
                "valueString": "Not Hispanic, Latino, or Spanish Origin",
                "url": "text"
              }
            ],
            "url": "http://hl7.org/fhir/us/core/StructureDefinition/us-core-ethnicity"
          }
        ],
        "identifier": [
          {
            "id": "CI-490172192-0",
            "use": "usual",
            "type": {
              "coding": [
                {
                  "system": "https://fhir.cerner.com/ec2458f2-1e24-41c8-b71b-0e701af7583d/codeSet/4",
                  "code": "2",
                  "display": "Community Medical Record Number",
                  "userSelected": true
                },
                {
                  "system": "http://terminology.hl7.org/CodeSystem/v2-0203",
                  "code": "MR",
                  "display": "Medical record number",
                  "userSelected": false
                }
              ],
              "text": "Community Medical Record Number"
            },
            "system": "urn:oid:2.16.840.1.113883.3.787.0.0",
            "value": "9002630555"
          },
          {
            "id": "CI-490098947-1",
            "use": "usual",
            "type": {
              "coding": [
                {
                  "system": "https://fhir.cerner.com/ec2458f2-1e24-41c8-b71b-0e701af7583d/codeSet/4",
                  "code": "10",
                  "display": "MRN",
                  "userSelected": true
                },
                {
                  "system": "http://terminology.hl7.org/CodeSystem/v2-0203",
                  "code": "MR",
                  "display": "Medical record number",
                  "userSelected": false
                }
              ],
              "text": "MRN"
            },
            "system": "urn:oid:2.16.840.1.113883.6.1000",
            "value": "490098947",
            "period": {
              "start": "2020-09-28T10:34:27.000Z"
            }
          },
          {
            "id": "CI-490098946-3",
            "use": "usual",
            "type": {
              "coding": [
                {
                  "system": "https://fhir.cerner.com/ec2458f2-1e24-41c8-b71b-0e701af7583d/codeSet/4",
                  "code": "22",
                  "display": "Military Id",
                  "userSelected": true
                }
              ],
              "text": "Military Id"
            },
            "system": "urn:oid:2.16.840.1.113883.3.42.10001.100001.12",
            "value": "10050007806",
            "period": {
              "start": "2020-09-28T10:34:27.000Z"
            }
          },
          {
            "id": "CI-490160317-4",
            "use": "usual",
            "type": {
              "coding": [
                {
                  "system": "https://fhir.cerner.com/ec2458f2-1e24-41c8-b71b-0e701af7583d/codeSet/4",
                  "code": "2553236785",
                  "display": "MIllennium Person Identifier",
                  "userSelected": true
                }
              ],
              "text": "MIllennium Person Identifier"
            },
            "_system": {
              "extension": [
                {
                  "valueCode": "unknown",
                  "url": "http://hl7.org/fhir/StructureDefinition/data-absent-reason"
                }
              ]
            },
            "value": "15230",
            "period": {
              "start": "2020-12-18T19:15:38.000Z"
            }
          }
        ],
        "active": true,
        "name": [
          {
            "id": "CI-12744437-0",
            "use": "official",
            "text": "KRAUS, DAVID",
            "family": "KRAUS",
            "given": [
              "DAVID"
            ],
            "period": {
              "start": "2020-09-28T10:34:27.000Z"
            }
          },
          {
            "id": "CI-490098966-0",
            "use": "usual",
            "text": "INFERNO, JEFF",
            "family": "INFERNO",
            "given": [
              "JEFF"
            ],
            "period": {
              "start": "2020-09-28T10:34:27.000Z"
            }
          },
          {
            "id": "CI-490211977-1",
            "use": "old",
            "text": "INFERNO, TESTONE",
            "family": "INFERNO",
            "given": [
              "TESTONE"
            ],
            "period": {
              "start": "2020-09-28T10:34:27.000Z",
              "end": "2021-03-03T05:55:41.000Z"
            }
          }
        ],
        "telecom": [
          {
            "id": "CI-PH-29829142-0",
            "system": "phone",
            "value": "5739234567",
            "rank": 1,
            "period": {
              "start": "2020-09-28T10:34:27.000Z"
            }
          },
          {
            "id": "CI-PH-29829144-1",
            "system": "phone",
            "value": "8162345123",
            "use": "work",
            "rank": 1,
            "period": {
              "start": "2020-09-28T10:34:27.000Z"
            }
          },
          {
            "id": "CI-PH-29829146-2",
            "system": "phone",
            "value": "9132221324",
            "use": "home",
            "rank": 1,
            "period": {
              "start": "2020-09-28T10:34:27.000Z"
            }
          },
          {
            "id": "CI-PH-29829145-3",
            "system": "phone",
            "value": "2125555554",
            "use": "mobile",
            "rank": 1,
            "period": {
              "start": "2020-09-28T10:34:27.000Z"
            }
          }
        ],
        "gender": "male",
        "birthDate": "1970-01-02",
        "deceasedBoolean": false,
        "address": [
          {
            "id": "CI-24333243-0",
            "use": "home",
            "text": "9876 Main St\nKANSAS CITY, MO 64113\nUS",
            "line": [
              "9876 Main St"
            ],
            "city": "KANSAS CITY",
            "state": "MO",
            "postalCode": "64113",
            "country": "US",
            "period": {
              "start": "2021-01-20T18:18:17.000Z"
            }
          }
        ],
        "maritalStatus": {
          "coding": [
            {
              "system": "https://fhir.cerner.com/ec2458f2-1e24-41c8-b71b-0e701af7583d/codeSet/38",
              "code": "309239",
              "display": "Single",
              "userSelected": true
            },
            {
              "system": "http://terminology.hl7.org/CodeSystem/v3-MaritalStatus",
              "code": "U",
              "display": "unmarried",
              "userSelected": false
            }
          ],
          "text": "Single"
        },
        "contact": [
          {
            "relationship": [
              {
                "coding": [
                  {
                    "system": "https://fhir.cerner.com/ec2458f2-1e24-41c8-b71b-0e701af7583d/codeSet/351",
                    "code": "1152",
                    "display": "Emergency Contact",
                    "userSelected": true
                  },
                  {
                    "system": "http://terminology.hl7.org/CodeSystem/v2-0131",
                    "code": "C",
                    "display": "Emergency Contact",
                    "userSelected": false
                  }
                ],
                "text": "Emergency Contact"
              }
            ],
            "name": {
              "id": "CI-12742541-0",
              "use": "official",
              "text": "HARRIS, DANA",
              "family": "HARRIS",
              "given": [
                "DANA"
              ]
            },
            "telecom": [
              {
                "system": "phone",
                "value": "2125555553",
                "use": "home",
                "rank": 1,
                "period": {
                  "start": "2020-04-27T16:36:47.000Z"
                }
              },
              {
                "system": "email",
                "value": "dharris@gmail.com",
                "use": "home",
                "rank": 1,
                "period": {
                  "start": "2020-07-28T14:53:41.000Z"
                }
              }
            ],
            "address": {
              "use": "home",
              "text": "\nUS",
              "country": "US",
              "period": {
                "start": "2020-09-09T22:24:03.000Z"
              }
            },
            "period": {
              "start": "2020-09-28T10:34:27.000Z"
            }
          },
          {
            "relationship": [
              {
                "coding": [
                  {
                    "system": "https://fhir.cerner.com/ec2458f2-1e24-41c8-b71b-0e701af7583d/codeSet/351",
                    "code": "1153",
                    "display": "Family Member",
                    "userSelected": true
                  }
                ],
                "text": "Family Member"
              }
            ],
            "name": {
              "id": "CI-12743963-0",
              "use": "official",
              "text": "HARRIS, DANA",
              "family": "HARRIS",
              "given": [
                "DANA"
              ],
              "period": {
                "start": "2020-09-16T21:28:50.000Z"
              }
            },
            "telecom": [
              {
                "system": "phone",
                "value": "2125555553",
                "use": "home",
                "rank": 1,
                "period": {
                  "start": "2020-04-27T16:36:47.000Z"
                }
              },
              {
                "system": "email",
                "value": "dharris@gmail.com",
                "use": "home",
                "rank": 1,
                "period": {
                  "start": "2020-07-28T14:53:41.000Z"
                }
              }
            ],
            "address": {
              "use": "home",
              "text": "\nUS",
              "country": "US",
              "period": {
                "start": "2020-09-09T22:24:03.000Z"
              }
            },
            "period": {
              "start": "2020-09-28T10:34:27.000Z"
            }
          },
          {
            "relationship": [
              {
                "coding": [
                  {
                    "system": "https://fhir.cerner.com/ec2458f2-1e24-41c8-b71b-0e701af7583d/codeSet/351",
                    "code": "1156",
                    "display": "Guardian",
                    "userSelected": true
                  }
                ],
                "text": "Guardian"
              }
            ],
            "name": {
              "id": "CI-12743963-0",
              "use": "official",
              "text": "HARRIS, DANA",
              "family": "HARRIS",
              "given": [
                "DANA"
              ],
              "period": {
                "start": "2020-09-16T21:28:50.000Z"
              }
            },
            "telecom": [
              {
                "system": "phone",
                "value": "2125555553",
                "use": "home",
                "rank": 1,
                "period": {
                  "start": "2020-04-27T16:36:47.000Z"
                }
              },
              {
                "system": "email",
                "value": "dharris@gmail.com",
                "use": "home",
                "rank": 1,
                "period": {
                  "start": "2020-07-28T14:53:41.000Z"
                }
              }
            ],
            "address": {
              "use": "home",
              "text": "\nUS",
              "country": "US",
              "period": {
                "start": "2020-09-09T22:24:03.000Z"
              }
            },
            "period": {
              "start": "2020-09-28T10:34:27.000Z"
            }
          },
          {
            "relationship": [
              {
                "coding": [
                  {
                    "system": "https://fhir.cerner.com/ec2458f2-1e24-41c8-b71b-0e701af7583d/codeSet/351",
                    "code": "1156",
                    "display": "Guardian",
                    "userSelected": true
                  }
                ],
                "text": "Guardian"
              }
            ],
            "name": {
              "id": "CI-12742541-0",
              "use": "official",
              "text": "HARRIS, DANA",
              "family": "HARRIS",
              "given": [
                "DANA"
              ]
            },
            "telecom": [
              {
                "system": "phone",
                "value": "2125555553",
                "use": "home",
                "rank": 1,
                "period": {
                  "start": "2020-04-27T16:36:47.000Z"
                }
              },
              {
                "system": "email",
                "value": "dharris@gmail.com",
                "use": "home",
                "rank": 1,
                "period": {
                  "start": "2020-07-28T14:53:41.000Z"
                }
              }
            ],
            "address": {
              "use": "home",
              "text": "\nUS",
              "country": "US",
              "period": {
                "start": "2020-09-09T22:24:03.000Z"
              }
            },
            "period": {
              "start": "2020-09-28T10:34:27.000Z",
              "end": "2020-09-16T21:28:50.000Z"
            }
          }
        ],
        "communication": [
          {
            "language": {
              "coding": [
                {
                  "system": "https://fhir.cerner.com/ec2458f2-1e24-41c8-b71b-0e701af7583d/codeSet/36",
                  "code": "151",
                  "display": "English",
                  "userSelected": true
                },
                {
                  "system": "urn:ietf:bcp:47",
                  "code": "en",
                  "display": "English",
                  "userSelected": false
                }
              ],
              "text": "English"
            },
            "preferred": true
          }
        ],
        "generalPractitioner": [
          {
            "id": "CI-490099001-0",
            "reference": "Practitioner/11938004",
            "display": "Bradford, MD, Michael Cerner"
          }
        ]
      }
    }
  ]
}

Include:

* The selected test suite
* The URL of the FHIR server being tested: https://fhir-open.cerner.com/r4/ec2458f2-1e24-41c8-b71b-0e701af7583d
* The Test ID, if it's a problem with a specific test.: see earlier in my post
* Any required configuration options (client ID, client secret, etc.)
* Anything else needed to make the issue occur.

**Expected behavior**
I would expect a failure when the same contact appears numerous times with different relationships

**Actual behavior**
Failures on numerous tests
![image](https://user-images.githubusercontent.com/20422272/111365239-3d65db80-8660-11eb-926a-bbc6b071b9b0.png)
![image](https://user-images.githubusercontent.com/20422272/111365339-5ff7f480-8660-11eb-9703-806b3c1ee165.png)
![image](https://user-images.githubusercontent.com/20422272/111365364-671f0280-8660-11eb-878e-a4df531bf455.png)
![image](https://user-images.githubusercontent.com/20422272/111365397-700fd400-8660-11eb-8c17-97b6b848fafc.png)
![image](https://user-images.githubusercontent.com/20422272/111365434-7c942c80-8660-11eb-90e8-bfc8cfbcada4.png)

**Comment by arscan** [comment]
This is an error coming from the HL7 FHIR Validator, which means that the resource is violating some core aspect of the FHIR specification.  Unless, of course, there is a bug in the HL7 FHIR Validator, which we can figure out.

In looking at the error, seems to me that you may be misusing the `id` on `Patient.contact.name` element.  `Element.id` is somewhat of a special field that is available on every element in FHIR and is used so that an element within a resource can refer to another element in the same resource.  Note that it is not defined in [HumanName](http://www.hl7.org/fhir/datatypes.html#humanname), but instead on its parent [Element](http://www.hl7.org/fhir/element.html#definition).  

See this section for the source of that requirement that is causing the failure: http://www.hl7.org/fhir/element.html#id

> The id SHALL be unique within a given resource

What is the purpose of the string you are saving in there?  Would it be more appropriate to put in an extension?

I think that is what is causing the issue, but also note that for a single contact you can list multiple relationship types.  So, list DANA HARRIS as the only contact, and fill in 2 relationships (Guardian & Family Member).  But maybe there is a reason why you want to consider them different contacts?

**Comment by bh021790** [comment]
THANK YOU! I will investigate further and see if we need to change our implementation.
