### ISSUE TITLE
Add option to skip authorization for Bulk API tests

### ISSUE THREAD

**Issue by dougpratt** [onc-healthit/inferno-program#257]
**Is your feature request related to a problem? Please describe it.**
Describe the problem you are trying to solve.
_Is there a way to disable authorization requirement for bulk-api testing using Inferno? Our authorization server is not yet ready with full support for the backend authorization specification and our bulk-api export APIs are ready for testing. We’d like to run Inferno tests to identify any gap in our implementation. Any suggestion on how we can achieve this?_
**Describe the solution you'd like to see implemented**
Things you can put in this section include (but aren't limited to):
* A description of the solution.
* Details of the technical implementation, if you've thought about it.
* Any caveats/tradeoffs of the proposed solution.
If there is currently a way to do this with the existing code, a description of how would suffice. If necessary, we could edit the code locally with some guidance from you, but our preference would be if it were build into a forthcoming release as a user selectable option.
**Describe alternatives you've considered**
Describe any alternative solutions or features you have considered.
We're open to altering the code locally, but would need some guidance.

**Comment by okeefm** [comment]
Hello Doug,

If you're looking to test your bulk data server against Inferno's tests without authorization, the easiest way to do it is to use Inferno Community's Bulk Data Test suites. If you navigate to https://inferno.healthit.gov/community, select `Bulk Data Tests (via BDT)`, and input your bulk data server URL, you can run the bulk data tests. 

You can run any of the tests listed individually, and disable authorization by unchecking `Requires Authorization` in the dialog box that comes up when you click "Run" on any of the tests.

Let us know if this works for you!

Thank you,
Michael O'Keefe

**Comment by yunwwang** [comment]
Question was answered
