### ISSUE TITLE
Inferno is giving "504 Gateway Time-out" error.

### ISSUE THREAD

**Issue by ParvindTrivial** [onc-healthit/inferno-program#266]
After completing the tests of "Single Patient Api", Inferno is giving "504 Gateway Time-out" error instead of results. Please help me with this.

**Comment by arscan** [comment]
Hi @ParvindTrivial -- you should be able to see the results now (though you will need to retest your system, sorry!).  This comes up from time to time, but we have a fix coming in our next release that addresses it.  So hopefully this is the last time we see this happen.

Thanks for the report!  Let me know if you are still having issues.

**Comment by ParvindTrivial** [comment]
Thanks @arscan for the quick response. For now, I am getting the results.
