### ISSUE TITLE
Terminology server used by Inferno needs to be updated to support SNOMED CT USA/2021-03-01 version. (FI-1258)

### ISSUE THREAD

**Issue by Rinkal-jain** [onc-healthit/inferno-program#267]
Terminology server used by Inferno needs to be updated to support SNOMED CT USA/2021-03-01 version.
Inferno tool reports USCE-13 Encounter type errors because some codes such as 453701000124103 are not found in USCoreEncounterType value set loaded in http://tx.fhir.org/r4.

**Comment by arscan** [comment]
Hi @Rinkal-jain -- thanks for pointing this out.  We are looking at it on our side and will provide updates in this GitHub issue.

**Comment by Rinkal-jain** [comment]
hi @arscan -- any updates related to this?

**Comment by arscan** [comment]
We are in the process of upgrading our terminology loading system to allow loading newer versions of terminologies, so this should be available in the next version.

**Comment by yunwwang** [comment]
PR: #337

**Comment by yunwwang** [comment]
@Rinkal-jain Inferno v1.8.0 is released. Could you verify that this issue has been addressed in this release?
