### ISSUE TITLE
Large white space between tests USCDR-12 and USCDR-13

### ISSUE THREAD

**Issue by IgLysk00** [onc-healthit/inferno-program#268]
Thank you for reporting a possible bug in Inferno! Please fill in as much of the template below as you can.

**Subject of the issue**
Describe your issue here.
When Inferno Single Patient API tests run a big gap is created between tests USCDR-12 and USCDR-13.

**Your environment**
* Edition of inferno (Community or Program): Program
* Version of inferno: 1.5.0
* Which browser and version(s) is the bug present on?: Chrome

**Steps to reproduce**
Tell us how to reproduce this issue.
Run Program Edition Single Patient API test for DocumentReference. Test patient needs to have the following Clinical Notes:
Consultation Note
Discharge Summary Note
History and Physical Note
Procedures Note
Progress Note
CCDA document

Include:

* The selected test suite
* The URL of the FHIR server being tested
* The Test ID, if it's a problem with a specific test.
* Any required configuration options (client ID, client secret, etc.)
* Anything else needed to make the issue occur.
* 
![image](https://user-images.githubusercontent.com/73243391/113458526-8ea3f800-93e0-11eb-9685-dcb143d62d51.png)
![image](https://user-images.githubusercontent.com/73243391/113458534-9794c980-93e0-11eb-9950-31a936ce36b2.png)
![image](https://user-images.githubusercontent.com/73243391/113458470-57354b80-93e0-11eb-9bc8-70de5fb9a7e7.png)

See position of the vertical scroll bar to understand the issue

**Expected behavior**
Tell us what should happen.
Big gap between the test runs should not be created

**Actual behavior**
Tell us what happens instead. Include screenshots if possible.
See screenshots attached above

**Comment by yunwwang** [comment]
@IgLysk00 Do you still experience the same issue with the latest release v1.6.2?

**Comment by IgLysk00** [comment]
We have not used release v1.6.2 yet. This was not an issue with release v1.6.1.

**Comment by arscan** [comment]
I'm going to close this if it appears to have been resolved in v1.6.1.  Please feel free to open another ticket if you come across it again.  I have a feeling that it might be dependent on error messages you receive (somehow some error messages are being intrepretted as markdown when the intent is to just display a string), but it is difficult to debug without being able to reproduce it locally.  Thanks!
