### ISSUE TITLE
Getting Gateway Timeout

### ISSUE THREAD

**Issue by lakshmib08** [onc-healthit/inferno-program#271]
We are getting a 504 - Getting Timeout for the past couple of days using the Program edition.
I've tried several times, but I have not been able to successfully execute the tests and view the results.
Thanks.

**Comment by okeefm** [comment]
Hello @lakshmib08. Thanks for reporting this issue; we're looking into it now. We will let you know when we have a resolution for this issue.

Thanks,
Michael

**Comment by lakshmib08** [comment]
Thank you. This is for the Single Patient API test set.

**Comment by lakshmib08** [comment]
I apologize...I will close this issue because it looks like there is most likely an error on our side. Thank you for looking into this.
