### ISSUE TITLE
Encounter Tests - No Encounter references found from the prior searches

### ISSUE THREAD

**Issue by lakshmib08** [onc-healthit/inferno-program#273]
Thank you for reporting a possible bug in Inferno! Please fill in as much of the template below as you can.

**Encounter Tests - No Encounter references found from the prior searches**

My MedicationRequest tests are all successful and have a Reference to an Encounter.
    "encounter": {
          "reference": "Encounter/0f67abaa-3120-47d2-8442-3948897b6cd4"
        },

**Your environment**
* Edition of inferno - Program
* Version of inferno:
* Which browser and version(s) is the bug present on?:Chrome

**Steps to reproduce**
Run the Single Patient Inferno tests. The Encounter tests are not executed

Encounter Tests - 0/4 Required Tests Passed - Hide Details
Verify support for the server capabilities required by the US Core Encounter Profile.
Test Results
Inputs
About
 USCE-01: Server returns correct Encounter resource from the Encounter read interaction results...
No Encounter references found from the prior searches

 USCE-02: Encounter resources returned from previous search conform to the US Core Encounter Profile. results...
No Encounter resources appear to be available.

 USCE-03: All must support elements are provided in the Encounter resources returned. results...
No Encounter resources appear to be available.

 USCE-04: Every reference within Encounter resources can be read. results...
No Encounter resources appear to be available.

**Comment by lakshmib08** [comment]
I tested it again to confirm to make sure I am able to do an Encounter read with the resource ID as mentioned above and I am getting a successful result. Just that Inferno tool is unable to find the resource and execute the tests.

**Comment by arscan** [comment]
We should make this more more clear in the tool.  We need to see an Encounter reference that is in a spot where the reference type is specifically "US Core Encounter" and not just "Encounter".  That way we know we can expect a US Core Encounter profiled resource.   MedicationRequest.encounter is typed to "Encounter", not "US Core Encounter".  I understand this is confusing.

You can find US Core Encounter references in [US Core DiagnosticReport.encounter](http://hl7.org/fhir/us/core/STU3.1.1/StructureDefinition-us-core-diagnosticreport-note.html) and [US Core DocumentReference.context.encounter](http://hl7.org/fhir/us/core/STU3.1.1/StructureDefinition-us-core-documentreference.html).

**Comment by lakshmib08** [comment]
Thank you for clarifying. I will be closing this ticket.
