### ISSUE TITLE
BDGV-03 should be more accepting of content type

### ISSUE THREAD

**Issue by cooperthompson** [onc-healthit/inferno-program#278]
Thank you for reporting a possible bug in Inferno! Please fill in as much of the template below as you can.

**Subject of the issue**
Describe your issue here.
BDGV-03 fails if the content type is application/fhir+ndjson;charset=utf-8.  I believe the explicit check Inferno is doing is for application/fhir+ndjson.  It seems like it should be fine if the server returns the additional charset=utf-8.

**Your environment**
* Edition of inferno (Community or Program): Program
* Version of inferno: 1.5.0
* Which browser and version(s) is the bug present on?: Chrome

**Steps to reproduce**
Tell us how to reproduce this issue.
Run Inferno on a server that returns application/fhir+ndjson;charset=utf-8 as the content type for Bulk FHIR checks.  Our server is internal for now, so I don't have an example URL for you to use to reproduce.  Sorry!
Include:

* The selected test suite:  BDGV-03
* The URL of the FHIR server being tested
* The Test ID, if it's a problem with a specific test.
* Any required configuration options (client ID, client secret, etc.)
* Anything else needed to make the issue occur.

**Expected behavior**
Tell us what should happen.
BDE-05 should pass as long as the header _includes_ application/fhir+ndjson.  Extra components of the header should be fine, as long as they are valid HTTP header components.

**Actual behavior**
Tell us what happens instead. Include screenshots if possible.
![image](https://user-images.githubusercontent.com/5863379/116722567-2d058800-a9a4-11eb-85a7-7b79221c349e.png)

**Comment by yunwwang** [comment]
That is a bug in our testing. We will fix it asap

**Comment by arscan** [comment]
This should have been fixed in v1.6.0 (#280).  Thanks for the report.
