### ISSUE TITLE
BDE-04 and BDE-05 - are these requirements on the client or server? (FI-1308)

### ISSUE THREAD

**Issue by cooperthompson** [onc-healthit/inferno-program#279]
Thank you for reporting a possible bug in Inferno! Please fill in as much of the template below as you can.

**Subject of the issue**
Describe your issue here.
BDE-04 and BDE-05 are checking that the server rejects an export request if invalid headers are sent.  The valid/required headers are listed here: http://hl7.org/fhir/uv/bulkdata/export/index.html#headers

Our interpretation was that those header requirements were imposed on the client.  It seems reasonable for a server to still process the request even if the client didn't provide the correct headers, and, since incorrect headers were provided, just use server-specified default behavior.

**Your environment**
* Edition of inferno (Community or Program):  Program
* Version of inferno: 1.5.0
* Which browser and version(s) is the bug present on?: Chrome

**Steps to reproduce**
Tell us how to reproduce this issue.
Run Bulk FHIR checks against a lenient server.  Our server will return 202 for BDE-04 and BDE-05 cases.

Include:

* The selected test suite
* The URL of the FHIR server being tested;  Internal server, our URL won't be useful for reproducing the issue.  Sorry!
* The Test ID, if it's a problem with a specific test.  BDE-04 and BDE-05
* Any required configuration options (client ID, client secret, etc.)
* Anything else needed to make the issue occur.

**Expected behavior**
Tell us what should happen.
I think these checks shouldn't apply to the server.  The spec is unclear whether the header requirements is on the client or server, but I think it makes more sense for them to be client requirements.

**Actual behavior**
Tell us what happens instead. Include screenshots if possible.
![image](https://user-images.githubusercontent.com/5863379/116723320-ff6d0e80-a9a4-11eb-9ef0-beaf30c55a53.png)

**Comment by cooperthompson** [comment]
Zulip topic on this issue: https://chat.fhir.org/#narrow/stream/179250-bulk-data/topic/Bulk.20Export.20Headers.20-.20required.20for.20servers.20or.20clients.3F

Based on the outcome of that, I'll submit a ballot comment on the May 21 ballot to be more clear about whatever we think is the right behavior.   The version under ballot review would still need SVAP, but would probably add weight to what we decide to do for the current version.

**Comment by yunwwang** [comment]
HL7 JIRA https://jira.hl7.org/browse/FHIR-32062
Approved for Bulk Data IG v2.0.0

**Comment by dabimahesh** [comment]
So will it not be mandatory check for BDE-04 and BDE-05?

Currently our FHIR server is sending 202 (Success) when the client set accept='application/fhir+xml' and prefer=return=representation for BDE-04 and BDE-05 respectively. Will this be acceptable after the new fix?

Thanks
Mahesh

**Comment by yunwwang** [comment]
BDE-04 and BDE-05 will be removed from Multi Patient test. So Inferno will not test server's response for client request with header value other than what specified in Bulk Data IG.
