### ISSUE TITLE
MIME types with parameters not recognized as valid Attachment.contentType codes

### ISSUE THREAD

**Issue by lcmaas** [onc-healthit/inferno-program#281]
valid MIME types that include valid parameters such as charset are not recognized for DocumentReference.content.attachment.contentType

* Edition of inferno (Community or Program): 1.5.0P

**Steps to reproduce**
1. Return a DocumentReference resource with DocumentReference.content.attachment.contentType = 'text/plain; charset=UTF-8' during execution of Single Patient API tests.
2. The resource fails USCDR-12 with the following error: DocumentReference.content.attachment.contentType with code 'text/plain; charset=UTF-8' is not in http://hl7.org/fhir/ValueSet/mimetypes

Or manually with rake:
$ run inferno bundle exec rake "terminology:check_code[text/plain; charset=UTF-8,urn:ietf:bcp:13,http://hl7.org/fhir/ValueSet/mimetypes]"
returns: urn:ietf:bcp:13|text/plain; charset=UTF-8 is not in http://hl7.org/fhir/ValueSet/mimetypes

**Expected behavior**
MIME types with valid parameters should pass.

From the US Core definition for [contentType](http://hl7.org/fhir/us/core/STU3.1.1/StructureDefinition-us-core-documentreference-definitions.html#DocumentReference.content.attachment.contentType) (which is also the R4 Attachment.contentType definition):

> Definition: Identifies the type of the data in the attachment and allows a method to be chosen to interpret or render the data. **Includes mime type parameters such as charset where appropriate.**

Note that the this is an infinitely large value set, including every combination of permitted parameter and possible value for every valid MIME type and subtype.

**Actual behavior**
test fails with message: DocumentReference.content.attachment.contentType with code 'text/plain; charset=UTF-8' is not in http://hl7.org/fhir/ValueSet/mimetypes

**Comment by yunwwang** [comment]
Hello @lcmaas, this issue is fixed in Inferno program release 1.6.1.
