### ISSUE TITLE
Hi Everyone, We have requirement to test against these guidelines "HL7 CARIN BB, DaVinci PDEX, PlanNet & Formulary guidelines" , Do you know how can i get the inferno community addition deployed on my local firewall inside docker to have validator up and running and test against these guidelines.

### ISSUE THREAD

**Issue by mahechilivery** [onc-healthit/inferno-program#286]
Thank you for reporting a possible bug in Inferno! Please fill in as much of the template below as you can.

**Subject of the issue**
Describe your issue here.

**Your environment**
* Edition of inferno (Community or Program):
* Version of inferno:
* Which browser and version(s) is the bug present on?:

**Steps to reproduce**
Tell us how to reproduce this issue.

Include:

* The selected test suite
* The URL of the FHIR server being tested
* The Test ID, if it's a problem with a specific test.
* Any required configuration options (client ID, client secret, etc.)
* Anything else needed to make the issue occur.

**Expected behavior**
Tell us what should happen.

**Actual behavior**
Tell us what happens instead. Include screenshots if possible.

**Comment by arscan** [comment]
I'm not sure if the requirements of these IGs are specifically covered in current inferno-community tests.  But instructions for standing up the community edition tests, including a copy of the hl7 validator for the tests to use, are here: https://github.com/onc-healthit/inferno#docker-installation

If you would like to just use the FHIR validator (which just validate resources and not APIs), you can use our web wrapper around the HL7 validator here: https://github.com/inferno-community/fhir-validator-app#running-the-fhir-validator-app-using-docker-compose
