### ISSUE TITLE
Encounter tests not running, even when Condition tests are returning Encounter references

### ISSUE THREAD

**Issue by samtregar** [onc-healthit/inferno-program#292]
**Subject of the issue**

I'm working on implementing the Encounter part of the Single Patient API tests but I can't figure out how to get them to run.  No matter what I've done I see:

> USCE-01: Server returns correct Encounter resource from the Encounter read interaction results...
> No Encounter references found from the prior searches

I've verified that my Condition tests are returning at least one Encounter reference.  Is there a particular other test that needs to return Encounters for this test to run?

**Your environment**
* Edition of inferno (Community or Program): Program
* Version of inferno: 2015 Edition Cures Update
* Which browser and version(s) is the bug present on?: Chrome Version 90.0.4430.212 (Official Build) (64-bit)

**Steps to reproduce**

Attempt to run Encounter Single Patient API tests, with only the Condition tests returning Encounter references.  

**Expected behavior**

I would expect that the Encounter tests would run if Encounter references were being returned in the Condition tests.

**Actual behavior**

No Encounter tests are run.

**Comment by Jammjammjamm** [comment]
Inferno is specifically looking for references to US Core Encounters. See the comments on these issues for more information:

https://github.com/onc-healthit/inferno-program/issues/273
https://github.com/onc-healthit/inferno-program/issues/153
