### ISSUE TITLE
terminology install

### ISSUE THREAD

**Issue by gjrom** [onc-healthit/inferno-program#295]
Hi, I'm working to install INFERNO 1.6.0.  The docker container and associated web interface is working.  When I attempt to install the terminology with the final command as per the instructions, i.e. "docker-compose -f terminology_compose.yml up" it appears to fail with a message that the db/config.yml files does not exist.  However when I check within the db dir it is there.  Below is an excerpt from the builder trying to run.  Any insight would be appreciated.

Thanks,
Greg

ubuntu@ip-10-0-10-183:~/INFERNO/inferno-program-1.6.0P$ sudo docker-compose -f terminology_compose.yml up &
[2] 17192
ubuntu@ip-10-0-10-183:~/INFERNO/inferno-program-1.6.0P$ WARNING: Found orphan containers (inferno-program-160p_inferno_1, inferno-program-160p_validator_service_1, inferno-program-160p_nginx_1) for this project. If you removed or renamed this service in your compose file, you can run this command with the --remove-orphans flag to clean it up.
Creating inferno-program-160p_terminology_builder_1 ... done
Attaching to inferno-program-160p_terminology_builder_1
terminology_builder_1  | UMLS Zip already exists; skipping UMLS download Rake task.
terminology_builder_1  | rake aborted!
terminology_builder_1  | Cannot load database configuration:
terminology_builder_1  | Could not load database configuration. No such file - ["db/config.yml"]
terminology_builder_1  | /usr/local/bundle/ruby/2.5.0/gems/railties-5.2.4.5/lib/rails/application/configuration.rb:185:in `database_configuration'
terminology_builder_1  | /usr/local/bundle/ruby/2.5.0/gems/standalone_migrations-6.0.0/lib/standalone_migrations/configurator.rb:24:in `load_configurations'
terminology_builder_1  | /usr/local/bundle/ruby/2.5.0/gems/standalone_migrations-6.0.0/lib/standalone_migrations/configurator.rb:30:in `environments_config'
terminology_builder_1  | /usr/local/bundle/ruby/2.5.0/gems/standalone_migrations-6.0.0/lib/standalone_migrations/tasks.rb:11:in `load_tasks'
terminology_builder_1  | /var/www/inferno/Rakefile:7:in `<top (required)>'
terminology_builder_1  | /usr/local/bundle/ruby/2.5.0/gems/rake-13.0.1/exe/rake:27:in `<top (required)>'
terminology_builder_1  | /usr/local/bundle/gems/bundler-2.2.17/lib/bundler/cli/exec.rb:63:in `load'
terminology_builder_1  | /usr/local/bundle/gems/bundler-2.2.17/lib/bundler/cli/exec.rb:63:in `kernel_load'
terminology_builder_1  | /usr/local/bundle/gems/bundler-2.2.17/lib/bundler/cli/exec.rb:28:in `run'
terminology_builder_1  | /usr/local/bundle/gems/bundler-2.2.17/lib/bundler/cli.rb:494:in `exec'
terminology_builder_1  | /usr/local/bundle/gems/bundler-2.2.17/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
terminology_builder_1  | /usr/local/bundle/gems/bundler-2.2.17/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
terminology_builder_1  | /usr/local/bundle/gems/bundler-2.2.17/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
terminology_builder_1  | /usr/local/bundle/gems/bundler-2.2.17/lib/bundler/cli.rb:30:in `dispatch'
terminology_builder_1  | /usr/local/bundle/gems/bundler-2.2.17/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
terminology_builder_1  | /usr/local/bundle/gems/bundler-2.2.17/lib/bundler/cli.rb:24:in `start'
terminology_builder_1  | /usr/local/bundle/gems/bundler-2.2.17/exe/bundle:49:in `block in <top (required)>'
terminology_builder_1  | /usr/local/bundle/gems/bundler-2.2.17/lib/bundler/friendly_errors.rb:130:in `with_friendly_errors'
terminology_builder_1  | /usr/local/bundle/gems/bundler-2.2.17/exe/bundle:37:in `<top (required)>'
terminology_builder_1  | /usr/local/bundle/bin/bundle:23:in `load'
terminology_builder_1  | /usr/local/bundle/bin/bundle:23:in `<main>'
terminology_builder_1  |
terminology_builder_1  | Caused by:
terminology_builder_1  | Could not load database configuration. No such file - ["db/config.yml"]
terminology_builder_1  | /usr/local/bundle/ruby/2.5.0/gems/railties-5.2.4.5/lib/rails/application/configuration.rb:185:in `database_configuration'
terminology_builder_1  | /usr/local/bundle/ruby/2.5.0/gems/standalone_migrations-6.0.0/lib/standalone_migrations/configurator.rb:24:in `load_configurations'
terminology_builder_1  | /usr/local/bundle/ruby/2.5.0/gems/standalone_migrations-6.0.0/lib/standalone_migrations/configurator.rb:30:in `environments_config'
terminology_builder_1  | /usr/local/bundle/ruby/2.5.0/gems/standalone_migrations-6.0.0/lib/standalone_migrations/tasks.rb:11:in `load_tasks'
terminology_builder_1  | /var/www/inferno/Rakefile:7:in `<top (required)>'
terminology_builder_1  | /usr/local/bundle/ruby/2.5.0/gems/rake-13.0.1/exe/rake:27:in `<top (required)>'
terminology_builder_1  | /usr/local/bundle/gems/bundler-2.2.17/lib/bundler/cli/exec.rb:63:in `load'
terminology_builder_1  | /usr/local/bundle/gems/bundler-2.2.17/lib/bundler/cli/exec.rb:63:in `kernel_load'
terminology_builder_1  | /usr/local/bundle/gems/bundler-2.2.17/lib/bundler/cli/exec.rb:28:in `run'
terminology_builder_1  | /usr/local/bundle/gems/bundler-2.2.17/lib/bundler/cli.rb:494:in `exec'
terminology_builder_1  | /usr/local/bundle/gems/bundler-2.2.17/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
terminology_builder_1  | /usr/local/bundle/gems/bundler-2.2.17/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
terminology_builder_1  | /usr/local/bundle/gems/bundler-2.2.17/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
terminology_builder_1  | /usr/local/bundle/gems/bundler-2.2.17/lib/bundler/cli.rb:30:in `dispatch'
terminology_builder_1  | /usr/local/bundle/gems/bundler-2.2.17/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
terminology_builder_1  | /usr/local/bundle/gems/bundler-2.2.17/lib/bundler/cli.rb:24:in `start'
terminology_builder_1  | /usr/local/bundle/gems/bundler-2.2.17/exe/bundle:49:in `block in <top (required)>'
terminology_builder_1  | /usr/local/bundle/gems/bundler-2.2.17/lib/bundler/friendly_errors.rb:130:in `with_friendly_errors'
terminology_builder_1  | /usr/local/bundle/gems/bundler-2.2.17/exe/bundle:37:in `<top (required)>'
terminology_builder_1  | /usr/local/bundle/bin/bundle:23:in `load'
terminology_builder_1  | /usr/local/bundle/bin/bundle:23:in `<main>'
terminology_builder_1  | (See full trace by running task with --trace)
inferno-program-160p_terminology_builder_1 exited with code 1

**Comment by danielberez** [comment]
I'm having the exact same issue.

**Comment by dkriebel** [comment]
I found this post right after posting my own. See post [here](https://github.com/onc-healthit/inferno/issues/569) for info.

The short answer is in your terminology_compose.yml file, add the following in the "volumes" section.
./db/config.yml:/var/www/inferno/db/config.yml

This allowed me to build the terminology.

**Comment by okeefm** [comment]
Hello, 

Yes, there is a fix for this, which we are in the process of reviewing in Pull Request #290. In the short term, you can either:

* checkout the `fix_terminology_docker` branch, which is the branch behind PR #290, and which is identical to inferno-program `v1.6.0` aside from the terminology build fixes.

* Copy the changes from that PR over to the corresponding files in your local Inferno Program directory.

We hope to release an Inferno Program `v1.6.1` shortly which will include this fix.

Thank you,
Michael
