### ISSUE TITLE
support for public clients using authorization flow with PKCE

### ISSUE THREAD

**Issue by sdikeman** [onc-healthit/inferno-program#297]
Would like to use Inferno to test an API for the CMS Final Rule.  The regulation suggests the use of an authorization flow with PKCE but I can't find a way to do that on the released version.  Wondering if someone has a solution?  Thanks

**Comment by yunwwang** [comment]
@sdikeman Inferno Program is designed for ONC (g)(10) certificate testing. Current rule is based on SMART App Launch v1.0.0 which does not specify any requirement about PKCE. The new version SMART App Launch v2.0.0 adds such requirement for public client
"All SMART apps SHOULD support Proof Key for Code Exchange (PKCE), and public client SMART apps SHALL support PKCE." (http://build.fhir.org/ig/HL7/smart-app-launch/index.html#considerations-for-pkce-support). Inferno will consider adding this feature to Inferno Community when moving to SMART App Launch v2.0.0
