### ISSUE TITLE
Unable to build terminology - 

### ISSUE THREAD

**Issue by dkriebel** [onc-healthit/inferno-program#299]
When upgrading to Program Edition version 1.6, I've been having issues building the terminology for this version. When running this command:

docker-compose -f terminology_compose.yml up

I get the following error, which then causes the process to abort:
terminology_builder_1  | Could not load database configuration. No such file - ["db/config.yml"]

This was confusing because the directory does exist, so I started looking in the config files to see if maybe there was a missing reference. After adding the following to the "volumes" section in terminology_compose.yml, I was able to successfully build the terminology.
- ./db/config.yml:/var/www/inferno/db/config.yml

**Your environment**
* Edition of inferno (Community or Program): Program
* Version of inferno: 1.6
* Which browser and version(s) is the bug present on?: Windows with Docker container

**Steps to reproduce**
Run the command:
docker-compose -f terminology_compose.yml up

While I was able to resolve this issue by changing the config I wanted to post this to make the issue known and assist anyone else who has run into this.

**Comment by okeefm** [comment]
Fixed by #290

**Comment by okeefm** [comment]
Hello,

Yes, there is a fix for this, which we are in the process of reviewing in Pull Request #290. In the short term, you can either:

    checkout the fix_terminology_docker branch, which is the branch behind PR #290, and which is identical to inferno-program v1.6.0 aside from the terminology build fixes.

    Copy the changes from that PR over to the corresponding files in your local Inferno Program directory.

We hope to release an Inferno Program v1.6.1 shortly which will include this fix.

Thank you,
Michael
