### ISSUE TITLE
DocumentReference search by Patient, Category and Date fails (FI-1268)

### ISSUE THREAD

**Issue by lakshmib08** [onc-healthit/inferno-program#310]
Thank you for reporting a possible bug in Inferno! Please fill in as much of the template below as you can.

**DocumentReference search by Patient, Category and Date fails**
Inferno is running a search with a combination of patient, category and date that does not exist in our system.

**Your environment**
Program
* Version of inferno:
inferno.healthit.gov

**Steps to reproduce**
The patient search in step 1 returns 3 records -
The 1st record has - 
**_"category": [
{
"text": "Untitled"
}
],
"subject": {
"reference": "Patient/332769c3-f9e1-4b3d-b1e8-a7efa5ffd25d"
},
"date": "2021-02-04T00:10:07.49+00:00",_**

and the 3rd record has
**_"category": [
{
"coding": [
{
"system": "http://hl7.org/fhir/us/core/CodeSystem/us-core-documentreference-category",
"code": "clinical-note",
"display": "Clinical Note"
}
],
"text": "Clinical Note"
}
],
"subject": {
"reference": "Patient/332769c3-f9e1-4b3d-b1e8-a7efa5ffd25d"
},
"date": "2021-03-02T04:34:05.313+00:00",_**

Inferno searches on -
**_"category=clinical-note&date=2021-02-04T00:10:07.49%2B00:00&patient=332769c3-f9e1-4b3d-b1e8-a7efa5ffd25d"
This search is not valid because no such record exists._**

Thanks.

**Comment by yunwwang** [comment]
It has been identified as a bug in Inferno system. Inferno takes search parameter value from the results of the first search. When there are more than one search parameter, other than patient, the search value may be drawn from different resource instances if one instance does not have all matched elements. Will fix in the next release.

**Comment by yunwwang** [comment]
Working ticket: FI-1268

**Comment by lakshmib08** [comment]
@yunwwang - When can I test this? Thanks.

**Comment by yunwwang** [comment]
Hello @lakshmib08 
If you use Inferno source codes, you can pull the latest from main branch and run tests locally.
If you use Inferno docker image or inferno.healthit.gov website, you have to wait for the v1.7.0 release. We are currently working through the release process. I hope it could be done by next weekend.
