### ISSUE TITLE
USCP-12 returns with warnings of valid codes being invalid

### ISSUE THREAD

**Issue by dkriebel** [onc-healthit/inferno-program#313]
When we run USCP-12 the test passes, but it leaves warnings about unrecognized code set values for our patient, two of them being marital status and language.
![image](https://user-images.githubusercontent.com/27783502/124648514-57246c00-de65-11eb-9934-3df98b766509.png)
![image](https://user-images.githubusercontent.com/27783502/124648641-820ec000-de65-11eb-984b-8187a3a45354.png)

Using language as an example, based on the HL7 spec linked below, we would expect "en" to be an recognized.
[Language codes](http://hl7.org/fhir/R4/valueset-languages.html)

Additionally, we were initially sending a 3-letter code for language because this is what USCDI asks for on patient language (see ISO 369 values included in link). Is the expectation we send a 2-letter or 3-letter language code?
[USCDI Preferred Language](https://www.healthit.gov/isa/taxonomy/term/751/uscdi-v1)

This is running Inferno Program Edition 1.6.0 on a local instance.

**Comment by Jammjammjamm** [comment]
It looks like in those cases the `system` field of a `Coding` is populated with the url for a `ValueSet` rather than a `CodeSystem`. For example, the coding for marital status should look like:
```
{
  "code": "S",
  "system": "http://terminology.hl7.org/CodeSystem/v3-MaritalStatus"
}
```
and not:
```
{
  "code": "S",
  "system": "http://hl7.org/fhir/ValueSet/marital-status"
}
```

**Comment by dkriebel** [comment]
This resolved my issue. Thank you!
