### ISSUE TITLE
Inferno client app doesn't entertain POST on the redirect uri containing code & state values

### ISSUE THREAD

**Issue by Puttajunjaiah01** [onc-healthit/inferno-program#315]
Thank you for reporting a possible bug in Inferno! Please fill in as much of the template below as you can.

**Subject of the issue**
In the Standalone Launch With Patient Scope, Inferno client app doesn't entertain POST on the redirect uri containing code & state values

**Your environment**
* Edition of inferno (Community or Program): Program
* Version of inferno: 1.6.1
* Which browser and version(s) is the bug present on?: Chrome Version 91.0.4472.124

**Steps to reproduce**
1. Launch local installation of Inferno tool on a chrome browser pointing to http://localhost:4567/
2. Enter your FHIR Server URL
3. Fill your client id & client secret in the input fields
4. Click **Execute**
5. Click **Continue** when prompted
6. Complete the oauth2 authorization workflow
7. Select a patient to establish patient context with and proceed

Include:

* The selected test suite **Standalone Launch With Patient Scope**
* The URL of the FHIR server being tested
* The Test ID, if it's a problem with a specific test. **OSLS-02: OAuth server redirects client browser to app redirect URI**
* Any required configuration options (client ID, client secret, etc.)
* Anything else needed to make the issue occur.

**Expected behavior**
We expect the Inferno client app to accept a POST request on the redirect uri containing code & state values in the form data

**Actual behavior**
Inferno client app accepts only GET request on the redirect uri containing code & state values in the query string

**Comment by Jammjammjamm** [comment]
Can you show us where the specs say that POST needs to be supported for the redirect?

**Comment by Puttajunjaiah01** [comment]
You are right. We will have to change our design. Thanks.
