### ISSUE TITLE
Inferno test USCDR-13 is expecting both DocumentReference.attachment.data and DocumentReference.attachment.url in the resource response (FI-1326)

### ISSUE THREAD

**Issue by Puttajunjaiah01** [onc-healthit/inferno-program#316]
**Subject of the issue**
Inferno is complaining **Could not find content.attachment.data in the 4 provided DocumentReference resource(s)**

But as per US Core profile for DocumentReference resource (http://hl7.org/fhir/us/core/StructureDefinition-us-core-documentreference.html),

> The DocumentReference resources can represent the referenced content using either an address where the document can be retrieved using DocumentReference.attachment.url or the content as inline base64 encoded data using DocumentReference.attachment.data.
> Although both are marked as must support, the server system is not required to support both an address and inline base64 encoded data, but SHALL support at least one of these elements.
> The client application SHALL support both elements.
> The content.url may refer to a FHIR Binary Resource (i.e. [base]/Binary/[id]), FHIR Document Bundle (i.e [base]/Bundle/[id] or other endpoint.
> If the endpoint is outside of the FHIR base URL, it SHOULD NOT require additional authorization to access.

So, either data or url need to be implemented. Not both.

**Your environment** 
* Edition of inferno (Community or Program): **Community**
* Version of inferno: **2.12.0**
* Which browser and version(s) is the bug present on?: **Chrome version 91**

**Steps to reproduce**
Perform the test **USCDR-12: All must support elements are provided in the DocumentReference resources returned.** against your FHIR server.

My FHIR server is returning the following content within DocumentReference resource response,
```
    <content>
        <attachment>
            <contentType value="text/plain"/>
            <language value="en"/>
            <url value="Binary/DOC-1941271429811650"/>
        </attachment>
        <format>
            <system value="urn:oid:1.3.6.1.4.1.19376.1.2.3"/>
            <code value="urn:ihe:iti:xds:2017:mimeTypeSufficient"/>
            <display value="MimeType Sufficient"/>
        </format>
    </content>
```

**Expected behavior**
Either DocumentReference.attachment.data or DocumentReference.attachment.url should be present.

**Actual behavior**
Inferno is expecting both DocumentReference.attachment.data and DocumentReference.attachment.url

**Comment by yunwwang** [comment]
Hello @Puttajunjaiah01: 
Thank you for reaching to us. Are you sure the test is USCDR-12 since USCED-12 does not check MustSupport requirement. Would you mind to send me one of your failed DocumentReference resource instance withou any sensitive information? Or if you use inferno.halthit.gov, you could send me the test instance id. Thank you.

**Comment by Puttajunjaiah01** [comment]
Sorry.. this issue was seen in Inferno Community Edition 2.12.0. and the test# in this edition is USCDR-12.

**Comment by yunwwang** [comment]
@Puttajunjaiah01 Sorry that I missed that this is a Community issue. In the future, you could submit Inferno Community related issue to https://github.com/onc-healthit/inferno/issues.
For this issue, what you mentioned is on US Core release 4.0.0. Currently, both Inferno Program and Inferno Community test US Core release 3.1.1. DocumentReference profile in US Core 3.1.1, which is http://hl7.org/fhir/us/core/STU3.1.1/StructureDefinition-us-core-documentreference.html, does not indicate that only one of attachment.data and attachment.url is must supported by server.

**Comment by Puttajunjaiah01** [comment]
Thank you for your reply. I have an additional question,

For criterion § 170.315(g)(10) certification, is the US Core version fixed at 3.1.1? Appreciate your response.

**Comment by yunwwang** [comment]
Current (g)(10) certification test is based on USCore 3.1.1. ONC may adopt new version of USCore in the future in SVAP (Standards Version Advancement Process). https://www.healthit.gov/isa/standards-version-advancement-process

**Comment by Puttajunjaiah01** [comment]
Thank you. That answered my question.

**Comment by Puttajunjaiah01** [comment]
Sorry.. one last clarification. As per [US Core 3.1.1 profile for DocumentReference](http://hl7.org/fhir/us/core/STU3.1.1/StructureDefinition-us-core-documentreference.html) resource, either DocumentReference.content.attachment.url or DocumentReference.content.attachment.data or both SHALL be present. See below. 

![image](https://user-images.githubusercontent.com/76984713/126596240-01670e5d-5554-4732-90ca-d0dd9dd9b61c.png)

 And we support DocumentReference.content.attachment.url.

**Comment by yunwwang** [comment]
That is difference between valid "per resource" validation and must-support "per server". The constraint us-core-6 means that every DocumentReference resource shall have either attachment.url or attachment.data or both. This is enforced by resource validator. The must-support means that server must demonstrate it supports both attachment.data and attachment.url. Inferno asks server to demonstrate such "support" by providing at least one resource for each case (could be the same resource having both). For example, assume the server has 100 DocumentReference resources. If all of the 100 resources have attachment.url but none of them has attachment.data, then all of the 100 resource are valid according to us-core-6. But the server has not demonstrate that it support attachment.data yet. So inferno put the test as "skipped" meaning that inferno has not seen enough evidence yet.

**Comment by cpsi-thrive** [comment]
According to https://jira.hl7.org/browse/FHIR-30111 "This is a case where there is a choice of supporting one or another profile element to meet the must support requirement  see: http://build.fhir.org/ig/HL7/US-Core/conformance-expectations.html#must-support---choice-of-profile-elements" where it indicates "In such instances, the server SHALL support at least one such element."

There is similar language in 3.2.0 (https://hl7.org/fhir/us/core/2021Jan/conformance-expectations.html#must-support---choice-of-profile-elements) where it indicates that the server "SHALL choose to support at least one of these elements."

Is there any chance that this test can be updated to reflect this guidance?  

If not for 3.1.1, is there an estimation on when (or if) (g)(10) and Inferno would be updated for 3.2.0?

**Comment by yunwwang** [comment]
@cpsi-thrive We do realized the updates on US Core v3.2.0/v4.0.0. ONC rules has specified US Core v3.1.1 as standard for certification so Inferno testing has to follow that. As discussed before, ONC will consider new versions of a standard through SVAP process. You can submit comments through ONC feedback channel.

**Comment by yunwwang** [comment]
@Puttajunjaiah01 @cpsi-thrive I will close this ticket as questions were already answered. If you still have questions, please either reopen this issue or create a new one. Thanks.

**Comment by cooperthompson** [comment]
Does this ONC clarification from the CCG apply here:

"A Health IT Module must support at least one Choice or Reference for US Core IG “must support” elements with multiple Choices or References, respectively. "

This constraint is conceptually a "Choice".  It isn't a [x] property, but it really seems like the intent from that ONC statement was that any time you have the option of different must-support elements, servers only have to demonstrate one.

**Comment by yunwwang** [comment]
You can have only one of the choice types. Here, you could have both according to us-core-6

`us-core-6: DocumentReference.content.attachment.url or DocumentReference.content.attachment.data or both SHALL be present.`

The clarification on US Core 4.0 is clear. The question if we could back port that to US Core 3.1.1.

**Comment by yunwwang** [comment]
After investigation and thorough discussion, we decided to update USCDR-13 to follow ONC CCG clarification on choice or reference element:

"A Health IT Module must support at least one Choice or Reference for US Core IG “must support” elements with multiple Choices or References, respectively. "

**Comment by yunwwang** [comment]
@Puttajunjaiah01 @cooperthompson Inferno v1.8.0 is released. Could you verify that this issue has been addressed in this release?
