### ISSUE TITLE
Inferno doesn't support IE11

### ISSUE THREAD

**Issue by cooperthompson** [onc-healthit/inferno-program#319]
**Subject of the issue**
Inferno does not support IE11.  These days, that is entirely reasonable.  However, our system currently *only* supports IE11 for SMART EHR Launch.  We _almost_ done with our migration away from IE11 (it's about time), but we will need to certify on our existing software for at least a few cycles.

**Your environment**
* Edition of inferno (Community or Program): Program
* Version of inferno:  1.6
* Which browser and version(s) is the bug present on?: IE11

**Steps to reproduce**
Perform an EHR Launch to Inferno in IE11.

**Expected behavior**
Ideally, we wouldn't need to ask for IE11 support.  In fact, we aren't really asking you to add support.  We just want an acknowledgement not supporting IE11 is a "known limitation of the test tool".  

We have a simple workaround we can employ for certification to demonstrate that we do support EHR launch, and that Inferno is happy with it (basically, we'll generate the launch URL to Inferno with the launch token and iss, and copy/paste it into Chrome).  However, to be comfortable showing this workaround to our certifier, we want that "known limitation of the test tool" acknowledgment.

**Actual behavior**
Inferno prompts the user with an error indicating that IE11 isn't supported.

Again, 100% agree with anyone looking at this issue and being like "WTF!? who is still using IE11".  Again, we are almost done moving off of it.  Almost...

**Comment by arscan** [comment]
I described a slightly closer-to-real-world workaround here: https://github.com/onc-healthit/inferno-program/issues/235#issuecomment-779470256

Its not great from a test user perspective, but it tests the full capability and not just that the EHR can generate a URL. I was able to get IE11 to do enough to make this work on my local machine with IE11.  Does it work for you?

**Comment by arscan** [comment]
We'll track progress on this in #235.
