### ISSUE TITLE
Invalid HTTP headers can crash inferno container (FI-1302)

### ISSUE THREAD

**Issue by cooperthompson** [onc-healthit/inferno-program#326]
Thank you for reporting a possible bug in Inferno! Please fill in as much of the template below as you can.

**Subject of the issue**
Describe your issue here.
If you include non-printable characters in the HTTP header value for response headers for the oauth2/token response, the Inferno docker container will crash.  These headers are obviously invalid, but an error is probably better than crashing the whole container.

We discovered this while testing a local install of Inferno program edition.  I haven't attempted to reproduce this against the public one since I don't want to crash it.

**Your environment**
* Edition of inferno (Community or Program): Program
* Version of inferno: 1.6.0
* Which browser and version(s) is the bug present on?: Chrome

**Steps to reproduce**
Tell us how to reproduce this issue.
The HTTP response header we were using is below.  This is intentionally NOT a valid HTTP header.  It is intentionally malformed. Because copy/paste doesn't work well, this is basically just all the ASCII characters (including non-printable characters).

ASCIIHeader: !"#$%&'()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz{|}~â‚¬â€šÆ’â€žâ€¦â€ â€¡Ë†â€°Å â€¹Å’Å½â€˜â€™â€œâ€â€¢â€“â€”Ëœâ„¢Å¡â€ºÅ“Å¾Å¸Â Â¡Â¢Â£Â¤Â¥Â¦Â§Â¨Â©ÂªÂ«Â¬Â­Â®Â¯Â°Â±Â²Â³Â´ÂµÂ¶Â·Â¸Â¹ÂºÂ»Â¼Â½Â¾Â¿Ã€ÃÃ‚ÃƒÃ„Ã…Ã†Ã‡ÃˆÃ‰ÃŠÃ‹ÃŒÃÃŽÃÃÃ‘Ã’Ã“Ã”Ã•Ã–Ã—Ã˜Ã™ÃšÃ›ÃœÃÃžÃŸÃ Ã¡Ã¢Ã£Ã¤Ã¥Ã¦Ã§Ã¨Ã©ÃªÃ«Ã¬Ã­Ã®Ã¯Ã°Ã±Ã²Ã³Ã´ÃµÃ¶Ã·Ã¸Ã¹ÃºÃ»Ã¼Ã½Ã¾Ã

Here is the crash stack:
Jul 22 16:28:23 inferno-host docker-compose[114015]: inferno_1            | INFO | Inferno | GETTING: https://example-host.epic.com/FHIRProxy/api/FHIR/R4/Patient/enoCp373txQSghUte78RDIQ3
Jul 22 16:28:23 inferno-host docker-compose[114015]: inferno_1            | INFO | Inferno | Finished Test: OSLS-12 [pass]
Jul 22 16:28:23 inferno-host docker-compose[114015]: inferno_1            | 10.12.15.19, 10.8.159.38 - - [22/Jul/2021:21:28:23 +0000] "POST /inferno/dZiL3GMwgll/test_sets/test_procedure/sequence_result HTTP/1.1" 200 - 30.9237
Jul 22 16:28:23 inferno-host docker-compose[114015]: inferno_1            | 10.12.15.19, 10.8.159.38 - - [22/Jul/2021:21:28:23 +0000] "GET /inferno/oauth2/static/redirect?code=eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJ1cm46ZXBpYzpjZWMuaW
Jul 22 16:28:23 inferno-host docker-compose[114015]: inferno_1            | bundler: failed to load command: rackup (/usr/local/bundle/bin/rackup)
Jul 22 16:28:23 inferno-host docker-compose[114015]: inferno_1            | /usr/local/bundle/gems/activesupport-5.2.4.5/lib/active_support/core_ext/object/json.rb:38:in `to_json': "\\xE2" from ASCII-8BIT to UTF-8 (Encoding::UndefinedConversio
Jul 22 16:28:23 inferno-host docker-compose[114015]: inferno_1            |         from /usr/local/bundle/gems/activesupport-5.2.4.5/lib/active_support/core_ext/object/json.rb:38:in `to_json'
Jul 22 16:28:23 inferno-host docker-compose[114015]: inferno_1            |         from /usr/local/bundle/gems/activesupport-5.2.4.5/lib/active_support/json/encoding.rb:57:in `to_json'
Jul 22 16:28:23 inferno-host docker-compose[114015]: inferno_1            |         from /usr/local/lib/ruby/2.7.0/json/common.rb:224:in `generate'
Jul 22 16:28:23 inferno-host docker-compose[114015]: inferno_1            |         from /usr/local/bundle/gems/activesupport-5.2.4.5/lib/active_support/json/encoding.rb:102:in `stringify'
Jul 22 16:28:23 inferno-host docker-compose[114015]: inferno_1            |         from /usr/local/bundle/gems/activesupport-5.2.4.5/lib/active_support/json/encoding.rb:35:in `encode'
Jul 22 16:28:23 inferno-host docker-compose[114015]: inferno_1            |         from /usr/local/bundle/gems/activesupport-5.2.4.5/lib/active_support/json/encoding.rb:22:in `encode'
Jul 22 16:28:23 inferno-host docker-compose[114015]: inferno_1            |         from /usr/local/bundle/gems/activesupport-5.2.4.5/lib/active_support/core_ext/object/json.rb:41:in `to_json'
Jul 22 16:28:23 inferno-host docker-compose[114015]: inferno_1            |         from /var/www/inferno/lib/app/models/request_response.rb:28:in `from_request'
Jul 22 16:28:23 inferno-host docker-compose[114015]: inferno_1            |         from /var/www/inferno/lib/app/sequence_base.rb:202:in `block (2 levels) in run_tests'
Jul 22 16:28:23 inferno-host docker-compose[114015]: inferno_1            |         from /var/www/inferno/lib/app/sequence_base.rb:201:in `each'
Jul 22 16:28:23 inferno-host docker-compose[114015]: inferno_1            |         from /var/www/inferno/lib/app/sequence_base.rb:201:in `block in run_tests'
Jul 22 16:28:23 inferno-host docker-compose[114015]: inferno_1            |         from /var/www/inferno/lib/app/sequence_base.rb:176:in `each'
Jul 22 16:28:23 inferno-host docker-compose[114015]: inferno_1            |         from /var/www/inferno/lib/app/sequence_base.rb:176:in `run_tests'
Jul 22 16:28:23 inferno-host docker-compose[114015]: inferno_1            |         from /var/www/inferno/lib/app/sequence_base.rb:127:in `start'
Jul 22 16:28:23 inferno-host docker-compose[114015]: inferno_1            |         from /var/www/inferno/lib/app/sequence_base.rb:104:in `resume'
Jul 22 16:28:23 inferno-host docker-compose[114015]: inferno_1            |         from /var/www/inferno/lib/app/endpoint/oauth2_endpoints.rb:98:in `block in resume_execution'
Jul 22 16:28:23 inferno-host docker-compose[114015]: inferno_1            |         from /usr/local/bundle/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:458:in `block (2 levels) in stream'
Jul 22 16:28:23 inferno-host docker-compose[114015]: inferno_1            |         from /usr/local/bundle/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:644:in `with_params'
Jul 22 16:28:23 inferno-host docker-compose[114015]: inferno_1            |         from /usr/local/bundle/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:458:in `block in stream'
Jul 22 16:28:23 inferno-host docker-compose[114015]: inferno_1            |         from /usr/local/bundle/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:424:in `block in each'
Jul 22 16:28:23 inferno-host docker-compose[114015]: inferno_1            |         from /usr/local/bundle/gems/eventmachine-1.2.7/lib/eventmachine.rb:1077:in `block in spawn_threadpool'

Include:

* The selected test suite:  Standalone Patient App
* The URL of the FHIR server being tested: We were testing an internal URL that isn't public.  Sorry!
* Anything else needed to make the issue occur.
We were sending an HTTP response header that had a value that just included all ASCII characters from 0-256.  

**Expected behavior**
Tell us what should happen.
I think maybe just ignore the header?  I'm not sure if that should get flagged as an error (unless the header was defined in the SMART spec).  This looks like it might be an issue with the library, so maybe just catch exceptions from the library and try to carry on with the tests, failing any that rely on the processing that library is doing?

**Actual behavior**
Tell us what happens instead. Include screenshots if possible.
The inferno docker container crashed.  See stack trace above.

**Comment by cooperthompson** [comment]
FYI - we don't really care about a fix here - we've just stopped sending that test header.  I figured you guys would want to know about a crash though.

**Comment by arscan** [comment]
Thanks for the report @cooperthompson -- at the very least Inferno shouldn't crash on this, but if it is a valid response it should also not error out of the test either.  We'll take a closer look at how to address this.  I think it likely has to do with the step where we serialize response data to save in the database, which doesn't have quite the same guards for exceptions.

**Comment by Jammjammjamm** [comment]
If we just don't want to crash, this can be a pretty easy fix.

**Comment by yunwwang** [comment]
Closed automatically by merged PR. Reopen to be group with other issues for next release
