### ISSUE TITLE
USCLRO-12 shouldn't check references not defined by US Core/USCDI (FI-1297)

### ISSUE THREAD

**Issue by cooperthompson** [onc-healthit/inferno-program#330]
**Subject of the issue**
In some cases, we return references to resources that are not relevant to US Core.  For example, in Observations (for labs) we have a basedOn reference to ServiceRequest.
![image](https://user-images.githubusercontent.com/5863379/127712766-a412de6e-4d53-4fdd-b522-c58ee1ff8f0a.png)

**Your environment**
* Edition of inferno (Community or Program): Program
* Version of inferno: 1.6.1
* Which browser and version(s) is the bug present on?: Chrome

**Steps to reproduce**
Tell us how to reproduce this issue.
Run Inferno against an API server that returns references to resources that are not US Core using a client that isn't authorized for no-USCDI resources.

Include:

* The selected test suite Single Patient API
* The URL of the FHIR server being tested
* The Test ID, if it's a problem with a specific test.  USCLRO-12
* Any required configuration options (client ID, client secret, etc.).  Use a client ID that is authorized for USCDI, but not resources that might be referenced by USCDI data (other than Encounter,Organization,etc. which are specifically called out as needing to resolve).
* Anything else needed to make the issue occur.

**Expected behavior**
Tell us what should happen.
This is something that _could_ be addressed by client registration changes to add all resources that could possibly be referenced, however that has other implications (for example, if the client registration system applies different rules for USCDI/US Core APIs vs. non-USCDI/US Core APIs.

But my proposal is that Inferno just have a specific list of resource types that it checks references for, which would be everything in USCDI, plus those few resource types that are included US Core and the CCG (Encounter, Pracititioner, Organization)

**Actual behavior**
Tell us what happens instead. Include screenshots if possible.
Currently, Inferno will fail a server if it includes references to a resource type that the client is not authorized for, even if that resource type is not within the regulated set.

**Comment by yunwwang** [comment]
@cooperthompson Hello Cooper, this test is based on (g)(10) test procedure (https://www.healthit.gov/test-method/standardized-api-patient-and-population-services)
"All references within the resources can be resolved and validated, as applicable, according to steps 2-6 of this section."
You think "all references" here means "all _USCDI_ references". Is my understanding correct?

**Comment by cooperthompson** [comment]
I think what I'd suggest is that it should be "all references a a client is authorized for".  The test procedure is not specific about what resources a client should be authorized for, but I think a fair assumption is that for testing g10, you'd only be required to authorize a client for USCDI named resources.

**Comment by yunwwang** [comment]
FI-1297

**Comment by yunwwang** [comment]
@cooperthompson Inferno v1.8.0 is released. Could you verify that this issue has been addressed in this release?
