### ISSUE TITLE
Validator does not check id format (FI-1294)

### ISSUE THREAD

**Issue by Jammjammjamm** [onc-healthit/inferno-program#332]
Id format is not being checked by the hl7 validator. Inferno may need to check this itself until the validator is updated.

Zulip thread: https://chat.fhir.org/#narrow/stream/179166-implementers/topic/Epic.20has.20IDs.20that.20are.20more.20than.2064.20characters
Validator issue: https://github.com/hapifhir/org.hl7.fhir.core/issues/513

**Comment by cooperthompson** [comment]
Can you remind me what the Inferno policy is for changes that add constraints?  Does that just determine how you publish release notes for updates?

**Comment by Jammjammjamm** [comment]
If a release includes any changes which add constraints, it will be a minor version increase rather than a patch version increase.
