### ISSUE TITLE
EHB-OELS-12 should allow launch context scopes in token response (FI-1351)

### ISSUE THREAD

**Issue by cooperthompson** [onc-healthit/inferno-program#353]
Thank you for reporting a possible bug in Inferno! Please fill in as much of the template below as you can.

**Subject of the issue**
It looks like EHB-OELS-12 is validating that the returned scopes in the EHR Launch flow match the Clinical Scope syntax, plus a few other knowns scopes:

 EHB-OELS-12: User-level access with OpenID Connect and Refresh Token scopes used. results...
Received scope 'launch/patient' does not follow the format: user/[ resource | * ].[ read | * ]

However, the SMART spec is unclear on whether the request scopes like "launch/patient" should be echoed back on grant or not.  We are sending that as a granted scope in the token, since we did allow the EHR launched app to do patient selection.

**Your environment**
* Edition of inferno (Community or Program):  Program
* Version of inferno:  1.6.2
* Which browser and version(s) is the bug present on?:  Chrome

**Steps to reproduce**
Tell us how to reproduce this issue.
Perform an EHR launch, where the scope of the access token issued by the launch includes the launch/patient scope.  For example (full response trimmed for brevity):

{
  "access_token": "asdf1234",
  "token_type": "bearer",
  "expires_in": 3600,
  "scope": "user/AllergyIntolerance.read user/CarePlan.read user/CareTeam.read user/Condition.read user/Device.read user/DiagnosticReport.read user/Encounter.read user/Goal.read user/Immunization.read user/Location.read user/Medication.read user/MedicationRequest.read user/Observation.read user/Patient.read user/Practitioner.read user/PractitionerRole.read user/Procedure.read fhirUser launch launch/patient offline_access openid",
  "state": "ofmind",
  "refresh_token": "1234adsf",
  "need_patient_banner": "false",
  "patient": "easdf3",
}

Include:

**Expected behavior**
I think EHB-OELS-12 should pass if extra scopes are included in the response.

**Actual behavior**
Tell us what happens instead. Include screenshots if possible.
EHB-OELS-12 fails because we are sending back the launch/patient scope:

 EHB-OELS-12: User-level access with OpenID Connect and Refresh Token scopes used. results...
Received scope 'launch/patient' does not follow the format: user/[ resource | * ].[ read | * ]

Also, more generally, I think it is ok for a server to return extra scopes.  I'm not really sure if there are a ton of cases where that makes sense beyond what is listed in the SMART spec, but I don't think the SMART spec prohibits it.  So maybe EHB-OELS-12 should be much more relaxed that just allowing all the SMART scopes.

**Comment by yunwwang** [comment]
One confusion here is that `launch/patient` is the scope used by standalone launch sequence. Should it be presented in a EHR launch token?

**Comment by cooperthompson** [comment]
I'm not sure that the SMART spec is super clear that launch/patient only applies to standalone launch.  That is the obvious use case, but it doesn't seem like it is prohibited in EHR launch.  We actually have an EHR launch flow that _starts_ outside a patient context (in addition to the normal one that starts in patient context), but if configured appropriately, the non-context launch will prompt the user to pick a patient.  So I think having launch/patient as a scope makes sense there, since we prompted for patient selection rather than using the launch context.

**Comment by yunwwang** [comment]
Quote from (g)(10) test procedure

“launch/patient” (to support “context-standalone-patient” “SMART on FHIR Core Capability” for **Standalone-Launch mode only**);
“launch” (for **EHR-Launch mode only**);

**Comment by cooperthompson** [comment]
We do support "launch" for EHR launch (we send back both "launch" and "launch/patient".  So the question is: which did the test procedure mean when it said that launch/patient was "only" for Standalone launch?

Did they mean:
1. launch/patient is required for Standalone launch, and optional for EHR Launch
2. launch/patient is required for Standalone launch, and prohibited for EHR Launch

We interpreted it to mean #1.

**Comment by cooperthompson** [comment]
Is this something we'd need ONC clarification on?

**Comment by yunwwang** [comment]
We are still investigating how we can address additional scopes presented in token response. We are currently leaning to say that server can return additional scopes but should at least grant scopes required by SMART.
I would appreciate if you could also submit a clarification request to ONC with interpretation (or expectation) from server implementer. So ONC could better understanding the gaps here.

**Comment by cooperthompson** [comment]
I'm wondering if we really need ONC clarification here.  The SMART spec seems pretty clear that the scope on the token response is how the server communicates to the client what scopes were granted.  ONC has set the minimum bar for what scopes _must_ be required and in which scenarios, but I don't see anything that implies that they are limiting EHRs from supporting additional scopes.  If ONC had intended to limit the set of scopes EHRs can grant that would be limiting the interoperability features of the EHR, which seems to be obviously contrary to their intent.

If ONC was saying that launch/patient was prohibited, then they'd be prohibiting EHRs from supporting additional interoperability features beyond the minimum bar they are requiring.

**Comment by cooperthompson** [comment]
@yunwwang - do you have any updates on the change to allow additional scopes beyond the minimum required?  I'm interested in knowing if that is the direction you're going, or if we need to do something on our end.

**Comment by yunwwang** [comment]
@cooperthompson sorry. I forgot to reply to you. There are actually three questions here. 

First one is if Inferno should allow token response include additional scopes that client does not request. 
I think the answer is yes. Server has freedom to add additional scopes beyond requested by client.

The second question is if `launch/patient` could be "returned" in token response during EHR launch. My opinion is that `launch/patient` is an additional scope that server include and Inferno should allow that based on the answer of the first question.

The third question is if `launch/patient` could be "used" in token request during EHR launch. This is beyond Inferno's testing scope. You can submit a comment to ONC to ask for clarification of that.

Now, back to Inferno's headache. Server could include three types of scopes in token response for EHR launch:

- required scopes: `openid`, `fhirUser`, `launch`, `offline_access`
- clinical scopes: `( 'patient' | 'user' ) '/' ( fhir-resource | '*' ) '.' ( 'read' | 'write' | '*' )`
- additional scopes, 

Inferno used to verify just (1) and (2). So it is easy to verify that every scopes returned are either (1) or (2). Such validation does not work with additional scopes.

So we are weighting in two different options
One is that Inferno only validates that all required scopes are presented
Second option is that on top of optional one, Inferno also validates there is at least one clinical scope returned

**Comment by yunwwang** [comment]
@cooperthompson Inferno v1.8.0 is released. Could you verify that this issue has been addressed in this release?
