### ISSUE TITLE
Must-support tests that should be failing are passing incorrectly (FI-1321)

### ISSUE THREAD

**Issue by cooperthompson** [onc-healthit/inferno-program#355]
**Subject of the issue**
Our FHIR server mysteriously starting passing several Inferno tests that we did not expect it to pass (because we have some dev in flight or are waiting on some Inferno fixes documented in other github issues).

These are some example tests that are passing incorrectly.  It appears these are all related to must-support checks.

USCG-08
USCDR-13
USCID-08
USCP-13

Here is an example test session:
https://inferno.healthit.gov/inferno/e7X7MhhmJlv/test_sets/test_procedure/

**Your environment**
* Edition of inferno (Community or Program):  Program
* Version of inferno: 1.6.2
* Which browser and version(s) is the bug present on?: Chrome

**Steps to reproduce**
Tell us how to reproduce this issue.

Include:

* The selected test suite
* The URL of the FHIR server being tested:  Inferno Logo Small https://hit-cert.epic.com:444/FHIRARR98/api/FHIR/R4
* The Test ID, if it's a problem with a specific test. Listed above/
* Any required configuration options (client ID, client secret, etc.)  
* Anything else needed to make the issue occur.

**Expected behavior**
Tell us what should happen.
The tests listed above should fail, based on the returned FHIR content.

**Actual behavior**
Tell us what happens instead. Include screenshots if possible.
The tests pass unexpectedly.

**Comment by cooperthompson** [comment]
Created per @Jammjammjamm.  See https://chat.fhir.org/#narrow/stream/179309-inferno/topic/Intermittently.20passing.20Inferno.20when.20we.20shouldn't.20be

**Comment by Jammjammjamm** [comment]
I've identified the cause of this issue and am working on a fix.
