### ISSUE TITLE
OIDC-02: Inferno is looking at incorrect end point for .well-known configuration

### ISSUE THREAD

**Issue by Puttajunjaiah01** [onc-healthit/inferno-program#356]
**Subject of the issue**
OIDC-02: Inferno is looking at incorrect end point for .well-known configuration

**Your environment**
* Edition of inferno (Community or Program): Program edition
* Version of inferno: 1.6.2
* Which browser and version(s) is the bug present on?: Chrome 92

**Steps to reproduce**
1. Launch Inferno app in Chrome browser
2. Input your FHIR server URL e.g., https://YOUR_FHIR_SERVER/demoAPIServer/fhir/r4
3. Enter your app client id and client secret
4. Click 'Execute'

Include:

* The selected test suite: **OpenID Connect SPC-OIDC-02**
* The URL of the FHIR server being tested
* The Test ID, if it's a problem with a specific test: **SPC-OIDC-02**
* Any required configuration options (client ID, client secret, etc.)
* Anything else needed to make the issue occur.

**Expected behavior**
The URL for .well-known/openid-configuration should be 
https://YOUR_FHIR_SERVER/demoAPIServer/fhir/**_r4_**/.well-known/openid-configuration

**Actual behavior**
Inferno is trying to access .well-known/openid-configuration at 
https://YOUR_FHIR_SERVER/demoAPIServer/fhir/.well-known/openid-configuration

![image](https://user-images.githubusercontent.com/76984713/132180023-707f5fea-17c6-4520-870f-04c5d7f80f22.png)

**Comment by yunwwang** [comment]
Hello @Puttajunjaiah01 
Inferno program does not have a test called "OIDC-02". Do you mean test SPC-OIDC-02?
SPC-OIDC-02 use the "iss" value in id_token payload to build the url for .well-known endpoint. Please check if the "iss" value in your id_token is correct

**Comment by yunwwang** [comment]
@Puttajunjaiah01 I am going to close this issue as question has been answered. If you still experience the same problem. Please either reopen this issue or create a new one. Thanks you.
