### ISSUE TITLE
Bulk data export status check (BDE-07) timeout should be configurable (FI-1327)

### ISSUE THREAD

**Issue by yunwwang** [onc-healthit/inferno-program#359]
Current BDE-07 timeout after 180 seconds. The timeout is calculated as
```
CurrentTime - StartTime + WaitTime
```
where the WaitTime is the value from `retry_after` header (if exist) or the exponential backoff from previous WaitTime

Some server may need more time than 180 seconds to get export ready. 

Inferno should allow tester to manually change the timeout threshold at run time, (ex via UI component)

**Comment by medhost-gkersting** [comment]
I was also curious about the ETA on this fix.

**Comment by yunwwang** [comment]
@jhrpcek @medhost-gkersting  Inferno v1.8.0 is released. Could you verify that this issue has been addressed in this release?

**Comment by jhrpcek** [comment]
We don’t see any new failures introduced and the configurable time-out for multi-patient seems to work.
