### ISSUE TITLE
Inferno issues an error message when patient/Binary.read is added to the Standalone Patient Scope

### ISSUE THREAD

**Issue by IgLysk00** [onc-healthit/inferno-program#362]
**Subject of the issue**
See Issue description
**Your environment**
* Edition of inferno (Community or Program): Program
* Version of inferno: 1.6.2
* Which browser and version(s) is the bug present on?: Chrome
**Steps to reproduce**
Tell us how to reproduce this issue.
Start running Inferno. Add patient/Binary.read to the Standalone Patient Scope before the series of the Standalone Patient App - Full Patient Access tests run. Populate the rest of the input fields as needed. Press Execute. 

Test SPB-OSLS-10 fails with the following error:
'Binary' must be either a valid resource type or '*'
![image](https://user-images.githubusercontent.com/73243391/134188464-81172672-c375-425d-a4b5-8d3a05788aef.png)

**Comment by yunwwang** [comment]
@IgLysk00 Why do you need Binary scope? Inferno does not have any test for Binary.

**Comment by yunwwang** [comment]
@IgLysk00 Why do you need request Binary scope?

**Comment by IgLysk00** [comment]
We included Binary in scope as a FHIR resource supported by our application. But, if Inferno is not testing to resolve the reference returned from DocumentReference resource to the Binary resource, then we can simply not provide scope for Binary resource. You can close this ticket. Thanks.
