### ISSUE TITLE
Value for VitalSigns provided but message says:  Could not find dataAbsentReason in the 8 provided Observation resource(s) (FI-1352)

### ISSUE THREAD

**Issue by jhrpcek** [onc-healthit/inferno-program#364]
Thank you for reporting a possible bug in Inferno! Please fill in as much of the template below as you can.

**Subject of the issue**
Could not find dataAbsentReason in the 8 provided Observation resource(s)
US Core spec only provide a dataAbsentReason when there is no Value for the vital sign. There is a valueQuantity in the json: 
        "resourceType": "Observation",
        "status": "final",
        "valueQuantity": {
          "unit": "Inches",
          "system": "http://unitsofmeasure.org",
          "code": "[in_i]",
          "value": 93
        }
      }

**Your environment**
* Edition of inferno (Community or Program):  Program
* Version of inferno:  1.6.2
* Which browser and version(s) is the bug present on?: Chrome

**Steps to reproduce**
Enter a vital sign with a valueQuantity.

Include:

* The selected test suite:   any of the vitals signs ones
* The URL of the FHIR server being tested
* The Test ID, if it's a problem with a specific test.
* Any required configuration options (client ID, client secret, etc.)
* Anything else needed to make the issue occur.

**Expected behavior**
the message  Could not find dataAbsentReason in the 8 provided Observation resource(s)  should not appear if you have a value filled in.  

 USCOBH-11: All must support elements are provided in the Observation resources returned. results...
Could not find dataAbsentReason in the 8 provided Observation resource(s)

**Actual behavior**
Tell us what happens instead. Include screenshots if possible.

**Comment by yunwwang** [comment]
Observation.dataAbsentReason is labeled as Must Support, so Inferno would want to see it in at least one returned resources. There is no expectation that a single resource contain all Must Support elements.

**Comment by jhrpcek** [comment]
ok - got it, so just one instance of the resource type has to have dataAbsentReason then, thanks.

**Comment by yunwwang** [comment]
@jhrpcek Yes. For a MustSupport element, server must demonstrate that it can populate this element. Inferno tests that if at lease one resource returned has that element.

**Comment by jhrpcek** [comment]
We decided to update our EHR to send dataAbsentReason if the value's UOM didn't have a UCUM code associated with it and put the EHR value and EHR UOM in the dataAbsentReason.text field.   So we are able to setup a test case to pass Inferno in the current version.

**Comment by yunwwang** [comment]
@jhrpcek @cooperthompson Inferno v1.8.0 is released. Could you verify that this issue has been addressed in this release?
