### ISSUE TITLE
Pulse Oximetry Tests -  inferno skipping test saying value fields required even when component.values are included 

### ISSUE THREAD

**Issue by jhrpcek** [onc-healthit/inferno-program#365]
Thank you for reporting a possible bug in Inferno! Please fill in as much of the template below as you can.

**Subject of the issue**

This test is being skipped due to this message: 
USCPO-11: All must support elements are provided in the Observation resources returned. results...
Could not find value, value.value, value.unit, value.system: http://unitsofmeasure.org, value.code: %, dataAbsentReason, component.dataAbsentReason, Observation.value[x]:valueQuantity in the 16 provided Observation resource(s)

Json: 
      "fullUrl": "https://fhir-qa-1.test.yourcareuniverse.net/tenant/7db7dfb5-2f73-4b96-bcf1-131410518850/Observation/f312dd37-fefb-4a98-a751-b2ca91143551",
      "resource": {
        "code": {
          "coding": [
            {
              "system": "http://loinc.org",
              "code": "59408-5",
              "display": "Oxygen saturation in Arterial blood by Pulse oximetry"
            },
            {
              "system": "http://loinc.org",
              "code": "2708-6",
              "display": "Oxygen saturation in Arterial blood"
            }
          ],
          "text": "Pulse Ox Panel"
        },
        "performer": [
          {
            "reference": "Practitioner/b64dc2dd-bc4d-4f74-86f1-266f5caaa2e7",
            "display": "CSIGLER",
            "type": "Practitioner"
          }
        ],
        "subject": {
          "reference": "Patient/7b0fe2ec-e479-4767-9565-ca2208c0c181",
          "type": "Patient"
        },
        "hasMember": [
          {
            "reference": "Observation/066bbbe6-a89b-4387-809f-470d157ebe42",
            "type": "Observation"
          }
        ],
        "encounter": {
          "reference": "Encounter/76af5161-b06f-4a61-b54c-16aa9c62285e",
          "type": "Encounter"
        },
        "component": [
          {
            "code": {
              "coding": [
                {
                  "system": "http://loinc.org",
                  "code": "3151-8",
                  "display": "Inhaled oxygen flow rate"
                }
              ],
              "text": "INHALED OXYGEN FLOW RATE"
            },
            "valueQuantity": {
              "unit": "Liters",
              "system": "http://unitsofmeasure.org",
              "code": "L/min",
              "value": 91
            }
          }
        ],
        "effectiveDateTime": "2021-09-03T07:42:00-05:00",
        "meta": {
          "lastUpdated": "2021-09-18T21:39:51.600198Z",
          "versionId": "7"
        },
        "id": "f312dd37-fefb-4a98-a751-b2ca91143551",
        "category": [
          {
            "coding": [
              {
                "system": "http://terminology.hl7.org/CodeSystem/observation-category",
                "code": "vital-signs",
                "display": "Vital Signs"
              }
            ],
            "text": "Vital Signs"
          }
        ],
        "resourceType": "Observation",
        "status": "final"
      }
    },

**Your environment**
* Edition of inferno (Community or Program): Program
* Version of inferno:  1.6.2
* Which browser and version(s) is the bug present on?: Chrome

**Steps to reproduce**
Create a PulseOx vital sign with 2 components only.

Include:

* The selected test suite: Single Patient API -  Pulse Oximetry Tests 
* The URL of the FHIR server being tested
* The Test ID, if it's a problem with a specific test.     USCPO-11
* Any required configuration options (client ID, client secret, etc.)
* Anything else needed to make the issue occur.

**Expected behavior**
Inferno should not be requiring both a value and component.value to be specified. 
According to US Core Spec 
http://hl7.org/fhir/us/core/STU3.1.1/StructureDefinition-us-core-pulse-oximetry-definitions.html
Under definition #54 54. Observation.value[x]
<html>
<body>

An observation may have; 1) a single value here, 2) both a value and a set of related or component values, or 3) only a set of related or component values. If a value is present, the datatype for this element should be determined by Observation.code. A CodeableConcept with just a text would be used instead of a string if the field was usually coded, or if the type associated with the Observation.code defines a coded value.
--

</body>
</html>

**Actual behavior**
Inferno is skipping test because it's requiring both value and component.value fields:   
Could not find value, value.value, value.unit, value.system: http://unitsofmeasure.org, value.code: %, dataAbsentReason, component.dataAbsentReason, Observation.value[x]:valueQuantity in the 16 provided Observation resource(s)

**Comment by yunwwang** [comment]
This is similar to #364. Both Observation.value is a MustSupport element. Inferno expects to see at least one returned Observation resource has that element populated.

**Comment by yunwwang** [comment]
@jhrpcek 
According to the latest CCG, both Observation.value and Observation.component.value are MustSupported for US Core pulse-oximetry profile. So system is required to demonstrate that it support both elements. Please see this FAQ [How does Inferno test MustSupport flag on an element?](https://github.com/onc-healthit/inferno-program/wiki/FAQ#q-how-does-inferno-test-mustsupport-flag-on-an-element)

**Comment by jhrpcek** [comment]
Yes, thanks, we updated our EHR so we can support both fields now.

**Comment by yunwwang** [comment]
Thanks. I am going to close this issue as question has been answered. If you still experience the same problem, please either reopen this one or create a new issue.
