### ISSUE TITLE
Is Data Absent Reason an allowable value for  Encounter participant.period, reasonCode ? 

### ISSUE THREAD

**Issue by jhrpcek** [onc-healthit/inferno-program#366]
Thank you for reporting a possible bug in Inferno! Please fill in as much of the template below as you can.

**Subject of the issue**
Getting this message from the Single Patient API - Encounter Tests 
Could not find participant.period, reasonCode in the 2 provided Encounter resource(s)
Since we do not collect the participant.period in our EHR system, we are filling the field with a data-absent-reason, but that doesn't seem to be satisfying the test. 

full Encounter json: 
{
  "subject": {
    "reference": "Patient/7b0fe2ec-e479-4767-9565-ca2208c0c181",
    "type": "Patient",
    "display": "149381"
  },
  "identifier": [
    {
      "system": "https://npiregistry.cms.hhs.gov/registry/search-results-table?number=1295169910",
      "type": {
        "coding": [
          {
            "system": "http://terminology.hl7.org/CodeSystem/v2-0203",
            "code": "VN",
            "version": "4.0.1",
            "userSelected": false,
            "display": "Visit number"
          }
        ],
        "text": "encounterId"
      },
      "value": "80457",
      "use": "usual"
    }
  ],
  "meta": {
    "lastUpdated": "2021-09-22T16:46:42.507216Z",
    "versionId": "13"
  },
  "status": "in-progress",
  "period": {
    "start": "2021-09-10T16:19:00+00:00"
  },
  "class": {
    "system": "http://terminology.hl7.org/CodeSystem/v3-ActCode",
    "code": "EMER",
    "version": "4.0.1",
    "userSelected": false,
    "display": "emergency"
  },
  "statusHistory": [
    {
      "period": {
        "start": "2021-09-10T16:19:00+00:00"
      },
      "status": "in-progress"
    }
  ],
  "resourceType": "Encounter",
  "serviceProvider": {
    "reference": "Organization/7a898d9f-9de6-4879-abce-7b4772224888",
    "type": "Organization",
    "display": "1295169910"
  },
  "id": "ab605134-1546-4ad5-a796-b21d8e5ffc01",
  "participant": [
    {
      "individual": {
        "reference": "Practitioner/63f03dd9-503d-4764-ba67-25660b22b0ac",
        "type": "Practitioner",
        "display": "BCONN"
      },
      "type": [
        {
          "coding": [
            {
              "system": "http://terminology.hl7.org/CodeSystem/v3-ParticipationType",
              "code": "ADM",
              "version": "4.0.1",
              "userSelected": false,
              "display": "admitter"
            }
          ],
          "text": "admitter"
        }
      ],
      "period": {
        "extension": [
          {
            "valueCode": "unknown",
            "url": "http://hl7.org/fhir/StructureDefinition/data-absent-reason"
          }
        ]
      }
    },
    {
      "individual": {
        "reference": "Practitioner/63f03dd9-503d-4764-ba67-25660b22b0ac",
        "type": "Practitioner",
        "display": "BCONN"
      },
      "type": [
        {
          "coding": [
            {
              "system": "http://terminology.hl7.org/CodeSystem/v3-ParticipationType",
              "code": "ATND",
              "version": "4.0.1",
              "userSelected": false,
              "display": "attender"
            }
          ],
          "text": "attender"
        }
      ],
      "period": {
        "extension": [
          {
            "valueCode": "unknown",
            "url": "http://hl7.org/fhir/StructureDefinition/data-absent-reason"
          }
        ]
      }
    },
    {
      "individual": {
        "reference": "Practitioner/e6842d0d-a604-4b4d-b007-0f385773dc40",
        "type": "Practitioner",
        "display": "151"
      },
      "type": [
        {
          "coding": [
            {
              "system": "http://terminology.hl7.org/CodeSystem/v3-ParticipationType",
              "code": "PPRF",
              "version": "4.0.1",
              "userSelected": false,
              "display": "primary performer"
            }
          ],
          "text": "primary care physician"
        }
      ],
      "period": {
        "extension": [
          {
            "valueCode": "unknown",
            "url": "http://hl7.org/fhir/StructureDefinition/data-absent-reason"
          }
        ]
      }
    }
  ],
  "reasonCode": [
    {
      "extension": [
        {
          "valueCode": "unknown",
          "url": "http://hl7.org/fhir/StructureDefinition/data-absent-reason"
        }
      ]
    }
  ],
  "type": [
    {
      "coding": [
        {
          "system": "http://snomed.info/sct",
          "code": "423215004",
          "display": "Provision of continuity of care"
        }
      ]
    }
  ]
}

**Your environment**
* Edition of inferno (Community or Program): Program
* Version of inferno: 1.6.2
* Which browser and version(s) is the bug present on?: Chrome

**Steps to reproduce**
Tell us how to reproduce this issue.

Include:

* The selected test suite
* The URL of the FHIR server being tested
* The Test ID, if it's a problem with a specific test.
* Any required configuration options (client ID, client secret, etc.)
* Anything else needed to make the issue occur.

**Expected behavior**
Tell us what should happen.

**Actual behavior**
Tell us what happens instead. Include screenshots if possible.

**Comment by yunwwang** [comment]
@jhrpcek 
Is this "USCE-03 All must support elements are provided in the Encounter resources returned"?

**Comment by jhrpcek** [comment]
I'm sorry - yes,    USCE-03: All must support elements are provided in the Encounter resources returned. results...
Could not find participant.period, reasonCode in the 2 provided Encounter resource(s)

**Comment by yunwwang** [comment]
"MustSupport" for server means the server must be able to demonstrate that it supports an element in a reasonable way. We don't count using DataAbsentReason extension as a reasonable way to demonstrate such support. 
Otherwise, a server could simply put DAR extension in every element and claim to be conformant.

**Comment by jhrpcek** [comment]
What do we do if we don't collect/store a piece of data in our EHR then?

**Comment by yunwwang** [comment]
The server is not conformant to ONC (g)(10) certificate.
As a developer, you can ask US Core to remove (or clarify) MustSupport label from those elements
or you can ask ONC to clarify (g)(10) requirement on those elements

**Comment by jhrpcek** [comment]
it does look like the online version is passing the tests filling in data-absent-reason for the field but our local version is not.   You can see that in the saved run I just did:   https://inferno.healthit.gov/inferno/hoKjeXsHNiA/

So again, i'm confused why the online version is reporting issues differently...

**Comment by yunwwang** [comment]
Oh. We have identified an issue on MustSupport test in v1.6.2 which may randomely pass a MS test which should not be passed because of multiple tests running at the same time. This is why the test passed on the online version (because there are other users testing at the same time) while failed locally (because you are the only user there)

This is fixed in v1.7.0.

**Comment by jhrpcek** [comment]
Yes that would explain it.  How do I access an online version of 1.7.0?

**Comment by yunwwang** [comment]
v1.7.0 is just published in GitHub 15 minutes ago. You could try to update docker image now. The inferno website is already updated to v1.7.0

**Comment by jhrpcek** [comment]
great timing!   you can close this ticket then since it's related to DAR which we've talked about already.

**Comment by jhrpcek** [comment]
I do have one more question for Encounter Tests - it says it uses encounter from previous tests, however I have a 2nd encounter returned from my Condition tests but it's not picking it up during the Encounter tests.  Is there another previous Test/Resource that I need to have encounter data entered in order to get the Encounter Id picked up in the Encounter Tests?

**Comment by yunwwang** [comment]
We don't use Condition.encounter because the type is `Reference(Enounter)`. Inferno saves the reference if the type is (or contains) `Reference(US Core Encounter)`. There are two is US Core:
DocumentReference.context.encounter
DiagnosticReport( Note).encounter

**Comment by yunwwang** [comment]
I will close this ticket as question has been answered. If you experience the same behavior, you can either reopen this issue or create a new issue
