### ISSUE TITLE
Different uom for Observation.referenceRange[0].age fail the low to high test

### ISSUE THREAD

**Issue by jhrpcek** [onc-healthit/inferno-program#368]
Thank you for reporting a possible bug in Inferno! Please fill in as much of the template below as you can.

**Subject of the issue**

Laboratory Result Observation Tests 

it seems when the units of measure are different between the low and high ranges, the value comparison is failing.  When they are the same it works.  I change the example below to be the same UOM and now it passes. 

 USCLRO-01: Server returns valid results for Observation search by patient+category. results...
Invalid Observation: Observation.referenceRange[0].age: rng-2: If present, low SHALL have a lower value than high [low.empty() or high.empty() or (low <= high)] * Observation.referenceRange[1].age: rng-2: If present, low SHALL have a lower value than high [low.empty() or high.empty() or (low <= high)]

            "age": {
              "high": {
                "unit": "M",
                "system": "http://unitsofmeasure.org",
                "code": "mo",
                "value": 1
              },
              "low": {
                "unit": "D",
                "system": "http://unitsofmeasure.org",
                "code": "d",
                "value": 0
              }
            }

            "age": {
              "high": {
                "unit": "Y",
                "system": "http://unitsofmeasure.org",
                "code": "a",
                "value": 10
              },
              "low": {
                "unit": "Y",
                "system": "http://unitsofmeasure.org",
                "code": "a",
                "value": 2
              }
            }

**Your environment**
* Edition of inferno (Community or Program): Program
* Version of inferno: 1.7.0
* Which browser and version(s) is the bug present on?: Chrome

**Steps to reproduce**
Tell us how to reproduce this issue.

Include:

* The selected test suite
* The URL of the FHIR server being tested
* The Test ID, if it's a problem with a specific test.
* Any required configuration options (client ID, client secret, etc.)
* Anything else needed to make the issue occur.

**Expected behavior**
Tell us what should happen.

**Actual behavior**
Tell us what happens instead. Include screenshots if possible.

**Comment by jhrpcek** [comment]
thanks, missed that requirement.

**Comment by yunwwang** [comment]
I close this issue as question has been addressed. Please reopen if the same issue happens again.
