### ISSUE TITLE
Inferno does not check if the attachment is downloadable (FI-1373)

### ISSUE THREAD

**Issue by yunwwang** [onc-healthit/inferno-program#374]
Thank you for reporting a possible bug in Inferno! Please fill in as much of the template below as you can.

**Subject of the issue**
Clinical Notes Guidance [requires](http://hl7.org/fhir/us/core/STU3.1.1/clinical-notes-guidance.html#fhir-resources-to-exchange-clinical-notes) that
```quote
Argonaut Clinical Note Server SHALL expose these reports through both 
DiagnosticReport and DocumentReference by representing the same attachment url 
using the corresponding elements listed below:

    DocumentReference.content.attachment.url
    DiagnosticReport.presentedForm.url

```

Currently, Inferno compares url from both DocumentReference and DiagnosticReport but not checking if those urls are downloadable.

**Your environment**
* Edition of inferno (Community or Program): Program
* Version of inferno: 17.0

**Expected behavior**
Inferno should try to download every URL to verify that those urls are real and the attachment is downloadable.

**Comment by yunwwang** [comment]
When download attachment, we should consider adding patient/Binary.read to the token request so that Inferno is authorized to read corresponding Binary attachment (see #362 )

**Comment by cooperthompson** [comment]
I noticed this isn't marked as willfix yet.  I'm specifically interested in allowing the patient/Binary.read scope.  Is there an open question here about whether this will be fixed?  Or should this be marked as willfix?  If there is a question, should we split the patient/Binary.read back into #362 so we can fix that independent of this issue?

**Comment by arscan** [comment]
We are not planning on expanding v1.x with any more tests, so I am closing this here.  Separately, v2.x should allow clients to request patient/Binary.read access, but please let us know if you are still seeing problems there @cooperthompson
