### ISSUE TITLE
Testing read interaction for Location resource (FI-1374)

### ISSUE THREAD

**Issue by czh-orz** [onc-healthit/inferno-program#378]
Thank you for reporting a possible bug in Inferno! Please fill in as much of the template below as you can.

**Subject of the issue**
According to the CCG: 
For the “Location” FHIR resource, Health IT Modules must either demonstrate support for the “read” type interaction or demonstrate support for providing the “Location” and FHIR resource references as a contained resource. The “search” type interactions for these profiles and resource are not in scope for testing and certification. Health IT Modules must support these US Core IG profiles / FHIR resource because they are included as “must support” data elements in US Core IG profiles required by the USCDI._

Inferno program certification doesn't have a Location sequence. It was relying on seeing a reference to a location in Encounter.location in order to test the read operation on Location. Since the reference might not be a literal reference (contains only location.display instead location.reference), it's possible that Inferno never sees a reference to an actual location resource.  Then the location read operation won't be tested.

**Comment by arscan** [comment]
This is not addressed in v1.x but should be addressed already in the latest 2.x release.
