### ISSUE TITLE
Encounter Tests skipped - No Encounter references found from the prior searches

### ISSUE THREAD

**Issue by nicolebzf** [onc-healthit/inferno-program#379]
Prior to submitting the question, I followed the threads [#273](https://github.com/onc-healthit/inferno-program/issues/273) and 
#[153](https://github.com/onc-healthit/inferno-program/issues/153)

DiagnosticReport tests pass, and they have a reference to encounter. 

`        "resourceType": "DiagnosticReport",
        "status": "final",
        "subject": {
          "reference": "Patient/a-1234.E-5678"
        },
        "encounter": {
          "reference": "Encounter/a-1234.encounter-5678"
        },`
        
Main questions: 

1. If DiagnosticReport requests pass, hence generating the necessary reference, why do Encounter tests still fail? 
It would be helpful to see an example Response body, with the reference that is generated in the "US Core Encounter" resources such as DiagnosticReport.

2. Inferno tests will be used as a tool to verify compliance with FHIR - 
**what are the specifications of the request that is expected to return successful Encounter tests? For example, for an Encounter test to pass, it SHOULD pass DiagnosticReport first. ** 

**Environment**

Edition of inferno - Program
Version of inferno: 1.6.2
Browser and version: Chrome Version 94.0.4606.81 (Official Build) (64-bit)

**Steps to reproduce**
Run the Single Patient Inferno tests. The Encounter tests do not pass 

Encounter Tests - 0/4 Required Tests Passed - Hide Details
Verify support for the server capabilities required by the US Core Encounter Profile.

**Test Results**
Inputs
About
USCE-01: Server returns correct Encounter resource from the Encounter read interaction results...
No Encounter references found from the prior searches

USCE-02: Encounter resources returned from previous search conform to the US Core Encounter Profile. results...
No Encounter resources appear to be available.

USCE-03: All must support elements are provided in the Encounter resources returned. results...
No Encounter resources appear to be available.

USCE-04: Every reference within Encounter resources can be read. results...
No Encounter resources appear to be available.

**Comment by yunwwang** [comment]
@nicolebzf The zip file you attached has a Patient resource and Encounter resource but not DiagnosticReport resources. The screen shot show DiagnosticReport for Lab Result. This profile does NOT have reference to US Core Encounter. The  [DiagnosticReport Note profile](http://hl7.org/fhir/us/core/STU3.1.1/StructureDefinition-us-core-diagnosticreport-note.html) or a [DocumentReference profile](http://hl7.org/fhir/us/core/STU3.1.1/StructureDefinition-us-core-documentreference.html) has reference to US Core Encounter profile

**Comment by yunwwang** [comment]
We are talking about several different things in one thread. I will try to clarify:
1) Your original question is about how Inferno test Encounter. I created a FAQ item at [here](https://github.com/onc-healthit/inferno-program/wiki/FAQ#q-how-does-inferno-test-us-core-encounter-resource). In a summary, server need to have a reference to Encounter in either the `encounter` element of `us-core-diagnosticreport-note` profile or `context.encounter` element of `us-core-documentreference` profile
2) Let's look at the DiagnosticReport Note profile. The `encounter` element is optional but MustSupport. That means for all the resources of DiagnosticReport Note profile, there has to be at least one having `encounter` populated.
3) It is the same for the DocumentReference profile that there has to be at least one DocumentReference resource having `context.encounter` element populated
4) The error for the DocumentReference. The element `content.attachment.contentType` is required so the server must try to populated that element. US Core 3.1.1 states if a required element is missing, the server SHALL
```
For coded data elements:
    required binding strength (CodeableConcept or code datatypes):
        use the appropriate “unknown” concept code from the value set if available
```
US Core 4.0 further clarify that
```
if the value set does not have the appropriate “unknown” concept code 
you must use a concept from the value set otherwise the instance will not be conformant
```
So server cannot skip element `content.attachment.contentType`
5) The DiagnosticReport resource in your zip file is still a resource for DiagnosticReport Lab profile. DiagnosticReport Note profile has three category code defined [here](http://hl7.org/fhir/us/core/STU3.1.1/ValueSet-us-core-diagnosticreport-category.html)
6) Here is an [example of DiagnosticReport Note resource](http://hl7.org/fhir/us/core/STU3.1.1/DiagnosticReport-cardiology-report.json.html) and an [example of DocumentReference resource](http://hl7.org/fhir/us/core/STU3.1.1/DocumentReference-episode-summary.json.html). None of these two have encounter element populated but you could add by yourself.

**Comment by nicolebzf** [comment]
@yunwwang thanks for your answers here and for creating a FAQ item about how Encounters are tested - I'm sure this will be helpful for other teams. 

6. I created a DiagnosticReport Note resource after your comment, and I am attaching it here so you can take a look. I reviewed the example resource you provided and it looks fairly similar. The syntax of how the us-core-encounter resource should be returned is important, so I ask that you please be more specific about what this should look like. 

In the attached json file, the encounter reference is found in line 27 and reads: 

    "encounter": {
        "reference": "Encounter/a-1234.encounter-100007"
    },
    
Is this correct?

[DiagnosticReportNotes.zip](https://github.com/onc-healthit/inferno-program/files/7368248/DiagnosticReportNotes.zip)

**Comment by nicolebzf** [comment]
Just added a DiagnosticReport Note with the provided category codes, and the "No Encounter references found from the prior searches" no longer showed - thank you! 

At the moment we 1 Encounter tests skips. 

**The output** 
USCE-03: All must support elements are provided in the Encounter resources returned. is SKIPPED
Message:
Could not find hospitalization, hospitalization.dischargeDisposition in the 1 provided Encounter resource(s)

 **Question**
 Hospitalization is used only for stay type encounters, does this mean that test USCE-03 only passes for inpatient users and not for ambulatory ones? By looking at the US Core Encounter Profile Terminology Bindings, it seems hospitalization is a preferred field, not a required one. 
 
![image](https://user-images.githubusercontent.com/57570357/138284280-d5a271c3-cdf8-4c93-9ce9-28345ab99acd.png)

**Comment by nicolebzf** [comment]
I also noticed that if only one subtest is skipped, then the icon for the test suite for that resource becomes "skipped". 
**Question**
If one test is skipped, does that equate to the test suite failing?

**Comment by yunwwang** [comment]
@nicolebzf I have created two new FAQs to answer your question https://github.com/onc-healthit/inferno-program/wiki/FAQ. Please let me know if that helps.
