### ISSUE TITLE
warning:  Unknown code system for NDC values for the MedicationRequest resource

### ISSUE THREAD

**Issue by jhrpcek** [onc-healthit/inferno-program#380]
Thank you for reporting a possible bug in Inferno! Please fill in as much of the template below as you can.

**Subject of the issue**
Warning message for MedicationRequest stating  Line #3: Unknown Code System: http://hl7.org/fhir/sid/ndc
This seems to be the correct system code for NDC values according to this:   https://www.hl7.org/fhir/ndc.html  
If not, please specify what is the correct system code for NDC values for medications.

**Your environment**
* Edition of inferno (Community or Program): Program
* Version of inferno:  1.7.0
* Which browser and version(s) is the bug present on?:Chrome

**Steps to reproduce**
specify an NDC for a MedicationRequest resource. 

Include:
{"encounter":{"type":"Encounter","display":"5261172","reference":"Encounter/ebcea0a0-39df-4bc5-b022-10f3fbd8362e"},"reportedBoolean":false,"intent":"original-order","resourceType":"MedicationRequest","category":[{"text":"Discharge","coding":[{"display":"Discharge","code":"discharge","system":"http://terminology.hl7.org/CodeSystem/medicationrequest-category"}]}],"meta":{"lastUpdated":"2021-10-14T16:18:30.172270Z","versionId":"2"},"medicationCodeableConcept":{"text":"LISINOPRIL Oral Tablet 40 MG","coding":[{"code":"197884","system":"http://www.nlm.nih.gov/research/umls/rxnorm"},{"code":"00591040901","system":"http://hl7.org/fhir/sid/ndc"}]},"requester":{"type":"Practitioner","display":"HMS","reference":"Practitioner/e8d54cdf-27a5-4293-adb9-3fe07183bb19"},"status":"cancelled","authoredOn":"2021-10-14T16:17:56+00:00","dosageInstruction":[{"text":"1 TAB BY MOUTH DAILY","timing":{"code":{"text":"DAILY"}},"asNeededBoolean":false,"doseAndRate":[{"doseQuantity":{"value":1,"unit":"TAB"}}],"route":{"text":"PO"}}],"subject":{"type":"Patient","display":"81820","reference":"Patient/8e5d203b-b179-45ff-8fb4-bd503113982d"},"substitution":{"allowedBoolean":true},"id":"0b9e80e5-6ca6-4679-9b9d-e460024152c9"}

* The selected test suite:    Multi-patient API tab 
* The URL of the FHIR server being tested   
* The Test ID, if it's a problem with a specific test.     BDGV-15: MedicationRequest resources returned conform to the US Core MedicationRequest Profile
* Any required configuration options (client ID, client secret, etc.)
* Anything else needed to make the issue occur.

**Expected behavior**
Tell us what should happen.

**Actual behavior**
Tell us what happens instead. Include screenshots if possible.

**Comment by yunwwang** [comment]
@jhrpcek  I will close this issue as question had been answered. If you are still experiencing similar issue, you can either reopen this issue or create a new one. Thank you.
