### ISSUE TITLE
XDR Receiver request says Invalid SOAP body

### ISSUE THREAD

**Issue by rashmi1977** [onc-healthit/inferno-program#383]
Hi Team,

While testing (b)(1) -Transition of Care criteria we need to check the XDR receiver in case of invalid SOAP body.
But to compare that the request body is an invalid SOAP body, we need to have a valid schema for comparison. Can you please provide the schema for comparing the response

![Capture](https://user-images.githubusercontent.com/60920244/138443970-804819e1-b8b5-426a-818b-d2d59fa9b7f7.PNG)

So in 4b for validating invalid SOAP body, please provide the valid schema to compare with invalid SOAP body.

**Comment by yunwwang** [comment]
@rashmi1977 This issue is not related to Inferno Program edition. I will close this one. If you have other questions related to Inferno Program, please create a new issue. Thank you.
