### ISSUE TITLE
What version of US Core Implementation Guide should be supported for FHIR v4 Certification?

### ISSUE THREAD

**Issue by alps8** [onc-healthit/inferno-program#388]
Thank you for reporting a possible bug in Inferno! Please fill in as much of the template below as you can.

**FHIR US Core Implementation Guide version**
HL7 specifies the current US Core Implementation Guide version as STU 4.0.0 for FHIR v4. 
HL7 spec : https://hl7.org/fhir/us/core/index.html

However the supported standard as mentioned in the Overview section of the Inferno at https://inferno.healthit.gov/inferno/ is  STU 3.1.1

We are using Inferno to validate our FHIR v4 Implementation and would like to know what is the correct STU version to support.

**Public Sandbox using Inferno website**
* Edition of inferno (Community or Program):  Program
* Version of inferno: 1.7.0
* Which browser and version(s) is the bug present on?: Chrome

**Steps to reproduce**
See the Overview section of Inferno at https://inferno.healthit.gov/inferno/ 
It is mentioned that Inferno only supports : FHIR US Core Implementation Guide (IG) STU 3.1.1

Issue is that the HL7 standard mentions STU4.0.0 as the current US Core Implementation Guide for FHIR v4

Include:

* The selected test suite : Single Patient API
* The URL of the FHIR server being tested : https://inferno.healthit.gov/inferno/ 
* The Test ID, if it's a problem with a specific test.
* Any required configuration options (client ID, client secret, etc.)
* Anything else needed to make the issue occur.

**Expected behavior**
Inferno should support the US Core Implementation Guide for FHIR v4 STU 4.0.0 as mentioned at https://hl7.org/fhir/us/core/index.html

**Actual behavior**
Inferno currently only supports FHIR US Core Implementation Guide (IG) STU 3.1.1

**Comment by yunwwang** [comment]
Inferno Program is based on [ONC (g)(10) Standardized API for patient and population services](https://www.healthit.gov/test-method/standardized-api-patient-and-population-services)

Paragraph (g)(10)(i)(A) references standard [170.215(a)(2)](https://www.healthit.gov/isa/svap-standard/170215a2) which is HL7 FHIR® US Core Implementation Guide STU 3.1.1, August 8, 2020

**Comment by alps8** [comment]
Thanks for the quick response and clarification.
