### ISSUE TITLE
BDE-02: Incorrectly fails this test case (Bulk Data Server declares support for Group export operation in CapabilityStatement) (FI-1366)

### ISSUE THREAD

**Issue by sagarsarvankar** [onc-healthit/inferno-program#390]
Thank you for reporting a possible bug in Inferno! Please fill in as much of the template below as you can.

**BDE-02 fails even when we provide correct URL+"|"+version for operation.definition **

The spec for operation.definition (https://www.hl7.org/fhir/operationdefinition.html) says that this can be a target of a canonical reference. Our FHIR server has a operation.definition value of "http://hl7.org/fhir/uv/bulkdata/OperationDefinition/group-export|1.0.1", which is acceptable going by the spec.

{
"type": "Group",
"profile": "http://hl7.org/fhir/profiles/Group",
"operation": [{
"name": "export",
"definition": "http://hl7.org/fhir/uv/bulkdata/OperationDefinition/group-export|1.0.1"
}]
}

When we run Inferno, this test case fails, it expects the value to be exact "http://hl7.org/fhir/uv/bulkdata/OperationDefinition/group-export"

Could you please address this issue?

**Your environment**
* Edition of inferno (Community or Program): https://inferno.healthit.gov/inferno/
* Version of inferno: 1.7.0
* Which browser and version(s) is the bug present on?: Chrome.

**Steps to reproduce**
Tell us how to reproduce this issue.

Include:

* The selected test suite
* The URL of the FHIR server being tested      https://fhir.secureit.co.in:9443/fhir-server/api/v4   We keep this server active only when we need it. For today we can keep this on, after that whenever you need it active, please let us know and we will do so.
* The Test ID, if it's a problem with a specific test.    BDE-02

**Expected behavior**
This should accept definition value "http://hl7.org/fhir/uv/bulkdata/OperationDefinition/group-export|1.0.1" 

**Actual behavior**
Inferno is marking this test case as a fail, and checking against the exact value "http://hl7.org/fhir/uv/bulkdata/OperationDefinition/group-export"

**Comment by yunwwang** [comment]
CapabilityStatement.rest.resource.operation.definition is a type of `canonical(OperationDefinition)`. Inferno should support canonical url with `|version` postfixed.

**Comment by yunwwang** [comment]
@sagarsarvankar This issue has been fixed in Inferno Program v1.8.2. Would you mind to check if this fix addressed your concern? Thank you.

**Comment by sagarsarvankar** [comment]
Thank you @yunwwang . We will test the same and let you know what happens soon.

**Comment by sagarsarvankar** [comment]
Thank you @yunwwang . This fix has worked. 
I appreciate your efforts in putting a fix so quickly.
