### ISSUE TITLE
Resource: Condition  Test: USCC-05- returns data for only one condition in the JSON response. How does it select which resource to include? 

### ISSUE THREAD

**Issue by tammyham64** [onc-healthit/inferno-program#393]
Thank you for reporting a possible bug in Inferno! Please fill in as much of the template below as you can.

**Subject of the issue**
While running tests in the Condition Resource by Single Patient API, we note that for the test that validates the Read interaction for Condition (and other resource as well) only ONE resource is returned. Specifically this is test USCC-05:  USCC-05: Server returns correct Condition resource from Condition read interaction.

The questions are 
1- When Inferno posts the test as PASSED, even though only the one resource is returned, is this sufficient for us to say, yes, it has Passed? 
2- How does the system choose which resource to return in this test? Ex, sometimes it may be the first entered or have the ID that is the "lowest" numerically, but this is not consistently the case. 

**Your environment**-- https://FHIRI221ES.rd.allscripts.com/fhir-ClinAuth/
* Edition of inferno (Community or Program):  Community
* Version of inferno:  1.7.0
* Which browser and version(s) is the bug present on?:  Microsoft Edge version 95.0.1020.44

**Steps to reproduce**
After retrieving the Token, select Single Patient API and enter the Patient ID of 2287500200 and run all tests. When tests are completed open results of USCC-05

Include:

* The selected test suite: Single patient API run by Patient ID/ Condition Resource
* The URL of the FHIR server being tested  https://FHIRI221ES.rd.allscripts.com
* The Test ID, if it's a problem with a specific test.  USCC-05
* Any required configuration options (client ID, client secret, etc.); only patient ID as shown above 2287500200 
* Anything else needed to make the issue occur.

**Expected behavior**
Tell us what should happen.; Not sure if all conditions should be returned and not just the one condition and what criteria the system uses to select WHICH resource to include.

**Actual behavior**
Results of USCC-05 here: Note that only ONE condition is included in the response. 

{
  "resourceType": "Condition",
  "id": "3226100500",
  "meta": {
    "lastUpdated": "2021-10-06T16:32:21.97-04:00",
    "source": "https://fhiri221es.rd.allscripts.com//fhir-ClinAuth",
    "profile": [
      "http://hl7.org/fhir/us/core/StructureDefinition/us-core-condition"
    ],
    "security": [
      {
        "system": "http://terminology.hl7.org/CodeSystem/v3-Confidentiality",
        "code": "N",
        "display": "normal"
      }
    ]
  },
  "language": "en-US",
  "text": {
    "div": "<div xmlns=\"http://www.w3.org/1999/xhtml\"><style type=\"text/css\">.narrative-text-div-table {display: table;width: 100%}.narrative-text-div-table-row {display: table-row}.narrative-text-div-table-cell {border: 0px solid #999;display: table-cell;padding: 3px 10px;float: left}.narrative-text-img-title {font-size: large;justify-content: center;display: flex;}.narrative-text-img-info {font-style: italic;justify-content: center;display: flex;font-size: small;}</style><table border=\"1px\" cellspacing=\"2px\" cellpadding=\"15px\" width=\"100%\"><tr><td><b>Id</b></td><td><p>3226100500</p></td></tr><tr><td><b>Security</b></td><td><table><tr><td>normal</td><td>(N)</td><td>http://terminology.hl7.org/CodeSystem/v3-Confidentiality</td><td></td><td></td></tr><tr><td colspan=\"5\"></td></tr></table></td></tr><tr><td><b>ClinicalStatus</b></td><td><p><b>Inactive</b></p><table><tr><td>Inactive</td><td>(inactive)</td><td>http://terminology.hl7.org/CodeSystem/condition-clinical</td><td></td><td></td></tr><tr><td colspan=\"5\"></td></tr></table></td></tr><tr><td><b>Category</b></td><td><p><b>Chronic</b></p><table><tr><td>Problem List Item</td><td>(problem-list-item)</td><td>http://hl7.org/fhir/ValueSet/condition-category</td><td></td><td></td></tr><tr><td colspan=\"5\"></td></tr></table></td></tr><tr><td><b>Code</b></td><td><p><b>Singultus</b></p><table><tr><td>Hiccoughs</td><td>(65958008)</td><td>http://snomed.info/sct</td><td></td><td></td></tr><tr><td colspan=\"5\"></td></tr></table></td></tr><tr><td><b>Subject</b></td><td><p>Patient/2287500200</p></td></tr><tr><td><b>Encounter</b></td><td><p>Encounter/2475900270</p></td></tr><tr><td><b>Onset</b></td><td><p>2020-03-07</p></td></tr><tr><td><b>Abatement</b></td><td><p>2021-09-15T10:31:00-04:00</p></td></tr><tr><td><b>RecordedDate</b></td><td><p>2021-09-15T10:31:35-04:00</p></td></tr><tr><td><b>Recorder</b></td><td><p>Practitioner/51201190</p></td></tr><tr><td><b>Asserter</b></td><td><p>Practitioner/51201190</p></td></tr></table></div>"
  },
  "clinicalStatus": {
    "coding": [
      {
        "system": "http://terminology.hl7.org/CodeSystem/condition-clinical",
        "code": "inactive",
        "display": "Inactive"
      }
    ],
    "text": "Inactive"
  },
  "category": [
    {
      "coding": [
        {
          "system": "http://hl7.org/fhir/ValueSet/condition-category",
          "code": "problem-list-item",
          "display": "Problem List Item"
        }
      ],
      "text": "Chronic"
    }
  ],
  "code": {
    "coding": [
      {
        "system": "http://snomed.info/sct",
        "code": "65958008",
        "display": "Hiccoughs"
      }
    ],
    "text": "Singultus"
  },
  "subject": {
    "reference": "https://FHIRI221ES.rd.allscripts.com//fhir-ClinAuth/Patient/2287500200",
    "type": "Patient",
    "display": "Victoria, Whisenhunt"
  },
  "encounter": {
    "reference": "https://FHIRI221ES.rd.allscripts.com//fhir-ClinAuth/Encounter/2475900270",
    "type": "Encounter",
    "display": "1 East-102-A/915051750026/07-Mar-2020 00:47"
  },
  "onsetDateTime": "2020-03-07",
  "abatementDateTime": "2021-09-15T10:31:00-04:00",
  "recordedDate": "2021-09-15T10:31:35-04:00",
  "recorder": {
    "reference": "https://FHIRI221ES.rd.allscripts.com//fhir-ClinAuth/Practitioner/51201190",
    "type": "Practitioner",
    "display": "SCM, AUT Admin (Physician)"
  },
  "asserter": {
    "reference": "https://FHIRI221ES.rd.allscripts.com//fhir-ClinAuth/Practitioner/51201190",
    "type": "Practitioner",
    "display": "SCM, AUT Admin (Physician)"
  }

[COnditions with Provenance response ONLY _excerpt _.txt](https://github.com/onc-healthit/inferno-program/files/7498686/COnditions.with.Provenance.response.ONLY._excerpt._.txt)

[Full INFERNO JSON for Whisenhunt_11-8-21.txt](https://github.com/onc-healthit/inferno-program/files/7498689/Full.INFERNO.JSON.for.Whisenhunt_11-8-21.txt)
}

**Comment by Jammjammjamm** [comment]
> 1- When Inferno posts the test as PASSED, even though only the one resource is returned, is this sufficient for us to say, yes, it has Passed?

Yes.

> 2- How does the system choose which resource to return in this test? Ex, sometimes it may be the first entered or have the ID that is the "lowest" numerically, but this is not consistently the case.

For resources in the patient compartment, the tests generally go like this:
1. Perform a search which only requires the patient id as an external input. This is the broadest search possible for each profile. Store all of the resources found from this search.
2. Perform the other required searches for this profile. Use the resources from step 1 to find values to use for the search parameters.
3. Perform a read using an id from the resources in step 1. I would expect this to the id of the first resource returned in step 1. It doesn't really matter as far as Inferno is concerned, it should be able to read any resource that was returned in an earlier search.
4. Validate all of the resources from step 1.
5. Check that all Must Support fields can be found in the resources from step 1.
6. Check that all references in the resources from step 1 can be read.

**Comment by tammyham64** [comment]
@Jammjammjamm - I'm assuming the response to #1 above also apply when The result shows as passed, but there are **0 Requests,** as in the screen shot below: 
![](https://alm-prod-app1.rd.allscripts.com/tfs/boc_projects/06760244-1701-4e6c-b7fe-9a99666cd265/_apis/wit/attachments/c4d34267-a2e4-4a84-98f5-1b57d1e02307?fileName=image.png)

**Comment by tammyham64** [comment]
![Test USCDR14 passes but 0 requests](https://user-images.githubusercontent.com/88512399/140817298-7dac4dfa-3701-4c44-9e02-d72e0b15a49b.png)

**Comment by Jammjammjamm** [comment]
That would be correct if none of the returned resources contained any references. If there were references, then that seems like a bug.

**Comment by yunwwang** [comment]
@tammyham64 I will close this issue as question had been answered. If you need further clarification, you can either reopen this issue or create a new one. Thank you.
