### ISSUE TITLE
Resource:Procedure  Test:USCPROC-02  Result:Fail , Procedure search patient+date does not match the comparator date in query

### ISSUE THREAD

**Issue by KClayton25** [onc-healthit/inferno-program#404]
Thank you for reporting a possible bug in Inferno! Please fill in as much of the template below as you can.

**Subject of the issue**
Describe your issue here.
While running tests in the Procedure Resource by Single Patient API, for the test that validates the patient+date for Procedure Test USCPROC-02 Result Fails and returns with message "No resources of this type were returned"

**Your environment**
* Edition of inferno (Community or Program): Community
* Version of inferno: 1.8.0
* Which browser and version(s) is the bug present on?: Chrome

**Steps to reproduce**
Tell us how to reproduce this issue.
After retrieving the Token, select Single Patient API and enter the Patient ID of 2287500200 and run all tests. When tests are completed open results of USCPROC-02

Include:

* The selected test suite: Single patient API run by Patient ID/ Procedure Resource
* The URL of the FHIR server being tested: https://servername.domain.com
* The Test ID, if it's a problem with a specific test.: USCPROC-02
* Any required configuration options (client ID, client secret, etc.) only patient ID as shown above 2287500200
* Anything else needed to make the issue occur.

**Expected behavior**
Tell us what should happen.
"A server SHALL support searching by patient+date on the Procedure resource. This test will pass if resources are returned and match the search criteria. If none are returned, the test is skipped."  --- This should PASS if it is using a date in the search that is returned in previous search.

"This will also test support for these date comparators: gt, ge, lt, le. Comparator values are created by taking a date value from a resource returned in the first search of this sequence and adding/subtracting a day. For example, a date of 05/05/2020 will create comparator values of lt2020-05-06 and gt2020-05-04"  -> If this comparator date is NEVER in a patient chart, this Test will always fail(which is the current case).  How does this account for that possibility?

**Actual behavior**
Tell us what happens instead. Include screenshots if possible.
Currently what is happening, "GET   200   https://servername.domain.com/fhir-ClinAuth/Procedure?date=gt2021-11-21T00:00:00-05:00&patient=2287500200", the date in this GET request is not in the list of previously returned search, thus resulting in the test failing.

**Comment by yunwwang** [comment]
@KClayton25 That is strange. Would you mind to post the search bundle from USCPROC-01? Please remove all PHI before you do that.

**Comment by KClayton25** [comment]
Comparator date Failed

![Procedure_PatientDate](https://user-images.githubusercontent.com/88527343/142272536-ae70f50c-4fe9-4122-9326-84db400a1c92.JPG)

 GET 200 https://servername.domain.com/fhir-ClinAuth/Procedure?date=gt2021-11-21T00:00:00-05:00&patient=2287500200

This date "date=gt2021-11-21T00:00:00-05:00" in the GET request does not match any date in the bundle.

**Comment by yunwwang** [comment]
@KClayton25 Can you verify if there is a Procedure (for this patient) having `performedPeriod.start = 2021-11-22T00:00:00-05:00`?

**Comment by KClayton25** [comment]
Yes, it is the 1st Procedure in the Bundle:

"entry": [
    {
      "fullUrl": "https://servername.domain.com/fhir-ClinAuth/procedure/OR20337500680",
      "resource": {
        "resourceType": "Procedure",
        "id": "OR20337500680",
        "meta": {
          "lastUpdated": "2021-11-16T07:55:39.963-05:00",
          "source": "https://servername.domain.com/fhir-ClinAuth",
          "profile": [
            "http://hl7.org/fhir/us/core/StructureDefinition/us-core-procedure"
          ],
          "security": [
            {
              "system": "http://terminology.hl7.org/CodeSystem/v3-Confidentiality",
              "code": "N",
              "display": "normal"
            }
          ]
        },
        "language": "en-US",
        "status": "in-progress",
        "code": {
          "coding": [
            {
              "system": "http://snomed.info/sct",
              "code": "29303009",
              "display": "Electrocardiographic procedure"
            }
          ],
          "text": "Electrocardiogram 12 Lead"
        },
        "subject": {
          "reference": "https://servername.domain.com/fhir-ClinAuth/Patient/2287500200",
          "type": "Patient",
          "display": "Victoria, Whisenhunt"
        },
        "encounter": {
          "reference": "https://servername.domain.com/fhir-ClinAuth/Encounter/2485700270",
          "type": "Encounter",
          "display": "1 East-102-B/915051750028/29-Sep-2021 05:43"
        },
        **"performedPeriod": {
          "start": "2021-11-22T00:00:00-05:00"
        }**,
        "recorder": {
          "reference": "https://servername.domain.com/fhir-ClinAuth/Practitioner/51201190",
          "type": "Practitioner",
          "display": "SCM, AUT Admin (Physician)"
        },
        "asserter": {
          "reference": "https://servername.domain.com/fhir-ClinAuth/Practitioner/51201190",
          "type": "Practitioner",
          "display": "SCM, AUT Admin (Physician)"
        }
      }
    }

**Comment by yunwwang** [comment]
Thanks for confirming that.

[US Core Procedure profile](http://hl7.org/fhir/us/core/STU3.1.1/StructureDefinition-us-core-procedure.html#mandatory-search-parameters) states that 

```quote
SHALL support searching using the combination of the patient and date search parameters:

    including support for these date comparators: gt,lt,ge,le
```

Inferno uses the date from an existing Procedure, which is `2021-11-22T00:00:00-05:00` in your test case, and minus one day to create a search query for `gt` comparator. That is why you have `date=gt2021-11-21T00:00:00-05:00` in your search query.

[FHIR search prefix](https://www.hl7.org/fhir/search.html#prefix) defines `gt` as 

```quote
the range above the search value intersects (i.e. overlaps) with the range of the target value
```

For this specific search, the search range (the range above the search value) is `[2021-11-21T00:00:00-05:00, infinite)` and the target Procedure has period in range `[2021-11-22T00:00:00-05:00, infinite)`. There is an intersection between these two ranges.

So Inferno expects to see (at least) the target Procedure resource in the search result.

**Comment by KClayton25** [comment]
It is expected that this Test may FAIL then?  There is chance that the comparator date used in the GET Request will NOT be linked to any procedure in the initial search result.  So is the expectation that it will FAIL?

**Comment by yunwwang** [comment]
Again, this is a range search. What server should do is check if there is any Procedure having date fell into that range. In this example, the Procedure has date 2021-11-22. When a client search date > 2021-11-21 (`date=gt2021-11-21`), server should include that Procedure because 2021-11-22 IS greater than 2021-11-21
