### ISSUE TITLE
SPB-OSLS-10 reports an error stating 'ServiceRequest' must be either a valid resource type or '*'

### ISSUE THREAD

**Issue by dileeprt** [onc-healthit/inferno-program#405]
Thank you for reporting a possible bug in Inferno! Please fill in as much of the template below as you can.

**Subject of the issue**
SPB-OSLS-10 reports an error stating 'ServiceRequest' must be either a valid resource type or '*'

Describe your issue here.
On manually adding the ServiceRequest resource to the patient scope while running 'STANDALONE PATIENT APP'

![image](https://user-images.githubusercontent.com/70513754/142643320-9fcbe748-be8b-4d90-a8ec-41fa7d71b427.png)

SPB-OSLS-10 test fails with error message stating 
'ServiceRequest' must be either a valid resource type or '*
![image](https://user-images.githubusercontent.com/70513754/142643489-91e6b298-6e5e-478c-8b81-cd8d1d55ce1f.png)

I have added the ServiceRequest scope because Procedure Tests under the  'SINGLE PATIENT API' tab refers to service request
![image](https://user-images.githubusercontent.com/70513754/142643746-7e1b5c86-ecd7-4bb3-9594-7c5c2ab4ec3b.png)

If I remove the patient/ServiceRequest.read scope then some of the Procedure Tests under the  'SINGLE PATIENT API' tab fails as the token does not have the scope for ServiceRequest.

**Your environment**
* Edition of inferno (Community or Program): Program Edition
* Version of inferno: 1.8.0
* Which browser and version(s) is the bug present on?: Chrome browser

**Steps to reproduce**
On manually adding the ServiceRequest resource to the patient scope while running 'STANDALONE PATIENT APP'

SPB-OSLS-10 test fails with error message stating 
'ServiceRequest' must be either a valid resource type or '*

Include:

* The selected test suite
* The URL of the FHIR server being tested
* The Test ID, if it's a problem with a specific test.
* Any required configuration options (client ID, client secret, etc.)
* Anything else needed to make the issue occur.

**Expected behavior**
SPB-OSLS-10 test fails with error message stating 

**Actual behavior**
SPB-OSLS-10 test should pass with 'patient/ServiceRequest.read' scope.

**Comment by yunwwang** [comment]
Inferno test client allows only USCDI related resource types to be specified in the requested scope to avoid server implementation mandates additional scopes from client. 

In version v1.8.0, Inferno fixes the reference validation so that server can reference resources outsides what client have been granted. That means Inferno does not raise error while checking references even server does not grant patiet/ServiceRequest.read permission,

When you run Inferno test, do you get testing error at USCPROC-11 due to server reject client request?

**Comment by dileeprt** [comment]
@yunwwang When I do not add patien/ServiceRequest.read to the token scope then the USCPROC-11 now passed with inferno 1.8.0 (It was previously failing on Inferno 1.6.2).
I apologise for the confusion caused by me. I guess this issue can be closed as the Tests under "Procedure" are passing even without patien/ServiceRequest.read scope.
![image](https://user-images.githubusercontent.com/70513754/142912144-8207929c-f1bd-421b-bb1a-c630d9dcfd98.png)

**Comment by yunwwang** [comment]
Thanks. Close this issue as requested.

**Comment by arscan** [comment]
FYI @yunwwang I added an internal ticket to update the language in that description field slightly to reflect the fact that references to non-US Core resources do not need to be successfully read (e.g. they can return an access denied response).
