### ISSUE TITLE
USCPO-11 test fails

### ISSUE THREAD

**Issue by dileeprt** [onc-healthit/inferno-program#406]
Inferno Version: **1.8.0**
Browser used for testing: **Chrome browser**

USCPO-11 under "Pulse Oximetry Tests" fails with below error:
Message:
Could not find component, component.code, component.code.coding.code: 3151-8, component.value.system: http://unitsofmeasure.org, component.value.code: L/min, component.code.coding.code: 3150-0, component.value, component.value.value, component.value.unit, component.value.code: %, Observation.component:FlowRate, Observation.component:Concentration in the 4 provided Observation resource(s)

But we are able to see those  codes in the responses (PSB). 
Could you please let us know the reason for the error thrown by this test.

Body
{
  "resourceType": "Bundle",
  "id": "1.2.840.1.113883.3.564.1291919857840553181.10.1637600603009.221509",
  "meta": {
    "lastUpdated": "2021-11-22T12:03:23.009-05:00"
  },
  "type": "searchset",
  "total": 2,
  "link": [
    {
      "relation": "self",
      "url": "https://CPSINT000662001.englab.athenahealth.com:9443/demoAPIServer/fhir/r4/Observation?category=vital-signs&date=2021-11-19T02%3A04%3A16-05%3A00&patient=1894685940365810"
    }
  ],
  "entry": [
    {
      "fullUrl": "https://CPSINT000662001.englab.athenahealth.com:9443/demoAPIServer/fhir/r4/Observation/1952906656414970",
      "resource": {
        "resourceType": "Observation",
        "id": "1952906656414970",
        "meta": {
          "versionId": "1952906656414970",
          "lastUpdated": "2021-11-19T02:06:34.097-05:00",
          "profile": [
            "https://docs.mydata.athenahealth.com/fhir-r4/StructureDefinition/athena-observation-profile",
            "http://hl7.org/fhir/us/core/StructureDefinition/us-core-observation-lab",
            "http://hl7.org/fhir/us/core/StructureDefinition/us-core-pulse-oximetry"
          ],
          "security": [
            {
              "system": "http://terminology.hl7.org/CodeSystem/v3-Confidentiality",
              "code": "N",
              "display": "Normal"
            }
          ],
          "tag": [
            {
              "system": "https://docs.mydata.athenahealth.com/fhir-r4/codesystem/athenaFlex/EditTags",
              "code": "New",
              "display": "New"
            },
            {
              "system": "https://docs.mydata.athenahealth.com/fhir-r4/codesystem/athenaFlex/EditTags",
              "code": "Pen",
              "display": "Pen"
            },
            {
              "system": "https://docs.mydata.athenahealth.com/fhir-r4/codesystem/athenaFlex/EditTags",
              "code": "NewPen",
              "display": "New Pen"
            }
          ]
        },
        "text": {
          "status": "generated",
          "div": "<div xmlns=\"http://www.w3.org/1999/xhtml\"><table width=\"100%\"><caption><a href=\"Patient/1894685940365810\">Patient/1894685940365810</a></caption><tbody><tr><td width=\"25%\"><span class=\"text-muted\">fraction of inspired oxygen (FIO2) (59408-5 LOINC)</span></td><td width=\"8%\"><span class=\"text-muted\">2021/11/19</span></td><td width=\"25%\"> -- <a href=\"Practitioner/1225652472001060\">Practitioner/1225652472001060</a><span> 2021/11/19</span></td></tr></tbody></table></div>"
        },
        "identifier": [
          {
            "type": {
              "coding": [
                {
                  "system": "http://terminology.hl7.org/CodeSystem/v2-0203",
                  "code": "U",
                  "display": "Unspecified Identifier"
                }
              ],
              "text": "Unspecified Identifier"
            },
            "system": "https://docs.mydata.athenahealth.com/fhir-r4/athenaFlex/namingsystem/ObservationId/1000-4-9390",
            "value": "1952906656414970"
          }
        ],
        "status": "final",
        "_status": {
          "extension": [
            {
              "url": "https://docs.mydata.athenahealth.com/fhir-r4/StructureDefinition/athena-originalCode",
              "valueCoding": {
                "system": "https://docs.mydata.athenahealth.com/fhir-r4/athenaFlex/codesystem/obsstatus",
                "code": "F",
                "display": "Final results; complete and verified"
              }
            }
          ]
        },
        "category": [
          {
            "coding": [
              {
                "system": "http://terminology.hl7.org/CodeSystem/observation-category",
                "code": "vital-signs",
                "display": "Vital Signs"
              }
            ]
          },
          {
            "coding": [
              {
                "system": "https://docs.mydata.athenahealth.com/fhir-r4/athenaFlex/codesystem/HIERGRPS/1000-4-9390",
                "code": "1234",
                "display": "Chemistry"
              }
            ]
          },
          {
            "text": "Chemistry"
          }
        ],
        "code": {
          "coding": [
            {
              "system": "http://loinc.org",
              "code": "59408-5",
              "display": "Oxygen saturation in arterial blood by pulse oximetry"
            },
            {
              "system": "http://loinc.org",
              "code": "2708-6",
              "display": "Oxygen saturation in Arterial blood"
            },
            {
              "system": "https://docs.mydata.athenahealth.com/fhir-r4/athenaFlex/codesystem/HDID/1000-4-9390",
              "code": "2173",
              "display": "O2SAT(OXIM)"
            }
          ],
          "text": "fraction of inspired oxygen (FIO2)"
        },
        "subject": {
          "reference": "Patient/1894685940365810"
        },
        "encounter": {
          "reference": "Encounter/1952906656414880"
        },
        "effectiveDateTime": "2021-11-19T02:04:16-05:00",
        "issued": "2021-11-19T02:06:34.097-05:00",
        "performer": [
          {
            "reference": "Practitioner/1225652472001060"
          }
        ],
        "dataAbsentReason": {
          "coding": [
            {
              "system": "http://terminology.hl7.org/CodeSystem/data-absent-reason",
              "code": "not-applicable",
              "display": "Not Applicable"
            }
          ],
          "text": "Not Applicable"
        },
        "component": [
          {
            "code": {
              "coding": [
                {
                  "system": "http://loinc.org",
                  "code": "3150-0",
                  "display": "O2 Inspired"
                },
                {
                  "system": "https://docs.mydata.athenahealth.com/fhir-r4/athenaFlex/codesystem/HDID/1000-4-9390",
                  "code": "3123",
                  "display": "O2 INSPIRED"
                }
              ]
            },
            "valueQuantity": {
              "value": 7,
              "unit": "%",
              "system": "http://unitsofmeasure.org",
              "code": "%"
            }
          },
          {
            "code": {
              "coding": [
                {
                  "system": "http://loinc.org",
                  "code": "3151-8",
                  "display": "Inhaled O2"
                }
              ]
            },
            "dataAbsentReason": {
              "coding": [
                {
                  "system": "http://terminology.hl7.org/CodeSystem/data-absent-reason",
                  "code": "unknown",
                  "display": "Unknown"
                }
              ],
              "text": "Unknown"
            }
          }
        ]
      },
      "search": {
        "mode": "match"
      }
    },
    {
      "fullUrl": "https://CPSINT000662001.englab.athenahealth.com:9443/demoAPIServer/fhir/r4/Observation/1952906656414950",
      "resource": {
        "resourceType": "Observation",
        "id": "1952906656414950",
        "meta": {
          "versionId": "1952906656414950",
          "lastUpdated": "2021-11-19T02:06:34.127-05:00",
          "profile": [
            "https://docs.mydata.athenahealth.com/fhir-r4/StructureDefinition/athena-observation-profile",
            "http://hl7.org/fhir/us/core/StructureDefinition/us-core-pulse-oximetry"
          ],
          "security": [
            {
              "system": "http://terminology.hl7.org/CodeSystem/v3-Confidentiality",
              "code": "N",
              "display": "Normal"
            }
          ],
          "tag": [
            {
              "system": "https://docs.mydata.athenahealth.com/fhir-r4/codesystem/athenaFlex/EditTags",
              "code": "New",
              "display": "New"
            },
            {
              "system": "https://docs.mydata.athenahealth.com/fhir-r4/codesystem/athenaFlex/EditTags",
              "code": "Pen",
              "display": "Pen"
            },
            {
              "system": "https://docs.mydata.athenahealth.com/fhir-r4/codesystem/athenaFlex/EditTags",
              "code": "NewPen",
              "display": "New Pen"
            }
          ]
        },
        "text": {
          "status": "generated",
          "div": "<div xmlns=\"http://www.w3.org/1999/xhtml\"><table width=\"100%\"><caption><a href=\"Patient/1894685940365810\">Patient/1894685940365810</a></caption><tbody><tr><td width=\"25%\"><span class=\"text-muted\">oxygen saturation, oximetry (59408-5 LOINC)</span></td><td width=\"42%\"><span class=\"text-muted\">5 %</span></td><td width=\"8%\"><span class=\"text-muted\">2021/11/19</span></td><td width=\"25%\"> -- <a href=\"Practitioner/1225652472001060\">Practitioner/1225652472001060</a><span> 2021/11/19</span></td></tr></tbody></table></div>"
        },
        "identifier": [
          {
            "type": {
              "coding": [
                {
                  "system": "http://terminology.hl7.org/CodeSystem/v2-0203",
                  "code": "U",
                  "display": "Unspecified Identifier"
                }
              ],
              "text": "Unspecified Identifier"
            },
            "system": "https://docs.mydata.athenahealth.com/fhir-r4/athenaFlex/namingsystem/ObservationId/1000-4-9390",
            "value": "1952906656414950"
          }
        ],
        "status": "final",
        "_status": {
          "extension": [
            {
              "url": "https://docs.mydata.athenahealth.com/fhir-r4/StructureDefinition/athena-originalCode",
              "valueCoding": {
                "system": "https://docs.mydata.athenahealth.com/fhir-r4/athenaFlex/codesystem/obsstatus",
                "code": "F",
                "display": "Final results; complete and verified"
              }
            }
          ]
        },
        "category": [
          {
            "coding": [
              {
                "system": "http://terminology.hl7.org/CodeSystem/observation-category",
                "code": "vital-signs",
                "display": "Vital Signs"
              }
            ]
          },
          {
            "coding": [
              {
                "system": "https://docs.mydata.athenahealth.com/fhir-r4/athenaFlex/codesystem/HIERGRPS/1000-4-9390",
                "code": "1347",
                "display": "Pulm function"
              }
            ]
          },
          {
            "text": "Pulm function"
          }
        ],
        "code": {
          "coding": [
            {
              "system": "http://loinc.org",
              "code": "59408-5",
              "display": "Oxygen saturation in arterial blood by pulse oximetry"
            },
            {
              "system": "http://loinc.org",
              "code": "2708-6",
              "display": "Oxygen saturation in Arterial blood"
            },
            {
              "system": "https://docs.mydata.athenahealth.com/fhir-r4/athenaFlex/codesystem/HDID/1000-4-9390",
              "code": "2173",
              "display": "O2SAT(OXIM)"
            }
          ],
          "text": "oxygen saturation, oximetry"
        },
        "subject": {
          "reference": "Patient/1894685940365810"
        },
        "encounter": {
          "reference": "Encounter/1952906656414880"
        },
        "effectiveDateTime": "2021-11-19T02:04:16-05:00",
        "issued": "2021-11-19T02:06:34.127-05:00",
        "performer": [
          {
            "reference": "Practitioner/1225652472001060"
          }
        ],
        "valueQuantity": {
          "value": 5,
          "unit": "%",
          "system": "http://unitsofmeasure.org",
          "code": "%"
        }
      },
      "search": {
        "mode": "match"
      }
    }
  ]
}

 {
      "fullUrl": "https://CPSINT000662001.englab.athenahealth.com:9443/demoAPIServer/fhir/r4/Observation/1952906198412560",
      "resource": {
        "resourceType": "Observation",
        "id": "1952906198412560",
        "meta": {
          "versionId": "1952906198412560",
          "lastUpdated": "2021-11-19T02:03:41.790-05:00",
          "profile": [
            "https://docs.mydata.athenahealth.com/fhir-r4/StructureDefinition/athena-observation-profile",
            "http://hl7.org/fhir/us/core/StructureDefinition/us-core-pulse-oximetry"
          ],
          "security": [
            {
              "system": "http://terminology.hl7.org/CodeSystem/v3-Confidentiality",
              "code": "N",
              "display": "Normal"
            }
          ],
          "tag": [
            {
              "system": "https://docs.mydata.athenahealth.com/fhir-r4/codesystem/athenaFlex/EditTags",
              "code": "New",
              "display": "New"
            },
            {
              "system": "https://docs.mydata.athenahealth.com/fhir-r4/codesystem/athenaFlex/EditTags",
              "code": "Pen",
              "display": "Pen"
            },
            {
              "system": "https://docs.mydata.athenahealth.com/fhir-r4/codesystem/athenaFlex/EditTags",
              "code": "NewPen",
              "display": "New Pen"
            }
          ]
        },
        "text": {
          "status": "generated",
          "div": "<div xmlns=\"http://www.w3.org/1999/xhtml\"><table width=\"100%\"><caption><a href=\"Patient/1894685940365810\">Patient/1894685940365810</a></caption><tbody><tr><td width=\"25%\"><span class=\"text-muted\">Inhaled O2 (59408-5 LOINC)</span></td><td width=\"8%\"><span class=\"text-muted\">2021/11/19</span></td><td width=\"25%\"> -- <a href=\"Practitioner/1225652472001060\">Practitioner/1225652472001060</a><span> 2021/11/19</span></td></tr></tbody></table></div>"
        },
        "identifier": [
          {
            "type": {
              "coding": [
                {
                  "system": "http://terminology.hl7.org/CodeSystem/v2-0203",
                  "code": "U",
                  "display": "Unspecified Identifier"
                }
              ],
              "text": "Unspecified Identifier"
            },
            "system": "https://docs.mydata.athenahealth.com/fhir-r4/athenaFlex/namingsystem/ObservationId/1000-4-9390",
            "value": "1952906198412560"
          }
        ],
        "status": "final",
        "_status": {
          "extension": [
            {
              "url": "https://docs.mydata.athenahealth.com/fhir-r4/StructureDefinition/athena-originalCode",
              "valueCoding": {
                "system": "https://docs.mydata.athenahealth.com/fhir-r4/athenaFlex/codesystem/obsstatus",
                "code": "F",
                "display": "Final results; complete and verified"
              }
            }
          ]
        },
        "category": [
          {
            "coding": [
              {
                "system": "http://terminology.hl7.org/CodeSystem/observation-category",
                "code": "vital-signs",
                "display": "Vital Signs"
              }
            ]
          },
          {
            "coding": [
              {
                "system": "https://docs.mydata.athenahealth.com/fhir-r4/athenaFlex/codesystem/HIERGRPS/1000-4-9390",
                "code": "1351",
                "display": "HPI"
              }
            ]
          },
          {
            "text": "HPI"
          }
        ],
        "code": {
          "coding": [
            {
              "system": "http://loinc.org",
              "code": "59408-5",
              "display": "Oxygen saturation in arterial blood by pulse oximetry"
            },
            {
              "system": "http://loinc.org",
              "code": "2708-6",
              "display": "Oxygen saturation in Arterial blood"
            },
            {
              "system": "https://docs.mydata.athenahealth.com/fhir-r4/athenaFlex/codesystem/HDID/1000-4-9390",
              "code": "2173",
              "display": "O2SAT(OXIM)"
            }
          ],
          "text": "Inhaled O2"
        },
        "subject": {
          "reference": "Patient/1894685940365810"
        },
        "encounter": {
          "reference": "Encounter/1952906198412480"
        },
        "effectiveDateTime": "2021-11-19T01:56:38-05:00",
        "issued": "2021-11-19T02:03:41.790-05:00",
        "performer": [
          {
            "reference": "Practitioner/1225652472001060"
          }
        ],
        "dataAbsentReason": {
          "coding": [
            {
              "system": "http://terminology.hl7.org/CodeSystem/data-absent-reason",
              "code": "not-applicable",
              "display": "Not Applicable"
            }
          ],
          "text": "Not Applicable"
        },
        "component": [
          {
            "code": {
              "coding": [
                {
                  "system": "http://loinc.org",
                  "code": "3151-8",
                  "display": "Inhaled O2"
                },
                {
                  "system": "https://docs.mydata.athenahealth.com/fhir-r4/athenaFlex/codesystem/HDID/1000-4-9390",
                  "code": "539801",
                  "display": "INHALED02"
                }
              ]
            },
            "valueQuantity": {
              "value": 6,
              "unit": "L/min",
              "system": "http://unitsofmeasure.org",
              "code": "L/min"
            }
          },
          {
            "code": {
              "coding": [
                {
                  "system": "http://loinc.org",
                  "code": "3150-0",
                  "display": "O2 Inspired"
                }
              ]
            },
            "dataAbsentReason": {
              "coding": [
                {
                  "system": "http://terminology.hl7.org/CodeSystem/data-absent-reason",
                  "code": "unknown",
                  "display": "Unknown"
                }
              ],
              "text": "Unknown"
            }
          }
        ]
      },
      "search": {
        "mode": "match"
      }
    }

**Comment by yunwwang** [comment]
@dileeprt Thanks for reaching to us. The example you posted is a little bit confusing because it has one Bundle (with 2 entries) and a separated BundleEntry but not in the first Bundle.

The Bundle has entries: `Observation/1952906656414970` and `Observation/1952906656414950`. Neither of these two entries provide `Observation.component.value.code: L/min. 

Here is my test results using the Bundle you posted:

![image](https://user-images.githubusercontent.com/8761175/142921865-2fae4caf-2447-4744-8c4d-17147c8c1bb7.png)

If I add the 3rd Observation (`Observation/1952906198412560`) into the Bundle, then I got no error on USCPO-11.

Could you verify that the Bundle you posted match the Search result in USCPO-01? Thanks

**Comment by yunwwang** [comment]
BTW, one of the resource in the Bundle `Observation/1952906656414970` is not valid. You need remove `http://hl7.org/fhir/us/core/StructureDefinition/us-core-observation-lab` from meta.profile.
