### ISSUE TITLE
USCPO-02/USCPO-03: test fails : Server returns valid results for Observation search by patient+category+date. 

### ISSUE THREAD

**Issue by Amits2070** [onc-healthit/inferno-program#407]
![image](https://user-images.githubusercontent.com/64770988/142920000-7e633954-c0c0-4d74-a176-2406bd40e773.png)

USCPO-02/USCPO-03 test fails with reason as **Invalid Observation: Observation.component[0].value.ofType(Quantity): The code provided (http://unitsofmeasure.org#L/min) is not in the value set http://hl7.org/fhir/ValueSet/ucum-vitals-common**

As per US core pulse oximetry profile https://www.hl7.org/fhir/us/core/STU3.1.1/StructureDefinition-us-core-pulse-oximetry.html . We have expected valueQuantity with required set of value for System = http://unitsofmeasure.org , Code= L/min , unit=L/min for component code 3151-8 . But still this tests are failing. 

ResponseBody : 

{
    "resourceType": "Bundle",
    "id": "1.2.840.1.113883.3.564.1291919857840553181.10.1637607085944.500819",
    "meta": {
        "lastUpdated": "2021-11-23T00:21:25.944+05:30"
    },
    "type": "searchset",
    "total": 1,
    "link": [
        {
            "relation": "self",
            "url": "https://localhost:9443/CentricityPracticeFHIRServer/fhir/r4/Observation?_id=1952906198412560"
        }
    ],
    "entry": [
        {
            "fullUrl": "https://localhost:9443/CentricityPracticeFHIRServer/fhir/r4/Observation/1952906198412560",
            "resource": {
                "resourceType": "Observation",
                "id": "1952906198412560",
                "meta": {
                    "versionId": "1952906198412560",
                    "lastUpdated": "2021-11-19T02:03:41.790+05:30",
                    "profile": [
                        "https://docs.mydata.athenahealth.com/fhir-r4/StructureDefinition/athena-observation-profile",
                        "http://hl7.org/fhir/us/core/StructureDefinition/us-core-pulse-oximetry"
                    ],
                    "security": [
                        {
                            "system": "http://terminology.hl7.org/CodeSystem/v3-Confidentiality",
                            "code": "N",
                            "display": "Normal"
                        }
                    ],
                    "tag": [
                        {
                            "system": "https://docs.mydata.athenahealth.com/fhir-r4/codesystem/athenaFlex/EditTags",
                            "code": "New",
                            "display": "New"
                        },
                        {
                            "system": "https://docs.mydata.athenahealth.com/fhir-r4/codesystem/athenaFlex/EditTags",
                            "code": "Pen",
                            "display": "Pen"
                        },
                        {
                            "system": "https://docs.mydata.athenahealth.com/fhir-r4/codesystem/athenaFlex/EditTags",
                            "code": "NewPen",
                            "display": "New Pen"
                        }
                    ]
                },
                "text": {
                    "status": "generated",
                    "div": "<div xmlns=\"http://www.w3.org/1999/xhtml\"><table width=\"100%\"><caption><a href=\"Patient/1894685940365810\">Patient/1894685940365810</a></caption><tbody><tr><td width=\"25%\"><span class=\"text-muted\">Inhaled O2 (59408-5 LOINC)</span></td><td width=\"8%\"><span class=\"text-muted\">2021/11/19</span></td><td width=\"25%\"> -- <a href=\"Practitioner/1225652472001060\">Practitioner/1225652472001060</a><span> 2021/11/19</span></td></tr></tbody></table></div>"
                },
                "identifier": [
                    {
                        "type": {
                            "coding": [
                                {
                                    "system": "http://terminology.hl7.org/CodeSystem/v2-0203",
                                    "code": "U",
                                    "display": "Unspecified Identifier"
                                }
                            ],
                            "text": "Unspecified Identifier"
                        },
                        "system": "https://docs.mydata.athenahealth.com/fhir-r4/athenaFlex/namingsystem/ObservationId/1000-4-9390",
                        "value": "1952906198412560"
                    }
                ],
                "status": "final",
                "_status": {
                    "extension": [
                        {
                            "url": "https://docs.mydata.athenahealth.com/fhir-r4/StructureDefinition/athena-originalCode",
                            "valueCoding": {
                                "system": "https://docs.mydata.athenahealth.com/fhir-r4/athenaFlex/codesystem/obsstatus",
                                "code": "F",
                                "display": "Final results; complete and verified"
                            }
                        }
                    ]
                },
                "category": [
                    {
                        "coding": [
                            {
                                "system": "http://terminology.hl7.org/CodeSystem/observation-category",
                                "code": "vital-signs",
                                "display": "Vital Signs"
                            }
                        ]
                    },
                    {
                        "coding": [
                            {
                                "system": "https://docs.mydata.athenahealth.com/fhir-r4/athenaFlex/codesystem/HIERGRPS/1000-4-9390",
                                "code": "1351",
                                "display": "HPI"
                            }
                        ]
                    },
                    {
                        "text": "HPI"
                    }
                ],
                "code": {
                    "coding": [
                        {
                            "system": "http://loinc.org",
                            "code": "59408-5",
                            "display": "Oxygen saturation in arterial blood by pulse oximetry"
                        },
                        {
                            "system": "http://loinc.org",
                            "code": "2708-6",
                            "display": "Oxygen saturation in Arterial blood"
                        },
                        {
                            "system": "https://docs.mydata.athenahealth.com/fhir-r4/athenaFlex/codesystem/HDID/1000-4-9390",
                            "code": "2173",
                            "display": "O2SAT(OXIM)"
                        }
                    ],
                    "text": "Inhaled O2"
                },
                "subject": {
                    "reference": "Patient/1894685940365810"
                },
                "encounter": {
                    "reference": "Encounter/1952906198412480"
                },
                "effectiveDateTime": "2021-11-19T01:56:38+05:30",
                "issued": "2021-11-19T02:03:41.790+05:30",
                "performer": [
                    {
                        "reference": "Practitioner/1225652472001060"
                    }
                ],
                "dataAbsentReason": {
                    "coding": [
                        {
                            "system": "http://terminology.hl7.org/CodeSystem/data-absent-reason",
                            "code": "not-applicable",
                            "display": "Not Applicable"
                        }
                    ],
                    "text": "Not Applicable"
                },
                "component": [
                    {
                        "code": {
                            "coding": [
                                {
                                    "system": "http://loinc.org",
                                    "code": "3151-8",
                                    "display": "Inhaled O2"
                                },
                                {
                                    "system": "https://docs.mydata.athenahealth.com/fhir-r4/athenaFlex/codesystem/HDID/1000-4-9390",
                                    "code": "539801",
                                    "display": "INHALED02"
                                }
                            ]
                        },
                        "valueQuantity": {
                            "value": 6,
                            "unit": "L/min",
                            "system": "http://unitsofmeasure.org",
                            "code": "L/min"
                        }
                    },
                    {
                        "code": {
                            "coding": [
                                {
                                    "system": "http://loinc.org",
                                    "code": "3150-0",
                                    "display": "O2 Inspired"
                                }
                            ]
                        },
                        "dataAbsentReason": {
                            "coding": [
                                {
                                    "system": "http://terminology.hl7.org/CodeSystem/data-absent-reason",
                                    "code": "unknown",
                                    "display": "Unknown"
                                }
                            ],
                            "text": "Unknown"
                        }
                    }
                ]
            },
            "search": {
                "mode": "match"
            }
        }
    ]
}

**Comment by yunwwang** [comment]
Are you using Inferno Program or Inferno Community?

**Comment by Amits2070** [comment]
Inferno Version: 1.8.0
Browser used for testing: Chrome browser

**Comment by yunwwang** [comment]
Are you running this locally or on inferno.healthit.gov?

**Comment by Amits2070** [comment]
Running locally only

**Comment by yunwwang** [comment]
Are you using external_validator or internal_validator? You can find that in config.yml

```
# Resource validator options:
# - "internal" uses the ruby validator from the fhir_models gem
#   https://github.com/fhir-crucible/fhir_models
# - "external" uses the a web interface for the L7 FHIR validator.
#   https://github.com/inferno-community/fhir-validator-wrapper
resource_validator: external
```

**Comment by Amits2070** [comment]
I also cross verified that after running the tests

![image](https://user-images.githubusercontent.com/64770988/142926311-5d91c7c8-422a-4e74-a6f7-eca6adeea339.png)

**Comment by Amits2070** [comment]
USCPO-11 test is also failing with reason as component, component.code, component.code.coding.code: 3151-8, component.value.system: http://unitsofmeasure.org, component.value.code: L/min, component.code.coding.code: 3150-0, component.value, component.value.value, component.value.unit, component.value.code: %, component.dataAbsentReason, Observation.component:FlowRate, Observation.component:Concentration in the 4 provided Observation resource(s). 

But I have the component code 3151-8 , 3150-0 in my response payload. I am attaching txt file containing json observation bundle.
[bundle.txt](https://github.com/onc-healthit/inferno-program/files/7584026/bundle.txt)

**Comment by yunwwang** [comment]
That is strange. HL7 validator does raise those errors but Inferno validator downgrades those from `error` to `informational` so It is strange that you still see those as `errors`. Can you verify the validator version you are running?

About the USCPO-11, @dileeprt raised #406.

**Comment by Amits2070** [comment]
Where i can find validator version ??

**Comment by yunwwang** [comment]
If you are using web client, client the version number at the bottom right

![image](https://user-images.githubusercontent.com/8761175/142929712-c5e71b4f-0278-4ca0-8d27-96d5aa0e5346.png)

The validator version show on the top of the popup

![image](https://user-images.githubusercontent.com/8761175/142929812-1c0b2412-e546-48ae-90d7-a0c086c7d1be.png)

**Comment by Amits2070** [comment]
Can you check bundle.txt and let me know the result for USCPO-11 ?

**Comment by yunwwang** [comment]
I tested using the three resource provided in #406, one of three resources is not valid. I provided details in #406.
