### ISSUE TITLE
Unable to select "Public Client" under Predefined Test Parameters

### ISSUE THREAD

**Issue by dileeprt** [onc-healthit/inferno-program#409]
Inferno Version: 1.8.1 Program Edition
Browser used: Chrome browser

I'm unable to check the "Public Client" option under Predefined Test Parameters before running the "STANDALONE PATIENT APP".
Clicking on that option has no effect and always "Confidential Client" is selected by default.

Could you please help as we are blocked from testing with Public Client

![image](https://user-images.githubusercontent.com/70513754/143053744-b4a5ee9f-7ec7-4401-9669-331b6c6bad9a.png)

**Comment by arscan** [comment]
Inferno's g10 test kit (program edition) is mostly organized around a handful of scenarios, that in sum demonstrate almost all requirements of the certification criteria (the first 5 tabs).  The remaining handful of requirements not covered in those scenarios are tested in the 6th 'Other' tab.

The 'Standalone Patient App' scenario specifically requires the system to demonstrate a confidential client app launch, along with a number of other requirements (patient scope, patient context, openid connect, full access to USCDI/US Core resource types for the patient, refresh token, etc).  We do not use that scenario to show the public client launch requirement.

For public client launches, look in the 'Other' tab and run the 'Public Client Standalone Launch with OpenID Connect' test. That is a less end-to-end integrated test (it doesn't attempt to read resources to see if the scopes match what was actually granted, for example).  It is just targetted at showing that you can support a public client launch.

If you'd like a more open-ended set of tests that aren't locked into specific scenarios/examples, look in the 'Community Edition'.  That is a more of an open sandbox for testing.

Does this clarify your question?
