### ISSUE TITLE
Inferno uses the latest HL7 FHIR validator (FI-1380)

### ISSUE THREAD

**Issue by yunwwang** [onc-healthit/inferno-program#414]
Inferno Program edition v1.8.1 uses Infenro validator-wrapper v1.2.0 which depends on HL7 Core validator v5.2.10.

The latest HL7 core validator (https://github.com/hapifhir/org.hl7.fhir.core) is v5.6.1

Inferno should adopt the latest release of HL7 core validator

**Comment by nathanloyer** [comment]
We've been using the validator wrapper 2.0.0 with our deployment (external) and it seems to be mostly working. I am unsure if that is something we should be doing or not. IIRC there was a bugfix in version 2 that my team needs to get our validation passing in certain situations.

**Comment by yunwwang** [comment]
the new one validator wrapper will be build on v2.1.0 so you should have the same fix on v2.0.0

**Comment by nathanloyer** [comment]
Oh ok, so you're going to update the validator wrapper to the latest version of the validator, then update inferno to use that new wrapper version.

Awesome, thanks. Will pick that up once you get it deployed.
