### ISSUE TITLE
USCDRRN : Diagnostic Report Notes tests do not allow LP7787-7 for Category

### ISSUE THREAD

**Issue by alps8** [onc-healthit/inferno-program#416]
Thank you for reporting a possible bug in Inferno! Please fill in as much of the template below as you can.

**Clinical Category not supported**
All Inferno tests under USCDRRN are being skipped for our data, because the test is only testing for Categories LP29684-5, LP29708-2, LP7839-6
We are using a category of LP7787-7 (Clinical) for all our Diagnostic Report Notes.
https://hl7.org/fhir/us/core/STU3.1.1/ValueSet-us-core-diagnosticreport-category.html specifies that Category is an extensible set.

**Your environment**
* Edition of inferno (Community or Program): Program
* Version of inferno: 1.7.0
* Which browser and version(s) is the bug present on?: Chrome

**Steps to reproduce**
Test data should contain Diagnostic Report Notes with category LP7787-7
Run tests under USCDRRN : DiagnosticReport For Report And Note Exchange Tests

Include:

* The selected test suite : Single Patient API
* The URL of the FHIR server being tested : https://inferno.healthit.gov/inferno/
* The Test ID, if it's a problem with a specific test : USCDRRN-01
* Any required configuration options (client ID, client secret, etc.)
* Anything else needed to make the issue occur.

**Expected behavior**
USCDRRN tests should test for Category LP7787-7

**Actual behavior**
USCDRRN tests do not test for Category LP7787-7

**Comment by Jammjammjamm** [comment]
US Core [requires that LP29684-5, LP29708-2, and LP7839-6 be supported](http://hl7.org/fhir/us/core/STU3.1.1/StructureDefinition-us-core-diagnosticreport-note.html#mandatory-and-must-support-data-elements), so using a category of `LP7787-7` for all diagnostic report notes is not conformant.
> The `DiagnosticReport.category` binding must support at a minimum the [US Core DiagnosticReport Category Codes](http://hl7.org/fhir/us/core/STU3.1.1/ValueSet-us-core-diagnosticreport-category.html) of Cardiology, Radiology, and Pathology. Other categories may be supported.

**Comment by alps8** [comment]
Thanks for the quick response and clarification.
