### ISSUE TITLE
USCDRRN-12 is being skipped for data that is not required

### ISSUE THREAD

**Issue by alps8** [onc-healthit/inferno-program#417]
Thank you for reporting a possible bug in Inferno! Please fill in as much of the template below as you can.

**Encounter and Performer are not Mandatory fields. But test is skipped when these dont exist**
When there are Diagnostic Report Notes that do not have an Encounter and Performer, the test USCDRRN-12 is being skipped. This test should pass because those fields are not mandatory.

encounter and performer, both have a cardinality of 0..1 even though they are MUST support elements.
As per http://hl7.org/fhir/us/core/general-guidance.html#missing-data the data element with cardinality of 0..1 can be ommitted from the resource

**Your environment**
* Edition of inferno (Community or Program): Program
* Version of inferno: v1.8.2
* Which browser and version(s) is the bug present on?: Chrome

**Steps to reproduce**
Run the tests for USCDRRN for a Diagnostic Report Note without encounter and performer elements in the resource

Include:

* The selected test suite : USCDRRN
* The URL of the FHIR server being tested : 
* The Test ID, if it's a problem with a specific test : USCDRRN-12
* Any required configuration options (client ID, client secret, etc.)
* Anything else needed to make the issue occur.

**Expected behavior**
USCDRRN-12 test should pass when data elements with cardinality of 0..1 are missing in the resource

**Actual behavior**
Message:
Could not find encounter, performer in the 2 provided DiagnosticReport resource(s)

USCDRRN-12: All must support elements are provided in the DiagnosticReport resources returned.
US Core Responders SHALL be capable of populating all data elements as part of the query results as specified by the US Core Server Capability Statement. This will look through the DiagnosticReport resources found previously for the following must support elements:

category
code
effective[x]
encounter
issued
performer
presentedForm
status
subject
http://hl7.org/fhir/us/core/STU3.1.1/general-guidance.html#must-support

**Comment by yunwwang** [comment]
@alps8 This is very common question about MustSupport. Please take a look of this [FAQ](https://github.com/onc-healthit/inferno-program/wiki/FAQ#q-how-does-inferno-test-mustsupport-flag-on-an-element) and let me if you have further questions about MustSupport testing.

**Comment by alps8** [comment]
Thanks for the clarification and quick response.
