### ISSUE TITLE
inferno jwks keys support only key_ops and does not include use=sig

### ISSUE THREAD

**Issue by kwalshAtMeditech** [onc-healthit/inferno-program#418]
Thank you for reporting a possible bug in Inferno! Please fill in as much of the template below as you can.

**Subject of the issue**
"https://inferno.healthit.gov/inferno/.well-known/jwks.json" should contain "use": "sig". It was fixed in 1.7 by adding it to the config.yml, but it's not working with the public app. This is needed for back end authorization registration during Bulk Data tests.
https://github.com/onc-healthit/inferno-program/pull/351 - Pull request that added change
https://github.com/onc-healthit/inferno-program/issues/344 - The original issue

**Your environment**
Program Edition 1.8.2 Chrome

**Steps to reproduce**
Go to "https://inferno.healthit.gov/inferno/.well-known/jwks.json" adn observe that (use: "sig) is missing

Include:

* Multi-patient API
* (https://inferno.healthit.gov/inferno/)
* The Test ID, BDA-07: Authorization request succeeds when supplied correct information

**Expected behavior**
(use: "sig) should be present in the config.yml and jwks.json

**Actual behavior**
(use: "sig) is missing

**Comment by yunwwang** [comment]
@kwalshAtMeditech: Thank you for reporting this. It looks like we forgot to apply the change to inferno website. This has been fixed by https://github.com/onc-healthit/inferno.healthit.gov/pull/83. Can you verify the jwks having the correct value?
