### ISSUE TITLE
USCDAR-01 : Mandatory data always exists in system, so this test is getting skipped

### ISSUE THREAD

**Issue by alps8** [onc-healthit/inferno-program#419]
Thank you for reporting a possible bug in Inferno! Please fill in as much of the template below as you can.

**How to make USCDAR-01 pass, when we always have mandatory data populated in the system?**
Our system always has data populated for the mandatory fields for **non-coded** data elements. USCDAR-01 always gets skipped because of this.
We do however have DAR for some coded data elements, So USCDAR-02 passes.

As per the example in http://hl7.org/fhir/us/core/general-guidance.html#missing-data, if we somehow try to create a patient without a name (which is not really possible in our db) , USCDAR tests might pass but the USCP tests will fail.

Can you suggest a different data element for which we can return a DAR so that USCDAR-01 will pass?

**Your environment**
* Edition of inferno (Community or Program): Program
* Version of inferno: 1.8.2
* Which browser and version(s) is the bug present on?: Chrome

**Steps to reproduce**
Run USCDAR for patient having all mandatory data elements for non-coded data elements having values that are not DAR.
USCDAR-01 will be skipped

Include:

* The selected test suite : USCDAR
* The URL of the FHIR server being tested
* The Test ID, if it's a problem with a specific test. : USCDAR-01
* Any required configuration options (client ID, client secret, etc.)
* Anything else needed to make the issue occur.

**Expected behavior**
USCDAR-01 should pass when no non-coded data elements exists without a DAR.
Or provide a data element which can be used to send a DAR such that other tests do not fail.

**Actual behavior**
USCDAR-01 fails for patient when data is present for all mandatory non-coded data elements.

**Comment by alps8** [comment]
Ran the tests and I see that even USCDAR-01 fails along with some tests in USCP. Here are the details : 

**Skipped :** 

USCDAR-01: Server represents missing data with the DataAbsentReason Extension results...
No resources using the DataAbsentReason Extension have been found

USCP-03: Server returns valid results for Patient search by name. results...
Could not resolve all parameters (name) in any resource.

USCP-04: Server returns valid results for Patient search by birthdate+name. results...
Could not resolve all parameters (birthdate, name) in any resource.

USCP-05: Server returns valid results for Patient search by gender+name. results...
Could not resolve all parameters (gender, name) in any resource.

USCP-13: All must support elements are provided in the Patient resources returned. results...
Could not find name, name.family, name.given, address.city, address.postalCode, address.period in the 1 provided Patient resource(s)

**Failed :** 

USCP-12: Patient resources returned during previous tests conform to the US Core Patient Profile. results...
Patient/4ceaf66b-1764-4457-9be7-ca067c6628c7: Patient.name[0]: us-core-8: Either Patient.name.given and/or Patient.name.family SHALL be present or a Data Absent Reason Extension SHALL be present. [(family.exists() or given.exists()) xor extension.where(url = 'http://hl7.org/fhir/StructureDefinition/data-absent-reason').exists()]

```
{
  "resourceType": "Bundle",
  "id": "35492766-f6d3-4627-9677-886963c0c9d9",
  "type": "searchset",
  "total": 1,
  "link": [
    {
      "relation": "self",
      "url": "https://redacted/_snapshot?id=3a4a9390-585a-491a-a7e9-03789da9c67c&start=0"
    },
    {
      "relation": "first",
      "url": "https://redacted/_snapshot?id=3a4a9390-585a-491a-a7e9-03789da9c67c&start=0"
    },
    {
      "relation": "last",
      "url": "https://redacted/_snapshot?id=3a4a9390-585a-491a-a7e9-03789da9c67c&start=0"
    }
  ],
  "entry": [
    {
      "fullUrl": "https://redacted/Patient/4ceaf66b-1764-4457-9be7-ca067c6628c7",
      "resource": {
        "resourceType": "Patient",
        "id": "4ceaf66b-1764-4457-9be7-ca067c6628c7",
        "meta": {
          "lastUpdated": "2021-12-14T12:23:16-06:00"
        },
        "extension": [
          {
            "extension": [
              {
                "url": "text",
                "valueString": "White"
              },
              {
                "url": "ombCategory",
                "valueCoding": {
                  "system": "urn:oid:2.16.840.1.113883.6.238",
                  "code": "2106-3",
                  "display": "White"
                }
              }
            ],
            "url": "http://hl7.org/fhir/us/core/StructureDefinition/us-core-race"
          },
          {
            "extension": [
              {
                "url": "text",
                "valueString": "Not Hispanic Or Latino"
              },
              {
                "url": "ombCategory",
                "valueCoding": {
                  "system": "urn:oid:2.16.840.1.113883.6.238",
                  "code": "2186-5",
                  "display": "Not Hispanic Or Latino"
                }
              }
            ],
            "url": "http://hl7.org/fhir/us/core/StructureDefinition/us-core-ethnicity"
          },
          {
            "url": "http://hl7.org/fhir/us/core/StructureDefinition/us-core-birthsex",
            "valueCode": "UNK"
          }
        ],
        "identifier": [
          {
            "system": "https://redacted/patient/mrn",
            "value": "redacted"
          }
        ],
        "active": true,
        "name": [
          {
            "extension": [
              {
                "url": "http://terminology.hl7.org/CodeSystem/data-absent-reason",
                "valueString": "unknown"
              }
            ]
          }
        ],
        "telecom": [
          {
            "system": "phone",
            "value": "8888888888",
            "use": "home"
          }
        ],
        "gender": "female",
        "birthDate": "1980-01-01",
        "address": [
          {
            "use": "home",
            "line": [
              "123 main st"
            ],
            "state": "NY"
          },
          {
            "use": "home",
            "state": "MO"
          }
        ],
        "maritalStatus": {
          "coding": [
            {
              "system": "http://terminology.hl7.org/CodeSystem/v3-MaritalStatus",
              "code": "U"
            }
          ],
          "text": "Unknown"
        },
        "communication": [
          {
            "language": {
              "coding": [
                {
                  "system": "urn:ietf:bcp:47",
                  "code": "EN"
                }
              ],
              "text": "English"
            },
            "preferred": true
          }
        ],
        "generalPractitioner": [
          {
            "reference": "Practitioner/redacted"
          }
        ]
      }
    }
  ]
}
```

**Comment by yunwwang** [comment]
Your extension is invalid. It should be
```
{
  "url": "http://hl7.org/fhir/StructureDefinition/data-absent-reason",
  "valueCode": "unknown"
}
```

**Comment by alps8** [comment]
Yes. I had noticed and fixed the Extension. Thank you.

I have been trying to find another mandatory element that supports a DAR Extension, but havent come across one.
Can you please let me know of one that I could use?

**Comment by yunwwang** [comment]
If you stick to Patient resource, you could try use DAR for Patient.identifier, Patient.telecom.system, or Patient.telecom.value.

You can also chose using resource other than Patient, for example: CarePlan.text

**Comment by alps8** [comment]
Using a DAR for Patient.telecom like below is failing USCP-12 and skipping USCP-13. It is still expecting a system and value.

```
"telecom": [
          {
            "extension": [
              {
                "url": "http://hl7.org/fhir/StructureDefinition/data-absent-reason",
                "valueCode": "unknown"
              }
            ]
          }
        ]
```
**Skipped**
```
USCP-12: Patient resources returned during previous tests conform to the US Core Patient Profile. results...
Patient/4ceaf66b-1764-4457-9be7-ca067c6628c7: Patient.telecom[0]: Patient.telecom.system: minimum required = 1, but only found 0 (from http://hl7.org/fhir/us/core/StructureDefinition/us-core-patient)
Patient/4ceaf66b-1764-4457-9be7-ca067c6628c7: Patient.telecom[0]: Patient.telecom.value: minimum required = 1, but only found 0 (from http://hl7.org/fhir/us/core/StructureDefinition/us-core-patient)
```

**Failed**
```
USCP-13: All must support elements are provided in the Patient resources returned. results...
Could not find telecom, telecom.system, telecom.value, telecom.use in the 1 provided Patient resource(s)
```

**Comment by yunwwang** [comment]
```
{
  "telecom": [
    {
      "system": "email",
      "_value": {
        "extension": [
          {
            "url": "http://hl7.org/fhir/StructureDefinition/data-absent-reason",
            "valueCode": "unknown"
          }
        ]
      }
    }
  ]
}
```

USCP-13 failed because system does not provide a Patient with Patient.telecom.value. See the previous issue your raised about MustSupport testing.

Using DAR extension does not count in MustSupport testing.

So, you cannot use one Patient resource to satisfy both USCP-13 and USCDAR-01. 

Since you have only one Patient resource, you have to use other resource types for USCDAR-01. That is using a resource other than Patient to demonstrate your server support DAR extension.

**Comment by alps8** [comment]
Ok. That makes sense. Thank you.

**Comment by yunwwang** [comment]
@alps8 Just thought another way to demonstrate both using a single Patient resource: 
```
{
  "telecom": [
    {
      "system": "phone",
      "value": "555-123-4567"
    },
    {
      "system": "email",
      "_value": {
        "extension": [
          {
            "url": "http://hl7.org/fhir/StructureDefinition/data-absent-reason",
            "valueCode": "unknown"
          }
        ]
      }
    }
  ]
}
```

I haven't tested it yet but I think this should work.

**Comment by alps8** [comment]
Thanks @yunwwang . I had used that exact scenario to get the test USCDAR-01 to pass. 

However, I just noticed an issue with USCDAR-02. It was passing previously when I had a DAR for `Observation.dataAbsentReason`
But now it is getting skipped.

```
{
      "fullUrl": "https://redacted/Observation/673fd97a-70c2-4a74-8f10-5acfb0322014",
      "resource": {
        "resourceType": "Observation",
        "id": "673fd97a-70c2-4a74-8f10-5acfb0322014",
        "meta": {
          "lastUpdated": "2021-09-09T11:00:40-06:00"
        },
        "status": "registered",
        "category": [
          {
            "coding": [
              {
                "system": "http://terminology.hl7.org/CodeSystem/observation-category",
                "code": "laboratory",
                "display": "Laboratory"
              }
            ],
            "text": "Laboratory"
          }
        ],
        "code": {
          "text": "CBC Doc"
        },
        "subject": {
          "reference": "Patient/e39dd006-a9a9-49b6-a2f2-c3d4cadd13d8"
        },
        "effectiveDateTime": "2021-09-09T11:00:40+00:00",
        "dataAbsentReason": {
          "coding": [
            {
              "system": "http://hl7.org/fhir/StructureDefinition/data-absent-reason",
              "code": "unknown",
              "display": "Unknown"
            }
          ],
          "text": "Unknown"
        }
      }
    }
```

If that data element doesnt let the test pass, can you suggest another data element for which I can send a DAR. Unfortunately (fortunately?) for the mandatory coded-data elements under CarePlan/Condition/Observation we always have data.

**Comment by yunwwang** [comment]
First, I think there is a misunderstanding about USCDAR tests. This test sequence is to verify that server implementation support US Core [Missing Data section](http://hl7.org/fhir/us/core/STU3.1.1/general-guidance.html#missing-data). The two USCDAR tests map to the two scenarios mentioned in that section: required non-coded element (USCDAR-01) and required coded element (USCDAR-02). 

These two tests focus on server's capability instead of individual resource. That is for a server implementation, there has to be at least one resource having DAR-extension (USCDAR-01) and one resource having designated DAR code (USCDAR-02). They could be the same resource. They could be different resources. 

You can find any US Core resource types having required coded type and 'unknown' code in binding value set. One example is `CarePlan.status`

**Comment by alps8** [comment]
Having a value of `unknown` in `Careplan.status` is still skipping USCDAR-02
All USCCP tests do pass.

```
"entry": [
    {
      "fullUrl": "https://redacted/CarePlan/345c4c41-15d9-42a9-971b-d8c51b3da0b8",
      "resource": {
        "resourceType": "CarePlan",
        "id": "345c4c41-15d9-42a9-971b-d8c51b3da0b8",
        "meta": {
          "lastUpdated": "2021-12-16T17:48:18-06:00"
        },
        "text": {
          "status": "generated",
          "div": "<div xmlns=\"http://www.w3.org/1999/xhtml\">\r\n  <div>\r\n redacted </div>\r\n</div>"
        },
        "status": "unknown",
        "intent": "plan",
        "category": [
          {
            "coding": [
              {
                "system": "http://hl7.org/fhir/us/core/CodeSystem/careplan-category",
                "code": "assess-plan"
              }
            ]
          }
        ],
        "subject": {
          "reference": "Patient/4ceaf66b-1764-4457-9be7-ca067c6628c7"
        },
        "activity": [
          {
            "detail": {
              "code": {
                "coding": [............
```

**Comment by yunwwang** [comment]
My fault. USCDAR-02 tests "For coded data elements with example, preferred, or extensible binding strengths to ValueSets which do not include an appropriate “unknown” code, servers shall use the “unknown” code from the DataAbsentReason CodeSystem." 

So you need to find a **coded data elements with example, preferred, or extensible binding strengths to ValueSets which do not include an appropriate “unknown” code** and apply DAR extension when server does not have value.

**Comment by alps8** [comment]
@yunwwang Sending a DAR for the extensible value set `Device.type` is still skipping the test USCDAR-02. Please advice.

```
"entry": [
    {
      "fullUrl": "https://redacted/Device/30000014",
      "resource": {
        "resourceType": "Device",
        "id": "30000014",
        "meta": {
          "lastUpdated": "2021-12-17T17:28:09-06:00"
        },
        "udiCarrier": [
          {
            "deviceIdentifier": "redacted200",
            "carrierHRF": "redacted00"
          }
        ],
        "status": "active",
        "manufacturer": "redacted.",
        "manufactureDate": "0001-01-01",
        "expirationDate": "0001-01-01",
        "deviceName": [
          {
            "name": "Polymeric spinal interbody fusion cage",
            "type": "udi-label-name"
          }
        ],
        "modelNumber": "redacted220",
        "type": {
          "coding": [
            {
              "system": "http://hl7.org/fhir/StructureDefinition/data-absent-reason",
              "code": "unknown",
              "display": "Unknown"
            }
          ],
          "text": "Unknown"
        },
        "patient": {
          "reference": "Patient/ea006683-f411-4cce-95a5-8055a324c0c9"
        }
      }
    }
  ]
```

**Comment by yunwwang** [comment]
Your `coding.system` is wrong. That url is the StructureDefinition of DAR extension. What you need is the url for the code system.

**Comment by alps8** [comment]
Thank you! That worked.
