### ISSUE TITLE
Refresh Token request from Inferno Client is missing Authorization header information

### ISSUE THREAD

**Issue by vvvinze** [onc-healthit/inferno-program#425]
Thank you for reporting a possible bug in Inferno! Please fill in as much of the template below as you can.

**Subject of the issue**
Refresh Token request from Inferno Client is missing Authorization header information

Describe your issue here.
Refresh Token request from Inferno Client is missing Authorization header information.

![Token Refresh](https://user-images.githubusercontent.com/88528419/147198268-7fc128d1-c2ce-445b-b5f1-9b51d9daf9d4.jpg)

![Refresh Token with authorization header](https://user-images.githubusercontent.com/88528419/147198356-0649d205-c243-418d-add8-cb8a802f43db.jpg)

**The Complete Request & the Body of the TR-03 Test below:**

1 Request
   POST   200   https://fhiri221es.rd.allscripts.com/authorizationV2-ReleaseAll/connect/token
Request
Headers
•	Content-Type: application/x-www-form-urlencoded
•	Authorization: Basic MzY0Yjg4NmItNzgwNS00NzliLTlhM2MtZGM2MGRlZDk0YjNmOjc2OTFCM0JERjI0Qw==
Payload
grant_type=refresh_token&refresh_token=8ED1AD0AFEB4468433F2B585ADB8D81D56870AF46E04AED11D5B4F85E2AD80A2
Response
Headers
•	cache_control: no-store, no-cache, max-age=0
•	pragma: no-cache
•	transfer_encoding: chunked
•	content_type: application/json; charset=UTF-8
•	server: Microsoft-IIS/10.0
•	x_powered_by: ASP.NET
•	date: Mon, 20 Dec 2021 07:21:29 GMT
Body
{
  "id_token": "eyJhbGciOiJSUzI1NiIsImtpZCI6IlFPSzB1YmV2MWU5Q0VPV082NkVPbmlDaTZyMCIsInR5cCI6IkpXVCIsIng1dCI6IlFPSzB1YmV2MWU5Q0VPV082NkVPbmlDaTZyMCJ9.eyJuYmYiOjE2Mzk5ODQ4ODksImV4cCI6MTYzOTk4NTE4OSwiaXNzIjoiaHR0cHM6Ly9maGlyaTIyMWVzLnJkLmFsbHNjcmlwdHMuY29tL2F1dGhvcml6YXRpb25WMi1SZWxlYXNlQWxsIiwiYXVkIjoiMzY0Yjg4NmItNzgwNS00NzliLTlhM2MtZGM2MGRlZDk0YjNmIiwiaWF0IjoxNjM5OTg0ODg5LCJhdF9oYXNoIjoiVnlydUdjaWpHZnYxVUxUQ0ZrZURqQSIsInN1YiI6InJkXFxzaXRfc2VydmljZXMiLCJhdXRoX3RpbWUiOjE2Mzk5ODQ4NzMsImlkcCI6IkFsbHNjcmlwdHNGSElSQXV0aG9yaXphdGlvbiIsImFtciI6WyJQYXNzd29yZCJdfQ.pKHPEybJ9q9qmWlNdL9EMHaQ7smL3Pdm2E_vF4qd7auNMnSdZlqUUnyGdv3yT4SV9f_n6vc0hDeS33oyUP9jxbDc3puEPx2CpJWfHBsBgViuVPeTEPw63NZoQNDXwN5Gn6KlXUksS9M96h5OZ8SNFCzzEfvqV-rcmchvFW_k5aBGXIFgZt82u6ON9tOfLdeNQJEp9D7wYWxWzpetdbeczarBPTCZHUSy45BZS8KkyNIWzcBSh-RfdqR9VAHE0MgA4tfYaY_ONRVYHATAEbrwISEXTb3uQu2yHkRFM-_sEgIYprBmY5tGTP_XnPN3x3KR20RuzBVyhfyCMC23xNUR3qh9DKHZePDIgDnTSlynMlHA6I2QspNJdX2Wb_Pxsm8SGaZd5XPywccRmOfy-a9jopEUtIx_x1hntUwPdqMoOwCmmwPuEeQfe5Pxt44NnbvUHdHrsJT79mjyQOUilvJ52TnLdk4SRQ7coD2d7nss6WXkz4lC_144aeq9xwfKjCvKhW_G2j-ztWIXM29Vq8-KqyPYqUTB-4oWTlKPUh9fUP-cEA1VS6tj3kCjwSFZp52sOgFfOCpoAxJJiT7iQ6Z-c3e8huIJo-pjmn86qTifkO4lsoAKprNVRPsPzVXZx2oEgm7lfF_c4x-GJ-aEm346E71RbdtGCnHP-BeCwi1e4UM",
  "access_token": "6CC089FEF431EA4B848074289A902AF5D118A5B97EDA32478B21BEDAA9CC8F53",
  "expires_in": 1200,
  "token_type": "Bearer",
  "refresh_token": "003E65FA89DE497E6B7584A57FB18F8838C87148AA8599AC1D1A5E3864E88A37",
  "scope": "launch/patient openid patient/*.read offline_access"

Other Screenshots:

![Access token start time](https://user-images.githubusercontent.com/88528419/147198566-21818c9e-ed34-4fa5-b5cd-bf94e15b9546.jpg)

![Refresh token Post Request_Authorisation header missing](https://user-images.githubusercontent.com/88528419/147198582-2815bd68-2c79-4af7-83e0-e6bc4a6354de.jpg)

**Your environment**
* Edition of inferno (Community or Program): Program
* Version of inferno: 1_8_0
* Which browser and version(s) is the bug present on?: Chrome 96.0.4664.45 / MS EDGE 96.0.1054.34

**Steps to reproduce**
Tell us how to reproduce this issue.

1. After retrieving the Token, select Single Patient API and enter the Patient ID of 2287500200 and run all tests.
2. Go to the 'Single Patient API' tab and open the report for 'Observation Blood Pressure Tests'. 
3. Check the header information in the POST request.

Include:

* The selected test suite
* The URL of the FHIR server being tested
* The Test ID, if it's a problem with a specific test.
* Any required configuration options (client ID, client secret, etc.)
* Anything else needed to make the issue occur.

**Expected behavior**
Tell us what should happen.

Authorization information should be displayed in the header of the POST request

**Actual behavior**
Tell us what happens instead. Include screenshots if possible.
Authorization information is not displayed in the header of the POST request.

**Comment by vvvinze** [comment]
> * Community

Program

**Comment by yunwwang** [comment]
Hello @vvvinze : I tried to reproduce that on https://inferno.healthit.gov/inferno but the token refreshed correctly after waiting for 1 hour (token expires after 3600 seconds). Did you get the error on Inferno web or your local installation? Could you provide more detail on how to reproduce that? Thanks

**Comment by vvvinze** [comment]
Hi @yunwwang: Currently we are seeing failures for SPD-TR-03. Once we are through this, we can check the inferno report. However we would like to see the logs. Can you please share the location from where we can check inferno logs?

**Comment by yunwwang** [comment]
Are you running test locally or on inferno.healthit.gov?

**Comment by Amit707K** [comment]
@yunwwang - We're running the test locally. Could you please share the location from where we can get the Inferno Logs?

**Comment by Amit707K** [comment]
@yunwwang - Detailed Steps to Reproduce for the above case:

Step.1
On the location installation VM where Inferno tool is running(Inferno tool Program edition version 1_8_0):

Step.2
Launch the Docker Container service for Inferno

Step.3
Open the browser from Inferno-program-180p-nginx within docker Container

Step.4
From the Inferno program edition Test screen, provide the fhir endpoint

Step.5
Click on start testing

Step.6
In the standalone Patient Tab > Click on Run Tests

Step.7
Provide the fhir end point, client ID, client secret, standalone patient scope(launch/patient openid offline_access patient/*.read)

Step.8
Click on Execute

Step.9
Wait for test progress on  
STANDALONE PATIENT APP - FULL PATIENT ACCESS > "SMART On FHIR Discovery" Tests

Step.10
Wait for the "Token Refresh" Tests to be completed

Step.11
Look for the Authorization header information for SPD-TR-03
screenshot

Step.12
Wait for the "SMART On FHIR Discovery" Tests to be completed

Step.13
Click Single Patient API Tab

Step.14
Click on Run Tests

Step.15
Provide the Patient ID

Step.16
Click on Execute

Step.17
Wait for the Single Patient API tests to be completed

Step.18
Review the Single Patient API Test results

Step.19
Review the Resources that have Failed with Error 401

Step.20
Starting with the first failed resource with 401 error, verify if total test time is past 20 minutes Step.6 above

Step.21
In the first failed resource > Click on Results > Look for the URL:
POST   400   https://fhiri221es.rd.allscripts.com/authorizationV2-ReleaseAll/connect/token

Step.22
Verify if the Authorization header information is passed in the refresh token request.

Note-
On the inferno VM is there any logs for this Test Run that you think we can look up & send it to you for review. Please share the location.

**Comment by akkillewale** [comment]
> Hello @vvvinze : I tried to reproduce that on https://inferno.healthit.gov/inferno but the token refreshed correctly after waiting for 1 hour (token expires after 3600 seconds). Did you get the error on Inferno web or your local installation? Could you provide more detail on how to reproduce that? Thanks

Can you please clarify if Inferno refreshes the token based on access token expiration or if it will only refresh after 1 hour? Our access token has expiration set for 1200 seconds.

**Comment by yunwwang** [comment]
Yes. Inferno refreshes token when needed. Here is code segment in fhir_client:


```
    def refresh_token_if_needed
      return if testing_instance&.refresh_token.blank?

      perform_refresh if time_to_refresh?
    end

    def time_to_refresh?
      return true if testing_instance.token_expires_in.blank?

      testing_instance.token_expiration_time.to_i - DateTime.now.to_i < 60
    end

    def perform_refresh
      oauth2_params = {
        'grant_type' => 'refresh_token',
        'refresh_token' => testing_instance.refresh_token
      }
      ...
```


https://github.com/onc-healthit/inferno-program/blob/6b8d4785f06c77cd45b47de238dc27cb6d00b7ba/lib/app/ext/fhir_client.rb#L41

**Comment by akkillewale** [comment]
Thanks for the response. Please mark this issue as closed, we will take it up internally.

**Comment by yunwwang** [comment]
Closed as requested
