### ISSUE TITLE
BDE-02: Bulk Data Server declares support for Group export operation in CapabilityStatement

### ISSUE THREAD

**Issue by deepaktiwari29** [onc-healthit/inferno-program#427]
**Description**
BDE-02 test fails saying 'Server CapabilityStatement did not declare support for export operation in Group resource.'
![image](https://user-images.githubusercontent.com/74093656/148924515-577d61b7-5f57-45af-97b2-77eb4a0f9fe9.png)

We have declared support for group-export in both resource specific operation as well as in system level operation as below:

![image](https://user-images.githubusercontent.com/74093656/148925244-fa553c82-5800-4ea6-996a-f68dd1215f74.png)

![image](https://user-images.githubusercontent.com/74093656/148925716-adee81f6-150c-4f66-b744-c238bac580e9.png)

**Environment**
* Edition of inferno (Community or Program): Program
* Version of inferno: 1.8.2
* Which browser and version(s) is the bug present on?: Chrome Version 96.0.4664.110 (Official Build) (64-bit)

**Steps to reproduce**
Tell us how to reproduce this issue.

- Launch inferno program edition 1.8.2
- Run the test under Multi-Patient API

Include:

* The selected test suite:  Multi-Patient API
* The URL of the FHIR server being tested
* The Test ID, if it's a problem with a specific test: BDE-02
* Any required configuration options (client ID, client secret, etc.): NA

**Expected behavior**
Test should pass.

**Actual behavior**
It's failing with error " Server CapabilityStatement did not declare support for export operation in Group resource."

**Comment by yunwwang** [comment]
Hello @deepaktiwari29 The operation.definition shall be the canonical url "http://hl7.org/fhir/uv/bulkdata/OperationDefinition/group-export"

**Comment by deepaktiwari29** [comment]
Hello @yunwwang , the above url is resolves as :
"http://hl7.org/fhir/uv/bulkdata/STU2/OperationDefinition-group-export.html"
Is there any R4 specific URL??

**Comment by yunwwang** [comment]
STU2 is the latest of Bulk Data IG. 
You shall use the canonical url defined in the operation's OperationDefinition, not the web page.
