### ISSUE TITLE
Error starting docker image

### ISSUE THREAD

**Issue by javacup** [onc-healthit/inferno-program#429]
I pulled the latest from git.. and ran docker-compose up --build

I'm getting the following error 
" bundler: failed to load command: rackup (/usr/local/bundle/bin/rackup)"

please see the full stacktrace below

Building inferno
[+] Building 1.1s (21/21) FINISHED                                                                                                                                                                   
 => [internal] load build definition from Dockerfile                                                                                                                                            0.0s
 => => transferring dockerfile: 37B                                                                                                                                                             0.0s
 => [internal] load .dockerignore                                                                                                                                                               0.0s
 => => transferring context: 35B                                                                                                                                                                0.0s
 => [internal] load metadata for docker.io/library/ruby:2.7.2                                                                                                                                   0.9s
 => [ 1/16] FROM docker.io/library/ruby:2.7.2@sha256:1dd0106849233fcd913b7c4608078fa1a53a5e3ce1af2a55e4d726b0d8868e2f                                                                           0.0s
 => [internal] load build context                                                                                                                                                               0.0s
 => => transferring context: 51.00kB                                                                                                                                                            0.0s
 => CACHED [ 2/16] WORKDIR /var/www/inferno                                                                                                                                                     0.0s
 => CACHED [ 3/16] COPY Gemfile.postgres /var/www/inferno/Gemfile                                                                                                                               0.0s
 => CACHED [ 4/16] COPY Gemfile.postgres.lock /var/www/inferno/Gemfile.lock                                                                                                                     0.0s
 => CACHED [ 5/16] RUN gem install bundler                                                                                                                                                      0.0s
 => CACHED [ 6/16] RUN bundle config --global frozen 1                                                                                                                                          0.0s
 => CACHED [ 7/16] RUN bundle install                                                                                                                                                           0.0s
 => CACHED [ 8/16] RUN mkdir data                                                                                                                                                               0.0s
 => CACHED [ 9/16] COPY public /var/www/inferno/public                                                                                                                                          0.0s
 => CACHED [10/16] COPY resources /var/www/inferno/resources                                                                                                                                    0.0s
 => CACHED [11/16] COPY config* /var/www/inferno/                                                                                                                                               0.0s
 => CACHED [12/16] COPY Rakefile /var/www/inferno/                                                                                                                                              0.0s
 => CACHED [13/16] COPY test /var/www/inferno/test                                                                                                                                              0.0s
 => CACHED [14/16] COPY lib /var/www/inferno/lib                                                                                                                                                0.0s
 => CACHED [15/16] COPY db /var/www/inferno/db                                                                                                                                                  0.0s
 => CACHED [16/16] COPY bin /var/www/inferno/bin                                                                                                                                                0.0s
 => exporting to image                                                                                                                                                                          0.0s
 => => exporting layers                                                                                                                                                                         0.0s
 => => writing image sha256:5b34239e4319e6797fa295415e5fa991d242f49a9e7c12859c17bd3bec6366a9                                                                                                    0.0s
 => => naming to docker.io/library/inferno-program_inferno                                                                                                                                      0.0s

Use 'docker scan' to run Snyk tests against images to find vulnerabilities and learn how to fix them
inferno-program_validator_service_1 is up-to-date
Starting inferno-program_inferno_1 ... done
inferno-program_nginx_1 is up-to-date
Attaching to inferno-program_validator_service_1, inferno-program_inferno_1, inferno-program_nginx_1
validator_service_1  | 2022-01-14 16:37:40 INFO  App:61 - Starting Server...
validator_service_1  | 2022-01-14 16:37:40 INFO  log:193 - Logging initialized @280ms to org.eclipse.jetty.util.log.Slf4jLog
validator_service_1  |   Load /home/./igs/hl7.fhir.us.core-3.1.1.tgz - 146 resources (00:04.0845)
validator_service_1  | 2022-01-14 16:37:45 INFO  EmbeddedJettyServer:142 - == Spark has ignited ...
validator_service_1  | 2022-01-14 16:37:45 INFO  EmbeddedJettyServer:146 - >> Listening on 0.0.0.0:4567
validator_service_1  | 2022-01-14 16:37:45 INFO  Server:370 - jetty-9.4.18.v20190429; built: 2019-04-29T20:42:08.989Z; git: e1bc35120a6617ee3df052294e433f3a25ce7097; jvm 11.0.13+8
validator_service_1  | 2022-01-14 16:37:45 INFO  session:365 - DefaultSessionIdManager workerName=node0
validator_service_1  | 2022-01-14 16:37:45 INFO  session:370 - No SessionScavenger set, using defaults
validator_service_1  | 2022-01-14 16:37:45 INFO  session:149 - node0 Scavenging every 660000ms
validator_service_1  | 2022-01-14 16:37:45 INFO  AbstractConnector:292 - Started ServerConnector@56bf2873{HTTP/1.1,[http/1.1]}{0.0.0.0:4567}
validator_service_1  | 2022-01-14 16:37:45 INFO  Server:410 - Started @5620ms
nginx_1              | /docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
nginx_1              | /docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
nginx_1              | /docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
nginx_1              | 10-listen-on-ipv6-by-default.sh: info: Getting the checksum of /etc/nginx/conf.d/default.conf
nginx_1              | 10-listen-on-ipv6-by-default.sh: info: Enabled listen on IPv6 in /etc/nginx/conf.d/default.conf
nginx_1              | /docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
nginx_1              | /docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
nginx_1              | /docker-entrypoint.sh: Configuration complete; ready for start up
nginx_1              | 2022/01/14 16:38:52 [error] 32#32: *1 connect() failed (113: No route to host) while connecting to upstream, client: 172.19.0.1, server: inferno.oauth2.io, request: "GET /inferno HTTP/1.1", upstream: "http://172.19.0.3:4567/inferno", host: "localhost:4567"
nginx_1              | 2022/01/14 16:38:55 [error] 32#32: *1 connect() failed (113: No route to host) while connecting to upstream, client: 172.19.0.1, server: inferno.oauth2.io, request: "GET /favicon.ico HTTP/1.1", upstream: "http://172.19.0.3:4567/favicon.ico", host: "localhost:4567", referrer: "http://localhost:4567/inferno"
inferno_1            | INFO | Inferno | Environment: production
inferno_1            | rake aborted!
inferno_1            | EOFError: end of buffer reached
inferno_1            | /usr/local/bundle/gems/msgpack-1.3.3/lib/msgpack/factory.rb:70:in `full_unpack'
inferno_1            | /usr/local/bundle/gems/msgpack-1.3.3/lib/msgpack/factory.rb:70:in `load'
inferno_1            | /usr/local/bundle/gems/bloomer-1.0.0/lib/bloomer/msgpackable.rb:14:in `from_msgpack'
inferno_1            | /var/www/inferno/lib/app/utils/terminology.rb:277:in `block in load_validators'
inferno_1            | /var/www/inferno/lib/app/utils/terminology.rb:276:in `each'
inferno_1            | /var/www/inferno/lib/app/utils/terminology.rb:276:in `load_validators'
inferno_1            | /var/www/inferno/lib/app/sequence_base.rb:25:in `<module:Sequence>'
inferno_1            | /var/www/inferno/lib/app/sequence_base.rb:24:in `<module:Inferno>'
inferno_1            | /var/www/inferno/lib/app/sequence_base.rb:23:in `<top (required)>'
inferno_1            | /var/www/inferno/lib/app.rb:25:in `require_relative'
inferno_1            | /var/www/inferno/lib/app.rb:25:in `<top (required)>'
inferno_1            | /var/www/inferno/lib/tasks/tasks.rake:12:in `require_relative'
inferno_1            | /var/www/inferno/lib/tasks/tasks.rake:12:in `<top (required)>'
inferno_1            | /usr/local/bundle/gems/activesupport-5.2.6/lib/active_support/dependencies.rb:285:in `load'
inferno_1            | /usr/local/bundle/gems/activesupport-5.2.6/lib/active_support/dependencies.rb:285:in `block in load'
inferno_1            | /usr/local/bundle/gems/activesupport-5.2.6/lib/active_support/dependencies.rb:257:in `load_dependency'
inferno_1            | /usr/local/bundle/gems/activesupport-5.2.6/lib/active_support/dependencies.rb:285:in `load'
inferno_1            | /usr/local/bundle/gems/railties-5.2.6/lib/rails/engine.rb:656:in `block in run_tasks_blocks'
inferno_1            | /usr/local/bundle/gems/railties-5.2.6/lib/rails/engine.rb:656:in `each'
inferno_1            | /usr/local/bundle/gems/railties-5.2.6/lib/rails/engine.rb:656:in `run_tasks_blocks'
inferno_1            | /usr/local/bundle/gems/railties-5.2.6/lib/rails/application.rb:515:in `run_tasks_blocks'
inferno_1            | /usr/local/bundle/gems/railties-5.2.6/lib/rails/engine.rb:459:in `load_tasks'
inferno_1            | /usr/local/bundle/gems/railties-5.2.6/lib/rails/railtie.rb:190:in `public_send'
inferno_1            | /usr/local/bundle/gems/railties-5.2.6/lib/rails/railtie.rb:190:in `method_missing'
inferno_1            | /usr/local/bundle/gems/standalone_migrations-6.0.0/lib/standalone_migrations/tasks.rb:14:in `load_tasks'
inferno_1            | /var/www/inferno/Rakefile:7:in `<top (required)>'
inferno_1            | /usr/local/bundle/gems/rake-13.0.6/exe/rake:27:in `<top (required)>'
inferno_1            | /usr/local/bundle/gems/bundler-2.2.33/lib/bundler/cli/exec.rb:58:in `load'
inferno_1            | /usr/local/bundle/gems/bundler-2.2.33/lib/bundler/cli/exec.rb:58:in `kernel_load'
inferno_1            | /usr/local/bundle/gems/bundler-2.2.33/lib/bundler/cli/exec.rb:23:in `run'
inferno_1            | /usr/local/bundle/gems/bundler-2.2.33/lib/bundler/cli.rb:479:in `exec'
inferno_1            | /usr/local/bundle/gems/bundler-2.2.33/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
inferno_1            | /usr/local/bundle/gems/bundler-2.2.33/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
inferno_1            | /usr/local/bundle/gems/bundler-2.2.33/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
inferno_1            | /usr/local/bundle/gems/bundler-2.2.33/lib/bundler/cli.rb:31:in `dispatch'
inferno_1            | /usr/local/bundle/gems/bundler-2.2.33/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
inferno_1            | /usr/local/bundle/gems/bundler-2.2.33/lib/bundler/cli.rb:25:in `start'
inferno_1            | /usr/local/bundle/gems/bundler-2.2.33/exe/bundle:49:in `block in <top (required)>'
inferno_1            | /usr/local/bundle/gems/bundler-2.2.33/lib/bundler/friendly_errors.rb:103:in `with_friendly_errors'
inferno_1            | /usr/local/bundle/gems/bundler-2.2.33/exe/bundle:37:in `<top (required)>'
inferno_1            | /usr/local/bundle/bin/bundle:23:in `load'
inferno_1            | /usr/local/bundle/bin/bundle:23:in `<main>'
inferno_1            | (See full trace by running task with --trace)
inferno_1            | Parsing options from the first comment line is deprecated!
inferno_1            | INFO | Inferno | Environment: production
inferno_1            | bundler: failed to load command: rackup (/usr/local/bundle/bin/rackup)
inferno_1            | /usr/local/bundle/gems/msgpack-1.3.3/lib/msgpack/factory.rb:70:in `full_unpack': end of buffer reached (EOFError)
inferno_1            | 	from /usr/local/bundle/gems/msgpack-1.3.3/lib/msgpack/factory.rb:70:in `load'
inferno_1            | 	from /usr/local/bundle/gems/bloomer-1.0.0/lib/bloomer/msgpackable.rb:14:in `from_msgpack'
inferno_1            | 	from /var/www/inferno/lib/app/utils/terminology.rb:277:in `block in load_validators'
inferno_1            | 	from /var/www/inferno/lib/app/utils/terminology.rb:276:in `each'
inferno_1            | 	from /var/www/inferno/lib/app/utils/terminology.rb:276:in `load_validators'
inferno_1            | 	from /var/www/inferno/lib/app/sequence_base.rb:25:in `<module:Sequence>'
inferno_1            | 	from /var/www/inferno/lib/app/sequence_base.rb:24:in `<module:Inferno>'
inferno_1            | 	from /var/www/inferno/lib/app/sequence_base.rb:23:in `<top (required)>'
inferno_1            | 	from /var/www/inferno/lib/app.rb:25:in `require_relative'
inferno_1            | 	from /var/www/inferno/lib/app.rb:25:in `<top (required)>'
inferno_1            | 	from /var/www/inferno/config.ru:4:in `require'
inferno_1            | 	from /var/www/inferno/config.ru:4:in `block in <main>'
inferno_1            | 	from /usr/local/bundle/gems/rack-2.2.3/lib/rack/builder.rb:116:in `eval'
inferno_1            | 	from /usr/local/bundle/gems/rack-2.2.3/lib/rack/builder.rb:116:in `new_from_string'
inferno_1            | 	from /usr/local/bundle/gems/rack-2.2.3/lib/rack/builder.rb:105:in `load_file'
inferno_1            | 	from /usr/local/bundle/gems/rack-2.2.3/lib/rack/builder.rb:66:in `parse_file'
inferno_1            | 	from /usr/local/bundle/gems/rack-2.2.3/lib/rack/server.rb:349:in `build_app_and_options_from_config'
inferno_1            | 	from /usr/local/bundle/gems/rack-2.2.3/lib/rack/server.rb:249:in `app'
inferno_1            | 	from /usr/local/bundle/gems/rack-2.2.3/lib/rack/server.rb:422:in `wrapped_app'
inferno_1            | 	from /usr/local/bundle/gems/rack-2.2.3/lib/rack/server.rb:312:in `block in start'
inferno_1            | 	from /usr/local/bundle/gems/rack-2.2.3/lib/rack/server.rb:379:in `handle_profiling'
inferno_1            | 	from /usr/local/bundle/gems/rack-2.2.3/lib/rack/server.rb:311:in `start'
inferno_1            | 	from /usr/local/bundle/gems/rack-2.2.3/lib/rack/server.rb:168:in `start'
inferno_1            | 	from /usr/local/bundle/gems/rack-2.2.3/bin/rackup:5:in `<top (required)>'
inferno_1            | 	from /usr/local/bundle/bin/rackup:23:in `load'
inferno_1            | 	from /usr/local/bundle/bin/rackup:23:in `<top (required)>'
inferno_1            | 	from /usr/local/bundle/gems/bundler-2.2.33/lib/bundler/cli/exec.rb:58:in `load'
inferno_1            | 	from /usr/local/bundle/gems/bundler-2.2.33/lib/bundler/cli/exec.rb:58:in `kernel_load'
inferno_1            | 	from /usr/local/bundle/gems/bundler-2.2.33/lib/bundler/cli/exec.rb:23:in `run'
inferno_1            | 	from /usr/local/bundle/gems/bundler-2.2.33/lib/bundler/cli.rb:479:in `exec'
inferno_1            | 	from /usr/local/bundle/gems/bundler-2.2.33/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
inferno_1            | 	from /usr/local/bundle/gems/bundler-2.2.33/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
inferno_1            | 	from /usr/local/bundle/gems/bundler-2.2.33/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
inferno_1            | 	from /usr/local/bundle/gems/bundler-2.2.33/lib/bundler/cli.rb:31:in `dispatch'
inferno_1            | 	from /usr/local/bundle/gems/bundler-2.2.33/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
inferno_1            | 	from /usr/local/bundle/gems/bundler-2.2.33/lib/bundler/cli.rb:25:in `start'
inferno_1            | 	from /usr/local/bundle/gems/bundler-2.2.33/exe/bundle:49:in `block in <top (required)>'
inferno_1            | 	from /usr/local/bundle/gems/bundler-2.2.33/lib/bundler/friendly_errors.rb:103:in `with_friendly_errors'
inferno_1            | 	from /usr/local/bundle/gems/bundler-2.2.33/exe/bundle:37:in `<top (required)>'
inferno_1            | 	from /usr/local/bundle/bin/bundle:23:in `load'
inferno_1            | 	from /usr/local/bundle/bin/bundle:23:in `<main>'

**Comment by yunwwang** [comment]
Hi, which Inferno Program version is this?

**Comment by javacup** [comment]
Hi, Thank you for the response. Where can I find the version? In the readme file I see this 
Inferno Program Edition

**Comment by javacup** [comment]
In lib/version.rb I see 1.8.2

module Inferno

VERSION = '1.8.2'

end

**Comment by javacup** [comment]
Never mind..  I'm rebuilding my docker image from scratch..
