### ISSUE TITLE
Update Inferno Reference Validation for US Core (FI-1418)

### ISSUE THREAD

**Issue by cooperthompson** [onc-healthit/inferno-program#431]
**Subject of the issue**

- Inferno initially tried resolving and validating all references (I think)
- With the fix to Issue#330, that was reduced to only references to resources the client was authorized for.
- There is ongoing work to further limit this to only Must Support US Core resources.

This work was described in the January 2022 Tech Talk ([slides](https://groups.google.com/g/inferno-testing/c/w7PiUBxw7lQ)).  

@yunwwang  [indicated ](https://chat.fhir.org/#narrow/stream/179309-inferno/topic/Post.201.2E9.20planned.20changes)that there is an internal Jira, but there was a public github issue tracking this change.

This issue is just meant to publicly track already planned work.

**Comment by yunwwang** [comment]
Pull Request: https://github.com/inferno-framework/us-core-test-kit/pull/12

**Comment by yunwwang** [comment]
This issue is fixed in ONC Certification (g)(10) Test Kit v2.1.0
