### ISSUE TITLE
OSLSP-0X: Support PKCE for testing public client standalone launch

### ISSUE THREAD

**Issue by bforbis** [onc-healthit/inferno-program#432]
We've opened a case with ONC and they have responded that Inferno would be modified to support PKCE in a future release.

> John Bender: Thanks for the inquiry. Support for Proof Key for Code Exchange (PKCE) will be added as an option in Inferno for certification testing to 45 CFR 170.315(g)(10) for both public and confidential client interactions. We expect PKCE to be supported in Inferno during the first quarter of 2022.

**Comment by yunwwang** [comment]
This issue is address in Inferno v2 smart-app-launch-test-kit: https://github.com/inferno-framework/smart-app-launch-test-kit/pull/4

**Comment by yunwwang** [comment]
reopen as duplicate v2 issue created
