### ISSUE TITLE
Broken links on http://www.hl7.org/fhir/smart-app-launch/conformance/#using-well-known (FI-1408)

### ISSUE THREAD

**Issue by horner** [onc-healthit/inferno-program#433]
<img width="1075" alt="Screen Shot 2022-02-03 at 3 07 58 PM" src="https://user-images.githubusercontent.com/6094599/152420694-19258b83-0db5-40da-a102-0b53b2668b6a.png">
<img width="1074" alt="Screen Shot 2022-02-03 at 3 08 07 PM" src="https://user-images.githubusercontent.com/6094599/152420702-442b1b58-979c-4096-8261-c93e5b82df70.png">

**Comment by horner** [comment]
@yunwwang Sounds good!  Thanks!

**Comment by yunwwang** [comment]
Pull Request: https://github.com/inferno-framework/onc-certification-g10-test-kit/pull/24

**Comment by yunwwang** [comment]
PR: https://github.com/onc-healthit/onc-certification-g10-test-kit/pull/24
