### ISSUE TITLE
USCDR-05 Fails when category = unknown (data-absent-reason)

### ISSUE THREAD

**Issue by bh021790** [onc-healthit/inferno-program#435]
Thank you for reporting a possible bug in Inferno! Please fill in as much of the template below as you can.

**Subject of the issue**
This may be more of a question: Should data-absent-reason codes be included as supported search parameters for a given element?

Currently we have a test patient with a document that we populate with an 'unknown' DAR code since it is not populated. So when the earlier Inferno tests search by patient, the subsequent test then makes an attempt to search for that patient+category=unknown; DocumentReference?category=unknown&patient=12742542

I'm wondering if this is something we just need to enhance our APIs to support or if Inferno should really be testing these scenarios. Not sure if this was an intended workflow based on the US Core profiles (but can also see the value in us supportingif we need to)

**Your environment**
* Edition of inferno (Community or Program): ONC program
* Version of inferno: 1.9.0
* Which browser and version(s) is the bug present on?: Chrome

**Steps to reproduce**
Tell us how to reproduce this issue.

Include:

* The selected test suite
ONC Program

* The URL of the FHIR server being tested
https://fhir-open.cerner.com/r4/ec2458f2-1e24-41c8-b71b-0e701af7583d/

* The Test ID, if it's a problem with a specific test.
USCDR-05

* Any required configuration options (client ID, client secret, etc.) NA

* Anything else needed to make the issue occur.
Patient ID: 12742542
https://fhir-open.cerner.com/r4/ec2458f2-1e24-41c8-b71b-0e701af7583d/DocumentReference?category=unknown&patient=12742542

**Expected behavior**
This is more of my question: should we be supporting a search by a DAR code? And should Inferno test for this?

**Actual behavior**
We do not support this today but Inferno tests for it.

**Comment by yunwwang** [comment]
My preference is that when server support DAR binding for an element, then server should support searching with DAR code. This is the same as using local coding. Assume a server supports local code "my-category" in additional to code "clinical-note". Server need to support searching with "my-category". Otherwise, client could not get resources with that category. DAR code, technically, falls into the same "extensive" codes beyond what specified in valueset.

**Comment by bh021790** [comment]
You convinced me :) thanks for the guidance! Feel free to close!
