### ISSUE TITLE
Support embedded IE document mode compatibility (FI-1453)

### ISSUE THREAD

**Issue by kolkheang** [onc-healthit/inferno-program#437]
**Is your feature request related to a problem? Please describe it.**
The embedded Internet Explorer [control](https://docs.microsoft.com/en-us/previous-versions/windows/internet-explorer/ie-developer/platform-apis/aa752127(v=vs.85)?redirectedfrom=MSDN) that we're using renders web page using document mode with IE7 mode by default (even if IE11 is installed). Without this meta tag `X-UA-Compatible` included on the web page, it will not be rendered using the highest document mode of the browser IE11 which leads to JavaScript errors and content not rendered properly.

Resources:
- https://docs.microsoft.com/en-us/openspecs/ie_standards/ms-iedoco/d3fffb13-31cc-4dd0-b38c-2b6aaabc153e
- https://docs.microsoft.com/en-us/openspecs/ie_standards/ms-iedoco/380e2488-f5eb-4457-a07a-0cb1b6e4b4b5

**Describe the solution you'd like to see implemented**
Add this meta tag to [this page](https://github.com/onc-healthit/inferno-program/blob/main/lib/app/views/layout.erb#L4), as the first tag in the `<head>` section.

```<meta http-equiv="X-UA-Compatible" content="IE=edge">```

**Describe alternatives you've considered**
Based on this [Microsoft doc](https://docs.microsoft.com/en-us/openspecs/ie_standards/ms-iedoco/380e2488-f5eb-4457-a07a-0cb1b6e4b4b5), it is also possible to set this `X-UA-Compatible` as a header in the response.

**Comment by kolkheang** [comment]
Hi @yunwwang - the workaround opens a standalone IE browser. The app that we have is a Windows app that uses an embedded IE browser.

The tag above will render the app in a document mode so that this app can be launched and rendered properly embedded.

What's your concern? Within IE dev tools, there is a tab for testing compatibility. You can test out the change using that tool by setting to document mode and IE=edge to see how the page is rendered.

**Comment by yunwwang** [comment]
@kolkheang Just wondering if the work around could help.

**Comment by kolkheang** [comment]
Thanks @yunwwang . The work around helps but the experience is disjointed and requires manual steps. It would be awesome to have this app works inside of an EHR, embedded.

Do you have a timeline of when v2 will be available?

**Comment by arscan** [comment]
I merged in this PR because it is a very superficial change and could help people running v1.9 locally.  But we are not planning on any more official releases on 1.x if possible, and strongly encourage using v2.x at https://github.com/onc-healthit/onc-certification-g10-test-kit.  Have you tried that out version yet to see if the same problem occurs for you there?
