### ISSUE TITLE
Inferno 2.0 Install - Vocabulary builder fail

### ISSUE THREAD

**Issue by jpdow01** [onc-healthit/inferno-program#446]
Thank you for reporting a possible bug in Inferno! Please fill in as much of the template below as you can.

**Subject of the issue**
Inferno 2.0 Install - Vocabulary builder fail

**Your environment**

Window 10
* Edition of inferno (Community or Program): ONC g10
* Version of inferno: 2.0
* Which browser and version(s) is the bug present on?:  N/A

**Steps to reproduce**

Using GIT Bash with 'docker-compose -f terminology_compose.yml up' command.  Get error message shown below.

**Actual behavior**
Starting onc-certification-g10-test-kit_terminology_builder_1 ... done
compose.parallel.feed_queue: Pending: set()
compose.parallel.parallel_execute_iter: Finished processing: <Service: terminology_builder>
compose.parallel.feed_queue: Pending: set()
compose.cli.verbose_proxy.proxy_callable: docker events <- (filters={'label': ['com.docker.compose.project=onc-certification-g10-test-kit', 'com.docker.compose.oneoff=False']}, decode=True)
Attaching to onc-certification-g10-test-kit_terminology_builder_1
terminology_builder_1  | standard_init_linux.go:228: exec user process caused: no such file or directory
compose.cli.verbose_proxy.proxy_callable: docker events -> <docker.types.daemon.CancellableStream object at 0x0000011789D623D0>
compose.cli.verbose_proxy.proxy_callable: docker wait <- ('1f97b36a18850189c82909dcea7f35e34bbd80df639990c5f54fe594cc2337e3')
compose.cli.verbose_proxy.proxy_callable: docker inspect_container <- ('1f97b36a18850189c82909dcea7f35e34bbd80df639990c5f54fe594cc2337e3')
compose.cli.verbose_proxy.proxy_callable: docker wait -> {'Error': None, 'StatusCode': 1}
onc-certification-g10-test-kit_terminology_builder_1 exited with code 1
compose.cli.verbose_proxy.proxy_callable: docker inspect_container -> {'AppArmorProfile': '',
 'Args': [],

**Comment by Jammjammjamm** [comment]
You should remove your UMLS API key from this post.

I don't know anything about git bash. Have you tried running it in WSL?

**Comment by jpdow01** [comment]
Thanks for the heads up about my having the API KEY in there!

I will give WSL a try!

-Jim

[https://d23fetfglg1ija.cloudfront.net/signature_fields/5cf81143e8b0ad347158c34c/DGLogoFullColor1559831400.png]<http://www.drummondgroup.com/>
  Jim Dow
  Interoperability Consultant, Advisory Services
   T  360.768.2044
   E  ***@***.******@***.***>
   W drummondgroup.com<http://www.drummondgroup.com/>

**Comment by arscan** [comment]
I'm going to close this because there haven't been any updates in 3 weeks.  Please let us know if you are still having trouble building the terminology.  And since we have migrated repositories for v2.x of Inferno, please use that other repository to record issues: https://github.com/onc-healthit/onc-certification-g10-test-kit

Thanks!
