### ISSUE TITLE
Inferno Web Test is down

### ISSUE THREAD

**Issue by Gauravu** [onc-healthit/inferno-program#459]
Thank you for reporting a possible bug in Inferno! Please fill in as much of the template below as you can.

**Inferno Web Test is down**
We are unable to run the ONC Certification (g)(10) Standardized API test from the web browser .

**Your environment**: Test
* Edition of inferno (Community or Program): Community
* Version of inferno:  2.0
* Which browser and version(s) is the bug present on?: Chrome

**Steps to reproduce**
Launch the URL https://inferno.healthit.gov/suites/g10_certification in the browser 
Click on the Select Option button

**Expected behavior**
Test Suite should be displayed

**Actual behavior**
We see nothing happening and end up getting a 502 Bad Gateway error

**Comment by yunwwang** [comment]
We rebooted the server. It is back to normal now.

Sorry about the inconvenience.

~ Yunwei
