### ISSUE TITLE
OIDC-03OpenID Connect well-known configuration contains all required fields

### ISSUE THREAD

**Issue by SavannahDearing** [onc-healthit/inferno-program#80]
![infernoOIDerror](https://user-images.githubusercontent.com/58518170/82358523-a3e48380-99d4-11ea-966c-b255f0f60f30.png)

I'm trying to understand this error.  My well-known endpoint has all of the fields required, and the two messages seem to be saying that this requires RSA SHA256 signing, but also does not support it?

Is this the same error? https://github.com/onc-healthit/inferno/issues/377

Thanks!

**Comment by arscan** [comment]
@SavannahDearing -- sorry for the slow response here.  The previous test (ending in OIDC-02) is where the request occurs, and documents what was received from the server.  Could you take a look there to see what exactly was returned from the server for the well-known endpoint request?  Does it contain all required fields?

For example:

![Screen Shot 2020-05-27 at 10 48 30 AM](https://user-images.githubusercontent.com/412901/83035959-17574800-a008-11ea-9a3a-f68abb46ea0f.png)

**Comment by SavannahDearing** [comment]
All of the fields were there, but I had somehow added an additional space to one of the items.. In fixing that I no longer have this error.

Now failing on OIDC-06.. will look into this more, but seems similar to the verification problem in the other ticket.

**Comment by SavannahDearing** [comment]
![oidc-06](https://user-images.githubusercontent.com/58518170/83183649-287e8280-a0f6-11ea-9a55-53467db3a8e4.png)

payload content:
        "aud" : "CLIENTID",
        "exp" : "1590696820",
        "fhirUser" : "https://www.medentmobiletest.com/fhir/R4/savcw235/Patient/PATIENTMRN",
        "iat" : "1590693220",
        "iss" : "https://www.medentmobiletest.com/fhir/R4/savcw235/",
        "sub" : "4CFA9DDB70752A6A8F4A1590693220"

the iss matches the issuer value in OIDC-02, and client id matches aud.  I did fix the iss, and still getting the same error.
Are there any kind of additional checks on exp, iat, or sub that could be failing? Or is the signature itself just failing?

**Comment by Jammjammjamm** [comment]
Could you provide a screenshot of the response from OIDC-02 like Rob posted above?

**Comment by SavannahDearing** [comment]
![oidc-02](https://user-images.githubusercontent.com/58518170/83185861-a42dfe80-a0f9-11ea-90fc-fcc53677bcc1.png)

**Comment by Jammjammjamm** [comment]
I have verified that this error message does specifically indicate a problem validating the signature.

**Comment by Jammjammjamm** [comment]
These issues are annoying to debug because jwt.io uses a PEM-formatted public key:
```
-----BEGIN PUBLIC KEY-----
MIIBoDANBgkqhkiG9w0BAQEFAAOCAY0AMIIBiAKCAYEAtfi+nEfu+JX2e1mu2TDi
...
GMHfYRT2TPX5SKTlHTtp0FTcpKDMDthNwBLd4HZ01arxAgER
-----END PUBLIC KEY-----
```
But OpenID Connect uses a jwk:
```
{
  "kty":"RSA",
  "e":"AQAB",
  "use":"sig",
  "alg":"RS256",
  "n":"AIHUBZRebKtjubhIN0AbP...QEyLDHWc="
}
```
Are you using the instance of inferno running on inferno.healthit.gov? If so, you can leave a link to a test run with the failure (or send it to me at smacvicar@mitre.org), and I'll take a look at it.

**Comment by SavannahDearing** [comment]
Emailed you the link
If I knew of a JWK test program I'd try it there too ! Internally I'm self testing using the values in the jwk, not the pem formatted keys

**Comment by SavannahDearing** [comment]
The overall problem was my JWK was showing the **string** encoded values for 'e' and 'n' instead of the **byte** encoded values.
My self-validation was able to validate both.  I'll leave some code here in case anyone else has issue using CryptoPP:

`  
   CryptoPP::RSA::PublicKey  pub; //Load your public key from storage
  //Extracting e: 
   CryptoPP::Integer eee(pub.GetPublicExponent());
   std::string e;
   e.resize(eee.MinEncodedSize());
   eee.Encode((CryptoPP::byte *)e.data(), e.size(), CryptoPP::Integer::UNSIGNED);
   Root["e"] = cnvbase64::EncodeB64URLwCrypto(e);
   //Extracting n works the same way but with GetModulus
`

Thanks for narrowing down the issue, I'm now passing this check !
